## Per-source tables from `*.by-source.txt`

Two views per file:

**Hierarchical subtotals** — every row contributes to its `function`, its `bucket`, and its `phase`. So a `dev_fixed_point_dprice` row counts toward `dev_fixed_point_dprice`, toward `ded`, and toward `newton` simultaneously. Blank cells mark "this is a subtotal row" — they aren't missing values. Subtotal fractions sum the row-level `frac` from the by-source.txt (true total fraction), so subtotals can sum to < 1.0 when some runtime is unattributed (`<unknown:…>` rows or sub-threshold kernels).

**Per-source rows** — every kernel-attribution row, augmented with `phase`/`bucket`/`function`, sorted by `sum_ms`. `full_chain` dropped for compactness.

### What the labels mean

- **phase** — algorithmic phase the kernel is part of:
  - `newton` — anything inside the Newton iteration (including the final outer linear solve *and* the inner per-τ ev solve / ed / ded work). Conceptually all of this exists in service of computing one Newton step.
  - `init` — the one-shot initial price guess via `spp_price_solve` (before Newton starts).
  - `other` — unrecognised, including `<unknown:…>` rows.
- **bucket** under `newton`:
  - `inner_dp_per_newton` — the per-τ Bellman ev fixed-point solve inside `ed_ded_price_all_*`'s `sol_evs`. Detected by **any chain segment whose file is `dpsolve.fut`** (which covers `dps.poly`, `sa`, `nk`, `polyad`, and any internal helpers). Takes priority over `ded`/`ed`/`newton_dispatch` so it isn't masked by also touching e.g. `bellmanJ`.
  - `ded` — derivative-of-excess-demand work. Recognised functions: `utility_dprice_*`, `ccp_scrap_dprice_*`, `dbellman_prices_*`, `dev_fixed_point_dprice`, `dv_dprice_*`, `dccp_dprice*` / `dccp_dprices_*`, `ccp_dprice_full`, `dctp_dprice*` / `dctp_dprices_*`, `ctp_dprice_full`, `ded_dprice_*`, `ded_dprice_tau_*`, `ergodic_with_dprice`. Note: a `lup.ols` inside `ergodic_with_dprice` or a `lu.ols` inside `dev_fixed_point_dprice` is `ded`, not `ed` or `newton_linsolve`.
  - `ed` — excess-demand work: `ergodic`, `demand_supply_*`, `ed_tau*`.
  - `newton_linsolve` — the outer Newton `lu.ols` that produces `dp` (chain hits `newton`/`newton_step` but does *not* hit any `ed_ded_price_all*`).
  - `newton_dispatch` — body-level code inside `ed_ded_price_all*` that the compiler fused into kernels with no deeper named call site (e.g., the `tw`-weighted population aggregations at the end of `ed_ded_price_all`). The `function` label here is the matched `ed_ded_price_all_*` variant.
- **bucket** under `init`:
  - `init_dp` — `spp_price_solve` and its internal helpers `bellman_spp_with_deriv`, `bellman_spp_with_deriv_p`, `solve_spp_single`. (These are *spp's own* Bellman implementation, only used for the initial price guess. Dpsolve traffic during init also stays here.)
- **function** — the most-specific recognised function appearing in the chain, per a precedence list (most-specific first).

In [ ]:
import re
from pathlib import Path
import pandas as pd
from IPython.display import display, Markdown

pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

HERE = Path('.').resolve()
FUT2 = HERE.parent

# ---------------------------------------------------------------------------
# Parsing the by-source.txt format
# ---------------------------------------------------------------------------
_FILELINE_RE = re.compile(r'^(?P<file>[^:]+):(?P<lines>.+)$')

def split_chain_segment(seg):
    m = _FILELINE_RE.match(seg)
    if m:
        return m.group('file'), m.group('lines')
    return seg, ''

def shorten_path(path):
    return Path(path).name

def formatted_call_path(chain_segments):
    parts = []
    for s in chain_segments:
        f, lines = split_chain_segment(s)
        parts.append(f'{shorten_path(f)}:{lines}' if lines else shorten_path(f))
    return ' → '.join(parts)

# ---------------------------------------------------------------------------
# Function-name resolution from `def`/`entry` line ranges in the .fut files.
# def/entry may be indented (they live inside `module … = { … }` blocks).
# ---------------------------------------------------------------------------
_DEF_RE = re.compile(r'^[ \t]*(?:def|entry)\s+(\w+)\b', re.MULTILINE)

def function_spans(fut_text):
    matches = list(_DEF_RE.finditer(fut_text))
    spans = []
    for i, m in enumerate(matches):
        start = fut_text.count('\n', 0, m.start()) + 1
        end = (fut_text.count('\n', 0, matches[i+1].start()) + 1
               if i + 1 < len(matches) else 10**9)
        spans.append((start, end, m.group(1)))
    return spans

_FUT_FILES = [
    'autotrade/equilibrium.fut',
    'autotrade/trmodel.fut',
    'run_equilibrium.fut',
    'run_equilibrium_man.fut',
    'run_equilibrium_full_ad.fut',
    'run_equilibrium_almost_full_ad.fut',
    'run_equilibrium_module.fut',
    'lib/github.com/diku-dk/linalg/dpsolve.fut',
    'lib/github.com/diku-dk/linalg/lu.fut',
    'lib/github.com/diku-dk/linalg/lup.fut',
]
FN_MAPS = {}
for rel in _FUT_FILES:
    p = FUT2 / rel
    if p.exists():
        FN_MAPS[rel] = function_spans(p.read_text())
print('FN_MAPS:', {k: len(v) for k, v in FN_MAPS.items()})

_SEG_RE = re.compile(r'^([^:]+):(\d+):')

def segment_file_and_fn(seg):
    """Return (file, fn) for a `file:line:cols` segment. fn is None if the
    line doesn't fall inside any recognised def/entry."""
    m = _SEG_RE.match(seg.strip())
    if not m:
        return None, None
    file, line = m.group(1), int(m.group(2))
    spans = FN_MAPS.get(file)
    if spans is None:
        return file, None
    for s, e, name in spans:
        if s <= line < e:
            return file, name
    return file, None

# ---------------------------------------------------------------------------
# Function-set bookkeeping for bucket dispatch.
# ---------------------------------------------------------------------------
DISPATCHER_FNS = {  # ed_ded_price_all variants: presence => inside a Newton step
    'ed_ded_price_all',
    'ed_ded_price_all_sa',
    'ed_ded_price_all_full_ad',
    'ed_ded_price_all_full_ad_alt',
    'ed_ded_price_all_almost_full_ad',
    'ed_ded_price_all_man',
    'ed_ded_price_all_man_sa',
    'ed_ded_price_all_dctp_only',
    'ed_ded_price_all_dv_dccp',
}
DERIVATIVE_FNS = {  # bucket = ded
    # utility / scrap / bellman / V / EV
    'utility_dprice_man', 'utility_dprice_ad',
    'ccp_scrap_dprice_man', 'ccp_scrap_dprice_ad',
    'dbellman_prices_man', 'dbellman_prices_ad',
    'dev_fixed_point_dprice',
    'dv_dprice_man', 'dv_dprice_dev',
    # ccp / ctp derivatives
    'dccp_dprices_from_du_dev', 'dccp_dprices_from_dev_dv',
    'dccp_dprice_man',
    'ccp_dprice_full',
    'dctp_dprices_from_du_dev', 'dctp_dprices_from_dccp',
    'dctp_dprice_man',
    'ctp_dprice_full',
    # ded itself (per-tau and combined)
    'ded_dprice_ad', 'ded_dprice_man',
    'ded_dprice_tau',
    'ded_dprice_tau_man',
    'ded_dprice_tau_full_ad', 'ded_dprice_tau_full_ad_alt',
    'ded_dprice_tau_almost_full_ad',
    'ded_dprice_tau_dctp_only', 'ded_dprice_tau_dv_dccp',
    # ergodic+derivative (`lup` linear solve over q and dq jointly)
    'ergodic_with_dprice',
}
ED_FNS = {  # bucket = ed
    'ergodic',
    'demand_supply_tau', 'demand_supply_all',
    'ed_tau', 'ed_tau_from_ccp',
}
# bucket = inner_dp_per_newton: detected by *file visit*, not by function set.
# Any chain segment whose file is dpsolve.fut counts as inner DP — unless the
# chain also went through spp_price_solve (init phase), which the in_init
# branch handles first.
DPSOLVE_FILE = 'lib/github.com/diku-dk/linalg/dpsolve.fut'

INIT_FNS   = {'spp_price_solve'}
NEWTON_FNS = {'newton', 'newton_step'}

# Hand-classified <unknown:…> kernels. These are multicore profile-event
# names whose generated C body has no source-location chain (lmad_copy /
# task-scheduler wrappers), so the by-source.txt reports them as <unknown>.
# Identified by reading the .c bodies in saved_c_files_for_local_profiling/
# and tracing back through the calling segred parloop's add_event chain.
# Format: kernel_name -> (phase, bucket, function).
#
# All entries below are the row permute (perm.permute p mat at lup.fut:69)
# inside lup.lup's `step` loop, called from `ergodic_with_dprice ctp dctp`
# at the end of a ded_dprice_tau* function. Same logical work; the IDs
# differ because the multicore backend emits one kernel per fused dispatcher
# variant.
_ERG_DP = ('newton', 'ded', 'ergodic_with_dprice')
KERNEL_OVERRIDES = {
    # run_equilibrium_man.c:  ded_dprice_tau_man (eq.fut:581) -> ergodic_with_dprice
    'futhark_mc_segmap_parloop_514214':       _ERG_DP,
    'futhark_mc_segmap_parloop_514214_total': _ERG_DP,
    'futhark_mc_segmap_task_514212':          _ERG_DP,
    'futhark_mc_segmap_parloop_513595':       _ERG_DP,
    'futhark_mc_segmap_parloop_513595_total': _ERG_DP,
    'futhark_mc_segmap_task_513593':          _ERG_DP,
    # run_equilibrium.c:  ded_dprice_tau (eq.fut:562) -> ergodic_with_dprice
    'futhark_mc_segmap_parloop_544339':       _ERG_DP,
    'futhark_mc_segmap_parloop_544339_total': _ERG_DP,
    'futhark_mc_segmap_task_544337':          _ERG_DP,
    'futhark_mc_segmap_parloop_544413':       _ERG_DP,
    'futhark_mc_segmap_parloop_544413_total': _ERG_DP,
    'futhark_mc_segmap_task_544411':          _ERG_DP,
}

# Hand-classified chain-end overrides. When the deepest segment matches one
# of these `file:line:cols` strings, force the classification. Used for
# kernels whose deepest source span is misleadingly tight (a single fused
# multiply / index op) but whose body actually does substantial upstream
# work that semantically belongs to a different bucket.
CHAIN_END_OVERRIDES = {
    # Fused per-tau derivative+ed assembly in ed_ded_price_all body. Deepest
    # span is the `y * w` tw multiply in `edfs_scaled`, but the kernel
    # actually writes the per-tau dctp/dccp tensor block, runs the ed_tau
    # ns-reduction, and then multiplies by tw at the end. Mostly ded work.
    'autotrade/equilibrium.fut:679:60-65': ('newton', 'ded', 'ded_dprice_tau'),      # default
    'autotrade/equilibrium.fut:884:60-65': ('newton', 'ded', 'ded_dprice_tau_man'),  # manual
}

# Most-specific to least-specific. First match in chain wins. The
# ed_ded_price_all_* family sits near the bottom so it only surfaces as the
# function label when no narrower function appears in the chain (i.e., the
# dispatch-body case).
PRECEDENCE = [
    'dev_fixed_point_dprice',
    'dv_dprice_man', 'dv_dprice_dev',
    'dccp_dprices_from_du_dev', 'dccp_dprices_from_dev_dv',
    'dccp_dprice_man',
    'dctp_dprices_from_du_dev', 'dctp_dprices_from_dccp',
    'dctp_dprice_man',
    'dbellman_prices_man', 'dbellman_prices_ad',
    'utility_dprice_man', 'utility_dprice_ad',
    'ccp_scrap_dprice_man', 'ccp_scrap_dprice_ad',
    'ergodic_with_dprice',
    'ccp_dprice_full', 'ctp_dprice_full',
    'ded_dprice_tau_man',
    'ded_dprice_tau_full_ad', 'ded_dprice_tau_full_ad_alt',
    'ded_dprice_tau_almost_full_ad',
    'ded_dprice_tau_dctp_only', 'ded_dprice_tau_dv_dccp',
    'ded_dprice_tau',
    'ded_dprice_ad', 'ded_dprice_man',
    'ergodic',
    'demand_supply_tau', 'demand_supply_all',
    'ed_tau', 'ed_tau_from_ccp',
    # Inner DP per Newton step (dpsolve.fut algorithms)
    'nk', 'sa', 'poly',
    # spp_price_solve internals (init-phase only)
    'bellman_spp_with_deriv_p', 'bellman_spp_with_deriv',
    'solve_spp_single',
    'spp_price_solve',
    # Dispatch-body fallbacks (when nothing narrower matches)
    'ed_ded_price_all_man_sa', 'ed_ded_price_all_man',
    'ed_ded_price_all_full_ad_alt', 'ed_ded_price_all_full_ad',
    'ed_ded_price_all_almost_full_ad',
    'ed_ded_price_all_dctp_only', 'ed_ded_price_all_dv_dccp',
    'ed_ded_price_all_sa', 'ed_ded_price_all',
    # Last-resort Newton fallbacks
    'newton_step', 'newton',
]

def classify(full_chain):
    """Return (phase, bucket, function)."""
    if not full_chain:
        return ('other', 'other', '?')
    if full_chain.startswith('<unknown:'):
        kernel_name = full_chain[len('<unknown:'):].rstrip('>')
        if kernel_name in KERNEL_OVERRIDES:
            return KERNEL_OVERRIDES[kernel_name]
        return ('other', 'other', '<unknown>')

    # Chain-end override: force classification when the deepest segment
    # (the kernel's profiler-attributed location) matches a known fused
    # kernel whose deepest AST node misrepresents the bulk of the work.
    segments = full_chain.split('->')
    deepest = segments[-1].strip()
    if deepest in CHAIN_END_OVERRIDES:
        return CHAIN_END_OVERRIDES[deepest]

    fns = set()
    files = set()
    for seg in segments:
        file, fn = segment_file_and_fn(seg)
        if file:
            files.add(file)
        if fn:
            fns.add(fn)
    if not fns:
        return ('other', 'other', '?')

    in_init    = bool(fns & INIT_FNS)
    in_ed_ded  = bool(fns & DISPATCHER_FNS)
    in_newton  = bool(fns & NEWTON_FNS) or in_ed_ded
    in_dpsolve = DPSOLVE_FILE in files

    if in_init and not in_newton:
        # Any dpsolve traffic that gets here came via spp — stays in init.
        phase, bucket = 'init', 'init_dp'
    elif in_ed_ded:
        phase = 'newton'
        if in_dpsolve:
            # Inner DP per Newton step — dps.poly/sa/nk inside sol_evs.
            bucket = 'inner_dp_per_newton'
        elif fns & DERIVATIVE_FNS:
            bucket = 'ded'
        elif fns & ED_FNS:
            bucket = 'ed'
        else:
            bucket = 'newton_dispatch'
    elif in_dpsolve:
        # dpsolve visited but no dispatcher in chain — count as inner DP work
        # in the Newton phase (only place dpsolve is called outside init).
        phase, bucket = 'newton', 'inner_dp_per_newton'
    elif in_newton:
        phase, bucket = 'newton', 'newton_linsolve'
    else:
        phase, bucket = 'other', 'other'

    fn_label = '?'
    for cand in PRECEDENCE:
        if cand in fns:
            fn_label = cand
            break
    return phase, bucket, fn_label

# ---------------------------------------------------------------------------
# Build the by-source DataFrame, augmented with phase/bucket/function.
# ---------------------------------------------------------------------------
def parse_by_source(path):
    rows = []
    with open(path) as f:
        for line in f:
            if line.startswith('source') or line.startswith('-'):
                continue
            line = line.rstrip()
            if not line:
                continue
            parts = line.rsplit(None, 4)
            if len(parts) != 5:
                continue
            src, nk, ct, ms, fr = parts
            try:
                nk_i, ct_i, ms_f, fr_f = int(nk), int(ct), float(ms), float(fr)
            except ValueError:
                continue
            if src.startswith('<unknown:'):
                kernel_name = src[len('<unknown:'):].rstrip('>')
                rows.append({
                    'deepest_file':  '<unknown>',
                    'deepest_lines': kernel_name,
                    'call_path':     '<unknown>',
                    '#kernels':      nk_i,
                    'count':         ct_i,
                    'sum_ms':        ms_f,
                    'frac':          fr_f,
                    'full_chain':    src,
                })
                continue
            segments = src.split('->')
            deepest_file, deepest_lines = split_chain_segment(segments[-1])
            rows.append({
                'deepest_file':  deepest_file,
                'deepest_lines': deepest_lines,
                'call_path':     formatted_call_path(segments),
                '#kernels':      nk_i,
                'count':         ct_i,
                'sum_ms':        ms_f,
                'frac':          fr_f,
                'full_chain':    src,
            })
    df = pd.DataFrame(rows)
    if df.empty:
        return df
    cls = df['full_chain'].apply(classify)
    df['phase']    = [c[0] for c in cls]
    df['bucket']   = [c[1] for c in cls]
    df['function'] = [c[2] for c in cls]
    return df.sort_values('sum_ms', ascending=False).reset_index(drop=True)

# ---------------------------------------------------------------------------
# Hierarchical subtotal table: phase -> bucket -> function. Each level's row
# shows the sum of every row beneath it (so a narrow function contributes to
# its bucket subtotal AND its phase subtotal). Fractions are summed from each
# row's by-source.txt `frac`, which is fraction of true total runtime — so
# subtotals can sum to < 1.0 when some runtime is unattributed.
# ---------------------------------------------------------------------------
def hierarchical_summary(df):
    if df.empty:
        return pd.DataFrame()
    rows = []
    phase_order = (df.groupby('phase')['sum_ms'].sum()
                     .sort_values(ascending=False).index)
    for phase in phase_order:
        pdf = df[df['phase'] == phase]
        rows.append({'phase': phase, 'bucket': '', 'function': '',
                     'sum_ms': pdf['sum_ms'].sum(),
                     'count':  int(pdf['count'].sum()),
                     'frac':   pdf['frac'].sum()})
        bucket_order = (pdf.groupby('bucket')['sum_ms'].sum()
                           .sort_values(ascending=False).index)
        for bucket in bucket_order:
            bdf = pdf[pdf['bucket'] == bucket]
            rows.append({'phase': '', 'bucket': bucket, 'function': '',
                         'sum_ms': bdf['sum_ms'].sum(),
                         'count':  int(bdf['count'].sum()),
                         'frac':   bdf['frac'].sum()})
            fn_order = (bdf.groupby('function')['sum_ms'].sum()
                           .sort_values(ascending=False).index)
            for fn in fn_order:
                fdf = bdf[bdf['function'] == fn]
                rows.append({'phase': '', 'bucket': '', 'function': fn,
                             'sum_ms': fdf['sum_ms'].sum(),
                             'count':  int(fdf['count'].sum()),
                             'frac':   fdf['frac'].sum()})
    return pd.DataFrame(rows)

In [10]:
files = sorted(HERE.glob('*.by-source.txt'))
if not files:
    print('No *.by-source.txt files in', HERE)

for p in files:
    display(Markdown(f'### `{p.name}`'))
    df = parse_by_source(p)
    if df.empty:
        display(Markdown('_(no data rows)_'))
        continue
    display(Markdown('**Hierarchical subtotals (phase → bucket → function)**'))
    display(hierarchical_summary(df))
    display(Markdown('**Per-source rows**'))
    display(df.drop(columns=['full_chain']))

### `1_spec-run_equilibrium-local-multicore.by-source.txt`

**Hierarchical subtotals (phase → bucket → function)**

,phase,bucket,function,sum_ms,count,frac
0,newton_inner,,,71390.07,57334,0.964647
1,,newton_step_other,,64941.31,8767,0.877509
2,,,newton_step,64941.31,8767,0.877509
3,,ded,,4432.11,31037,0.059888
4,,,ergodic_with_dprice,4061.34,29861,0.054878
5,,,dev_fixed_point_dprice,370.77,1176,0.005010
6,,ed,,2016.65,17530,0.027250
7,,,ergodic,1945.10,17278,0.026283
8,,,demand_supply_tau,71.55,252,0.000967
9,other,,,1502.77,15873,0.020306
10,,other,,1502.77,15873,0.020306
11,,,<unknown>,1228.18,13608,0.016596
12,,,?,274.59,2265,0.003710
13,init,,,1113.58,14,0.015047
14,,init_dp,,1113.58,14,0.015047
15,,,solve_spp_single,716.37,4,0.009680
16,,,bellman_spp_with_deriv_p,397.21,10,0.005367

**Per-source rows**

,deepest_file,deepest_lines,call_path,#kernels,count,sum_ms,frac,phase,bucket,function
0,autotrade/equilibrium.fut,679:60-65,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:679:60-65,3,252,40467.25,0.5329,newton_inner,newton_step_other,newton_step
1,autotrade/equilibrium.fut,551:60-679:122,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:551:60-679:122,9,150,13024.92,0.1714,newton_inner,newton_step_other,newton_step
2,autotrade/equilibrium.fut,551:60-679:70,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:551:60-679:70,3,42,8237.85,0.1086,newton_inner,newton_step_other,newton_step
3,lib/github.com/diku-dk/linalg/lup.fut,73:7-75:77,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:61-562:61 → equilibrium.fut:481:23-39 → lup.fut:83:51-63 → lup.fut:73:7-75:77,9,21766,3668.14,0.0482,newton_inner,ded,ergodic_with_dprice
4,lib/github.com/diku-dk/linalg/lup.fut,73:7-75:77,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:675:33-44 → equilibrium.fut:131:20-34 → lup.fut:106:18-23 → lup.fut:83:51-63 → lup.fut:73:7-75:77,9,17278,1945.10,0.0256,newton_inner,ed,ergodic
5,lib/github.com/diku-dk/linalg/lu.fut,118:32-73,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:647:42-658:58 → equilibrium.fut:646:66-654:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:118:32-73,3,1368,975.14,0.0128,newton_inner,newton_step_other,newton_step
6,lib/github.com/diku-dk/linalg/lu.fut,117:5-118:74,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:647:42-658:58 → equilibrium.fut:646:66-654:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:117:5-118:74,6,228,917.31,0.0120,newton_inner,newton_step_other,newton_step
7,autotrade/equilibrium.fut,81:101-84:99,equilibrium.fut:90:28-94:43 → equilibrium.fut:89:45-94:43 → equilibrium.fut:81:101-84:99,3,4,716.37,0.0095,init,init_dp,solve_spp_single
8,lib/github.com/diku-dk/linalg/lu.fut,44:10-58:16,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:647:42-658:58 → equilibrium.fut:646:66-654:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:122:18-46 → lu.fut:44:10-58:16,6,148,432.84,0.0057,newton_inner,newton_step_other,newton_step
9,autotrade/equilibrium.fut,37:79-61:50,equilibrium.fut:90:28-97:17 → equilibrium.fut:89:45-96:71 → equilibrium.fut:37:79-61:50,6,10,397.21,0.0053,init,init_dp,bellman_spp_with_deriv_p
10,autotrade/trmodel.fut,456:10-89,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-670:59 → trmodel.fut:462:10-463:58 → trmodel.fut:458:41-463:58 → trmodel.fut:456:10-89,6,294,277.99,0.0036,newton_inner,newton_step_other,newton_step
11,<unknown>,futhark_mc_segmap_task_544337,<unknown>,1,378,259.66,0.0034,other,other,<unknown>
12,lib/github.com/diku-dk/linalg/lup.fut,66:14-67:75,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:61-562:61 → equilibrium.fut:481:23-39 → lup.fut:83:51-63 → lup.fut:66:14-67:75,3,4072,242.23,0.0032,newton_inner,ded,ergodic_with_dprice
13,lib/github.com/diku-dk/linalg/lu.fut,117:5-118:74,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:44-559:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:117:5-118:74,6,168,230.06,0.0029,newton_inner,ded,dev_fixed_point_dprice
14,lib/github.com/diku-dk/linalg/lu.fut,46:12-49:25,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:647:42-658:58 → equilibrium.fut:646:66-654:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:122:18-46 → lu.fut:50:20-28 → lu.fut:46:12-49:25,3,4610,209.34,0.0027,newton_inner,newton_step_other,newton_step
15,<unknown>,futhark_mc_segmap_task_544411,<unknown>,1,378,203.45,0.0027,other,other,<unknown>
16,<unknown>,futhark_mc_segmap_parloop_544339_total,<unknown>,1,378,198.66,0.0026,other,other,<unknown>
17,<unknown>,futhark_mc_segmap_parloop_544413_total,<unknown>,1,378,191.79,0.0025,other,other,<unknown>
18,<unknown>,futhark_mc_segmap_parloop_544413,<unknown>,1,6048,189.99,0.0025,other,other,<unknown>
19,<unknown>,futhark_mc_segmap_parloop_544339,<unknown>,1,6048,184.63,0.0024,other,other,<unknown>
20,lib/github.com/diku-dk/linalg/lu.fut,44:10-58:16,lu.fut:44:10-58:16,6,84,170.23,0.0021,other,other,?
21,lib/github.com/diku-dk/linalg/lup.fut,71:27-35,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:61-562:61 → equilibrium.fut:481:23-39 → lup.fut:83:51-63 → lup.fut:71:27-35,3,4023,150.97,0.0019,newton_inner,ded,ergodic_with_dprice
22,lib/github.com/diku-dk/linalg/lu.fut,118:32-73,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:44-559:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:118:32-73,3,1008,140.71,0.0019,newton_inner,ded,dev_fixed_point_dprice
23,lib/github.com/diku-dk/linalg/lu.fut,46:12-49:25,lu.fut:50:20-28 → lu.fut:46:12-49:25,3,2181,104.36,0.0014,other,other,?
24,lib/github.com/diku-dk/linalg/lu.fut,44:10-58:16,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:647:42-658:58 → equilibrium.fut:646:66-654:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:145:11-51 → lu.fut:44:10-58:16,6,114,90.28,0.0012,newton_inner,newton_step_other,newton_step
25,lib/github.com/diku-dk/linalg/lu.fut,85:39-98:30,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:647:42-658:58 → equilibrium.fut:646:66-654:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-98:30,3,57,82.38,0.0012,newton_inner,newton_step_other,newton_step
26,lib/github.com/diku-dk/linalg/dpsolve.fut,182:20-63,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:647:42-658:58 → equilibrium.fut:646:66-654:123 → dpsolve.fut:228:28-237:83 → dpsolve.fut:182:20-63,3,1134,81.95,0.0010,newton_inner,newton_step_other,newton_step
27,lib/github.com/diku-dk/linalg/dpsolve.fut,261:21-42,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:647:42-658:58 → equilibrium.fut:646:66-654:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:203:17-47 → dpsolve.fut:261:21-42,3,342,78.14,0.0011,newton_inner,newton_step_other,newton_step
28,autotrade/equilibrium.fut,145:34-41,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-676:64 → equilibrium.fut:153:93-154:95 → equilibrium.fut:145:34-41,3,252,71.55,0.0009,newton_inner,ed,demand_supply_tau
29,lib/github.com/diku-dk/sorts/merge_sort.fut,164:16-26,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-669:40 → trmodel.fut:475:42-484:76 → trmodel.fut:378:9-57 → mono.fut:120:34-46 → mono.fut:89:5-17 → mono.fut:75:5-76:19 → merge_sort.fut:272:3-75 → merge_sort.fut:248:7-37 → merge_sort.fut:169:31-37 → merge_sort.fut:164:16-26,3,28,65.92,0.0008,newton_inner,newton_step_other,newton_step

### `1_spec-run_equilibrium_man-local-multicore.by-source.txt`

**Hierarchical subtotals (phase → bucket → function)**

,phase,bucket,function,sum_ms,count,frac
0,newton_inner,,,53623.84,36887,0.964910
1,,ed,,27030.35,17808,0.486386
2,,,ergodic,27030.35,17808,0.486386
3,,ded,,17126.03,13830,0.308167
4,,,ded_dprice_tau_man,15162.77,746,0.272840
5,,,ergodic_with_dprice,1495.43,11824,0.026909
6,,,dev_fixed_point_dprice,467.83,1260,0.008418
7,,newton_step_other,,9467.46,5249,0.170358
8,,,newton_step,9467.46,5249,0.170358
9,other,,,1150.62,15792,0.020704
10,,other,,1150.62,15792,0.020704
11,,,<unknown>,911.50,13608,0.016402
12,,,?,239.12,2184,0.004303
13,init,,,799.46,14,0.014386
14,,init_dp,,799.46,14,0.014386
15,,,solve_spp_single,419.23,4,0.007544
16,,,bellman_spp_with_deriv_p,380.23,10,0.006842

**Per-source rows**

,deepest_file,deepest_lines,call_path,#kernels,count,sum_ms,frac,phase,bucket,function
0,lib/github.com/diku-dk/linalg/lup.fut,73:7-75:77,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:880:33-44 → equilibrium.fut:131:20-34 → lup.fut:106:18-23 → lup.fut:83:51-63 → lup.fut:73:7-75:77,9,17808,27030.35,0.4719,newton_inner,ed,ergodic
1,autotrade/equilibrium.fut,568:60-884:122,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:568:60-884:122,9,116,9713.00,0.1695,newton_inner,ded,ded_dprice_tau_man
2,autotrade/equilibrium.fut,884:60-65,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:884:60-65,3,252,8362.41,0.1459,newton_inner,newton_step_other,newton_step
3,autotrade/equilibrium.fut,568:60-884:70,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:568:60-884:70,3,42,4874.16,0.0852,newton_inner,ded,ded_dprice_tau_man
4,lib/github.com/diku-dk/linalg/lup.fut,73:7-75:77,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:65-581:61 → equilibrium.fut:481:23-39 → lup.fut:83:51-63 → lup.fut:73:7-75:77,9,11530,957.66,0.0167,newton_inner,ded,ergodic_with_dprice
5,autotrade/equilibrium.fut,81:101-84:99,equilibrium.fut:90:28-94:43 → equilibrium.fut:89:45-94:43 → equilibrium.fut:81:101-84:99,3,4,419.23,0.0072,init,init_dp,solve_spp_single
6,autotrade/equilibrium.fut,37:79-61:50,equilibrium.fut:90:28-97:17 → equilibrium.fut:89:45-96:71 → equilibrium.fut:37:79-61:50,6,10,380.23,0.0066,init,init_dp,bellman_spp_with_deriv_p
7,autotrade/equilibrium.fut,479:38-488:41,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:65-581:61 → equilibrium.fut:479:38-488:41,3,252,367.80,0.0065,newton_inner,ded,ergodic_with_dprice
8,autotrade/equilibrium.fut,402:13-408:43,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:48-579:49 → equilibrium.fut:402:13-408:43,3,252,360.67,0.0064,newton_inner,ded,ded_dprice_tau_man
9,lib/github.com/diku-dk/linalg/lu.fut,117:5-118:74,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:852:42-863:58 → equilibrium.fut:851:70-859:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:117:5-118:74,6,228,268.85,0.0046,newton_inner,newton_step_other,newton_step
10,lib/github.com/diku-dk/linalg/lu.fut,44:10-58:16,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:852:42-863:58 → equilibrium.fut:851:70-859:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:122:18-46 → lu.fut:44:10-58:16,6,114,220.11,0.0039,newton_inner,newton_step_other,newton_step
11,lib/github.com/diku-dk/linalg/lu.fut,117:5-118:74,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:48-577:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:117:5-118:74,6,168,218.15,0.0038,newton_inner,ded,dev_fixed_point_dprice
12,autotrade/equilibrium.fut,478:78-489:18,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:65-581:61 → equilibrium.fut:478:78-489:18,3,42,169.97,0.0030,newton_inner,ded,ergodic_with_dprice
13,<unknown>,futhark_mc_segmap_task_514212,<unknown>,1,378,164.74,0.0029,other,other,<unknown>
14,autotrade/trmodel.fut,456:10-89,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-875:59 → trmodel.fut:462:10-463:58 → trmodel.fut:458:41-463:58 → trmodel.fut:456:10-89,6,294,162.91,0.0029,newton_inner,newton_step_other,newton_step
15,<unknown>,futhark_mc_segmap_parloop_514214_total,<unknown>,1,378,160.73,0.0028,other,other,<unknown>
16,lib/github.com/diku-dk/linalg/lu.fut,118:32-73,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:852:42-863:58 → equilibrium.fut:851:70-859:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:118:32-73,3,1368,156.60,0.0028,newton_inner,newton_step_other,newton_step
17,<unknown>,futhark_mc_segmap_task_513593,<unknown>,1,378,155.39,0.0027,other,other,<unknown>
18,<unknown>,futhark_mc_segmap_parloop_514214,<unknown>,1,6048,155.06,0.0027,other,other,<unknown>
19,autotrade/equilibrium.fut,401:9-409:14,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:48-579:49 → equilibrium.fut:401:9-409:14,3,42,149.54,0.0027,newton_inner,ded,ded_dprice_tau_man
20,lib/github.com/diku-dk/linalg/lu.fut,44:10-58:16,lu.fut:44:10-58:16,6,84,147.56,0.0027,other,other,?
21,<unknown>,futhark_mc_segmap_parloop_513595_total,<unknown>,1,378,143.43,0.0025,other,other,<unknown>
22,lib/github.com/diku-dk/linalg/lu.fut,44:10-58:16,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:48-577:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:145:11-51 → lu.fut:44:10-58:16,6,84,136.03,0.0024,newton_inner,ded,dev_fixed_point_dprice
23,<unknown>,futhark_mc_segmap_parloop_513595,<unknown>,1,6048,132.15,0.0023,other,other,<unknown>
24,lib/github.com/diku-dk/linalg/lu.fut,118:32-73,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:48-577:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:118:32-73,3,1008,113.65,0.0019,newton_inner,ded,dev_fixed_point_dprice
25,lib/github.com/diku-dk/sparse/mono.fut,79:17-81:38,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-874:40 → trmodel.fut:487:19-65 → mono.fut:120:34-46 → mono.fut:89:21-30 → mono.fut:79:17-81:38,3,232,103.09,0.0018,newton_inner,newton_step_other,newton_step
26,lib/github.com/diku-dk/linalg/lu.fut,57:14-28,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:852:42-863:58 → equilibrium.fut:851:70-859:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:122:18-46 → lu.fut:57:14-28,3,2647,100.22,0.0017,newton_inner,newton_step_other,newton_step
27,lib/github.com/diku-dk/linalg/lu.fut,44:10-58:16,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:852:42-863:58 → equilibrium.fut:851:70-859:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:145:11-51 → lu.fut:44:10-58:16,6,114,93.27,0.0015,newton_inner,newton_step_other,newton_step
28,lib/github.com/diku-dk/linalg/lu.fut,46:12-49:25,lu.fut:50:20-28 → lu.fut:46:12-49:25,3,2100,91.56,0.0016,other,other,?
29,autotrade/equilibrium.fut,568:60-868:106,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:568:60-868:106,6,294,65.40,0.0012,newton_inner,ded,ded_dprice_tau_man

### `3_spec-run_equilibrium-futhark01-multicore.by-source.txt`

_(no data rows)_

### `3_spec-run_equilibrium-local-multicore.by-source.txt`

**Hierarchical subtotals (phase → bucket → function)**

,phase,bucket,function,sum_ms,count,frac
0,newton_inner,,,102961.20,94719,0.904997
1,,newton_step_other,,76708.56,19877,0.674245
2,,,newton_step,76708.56,19877,0.674245
3,,ded,,20843.48,47581,0.183208
4,,,ergodic_with_dprice,12482.18,29409,0.109715
5,,,dev_fixed_point_dprice,8361.30,18172,0.073493
6,,ed,,5409.16,27261,0.047545
7,,,ergodic,5409.16,27261,0.047545
8,other,,,8007.18,38808,0.070381
9,,other,,8007.18,38808,0.070381
10,,,<unknown>,8007.18,38808,0.070381
11,newton_outer,,,1417.14,7224,0.012456
12,,newton_outer_linsolve,,1417.14,7224,0.012456
13,,,newton_step,1417.14,7224,0.012456
14,init,,,1384.09,8,0.012166
15,,init_dp,,1384.09,8,0.012166
16,,,solve_spp_single,1384.09,8,0.012166

**Per-source rows**

,deepest_file,deepest_lines,call_path,#kernels,count,sum_ms,frac,phase,bucket,function
0,autotrade/equilibrium.fut,551:60-679:122,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:551:60-679:122,9,305,29816.71,0.2485,newton_inner,newton_step_other,newton_step
1,autotrade/equilibrium.fut,679:60-65,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:679:60-65,3,756,27449.36,0.2287,newton_inner,newton_step_other,newton_step
2,lib/github.com/diku-dk/linalg/lup.fut,73:7-75:77,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:61-562:61 → equilibrium.fut:481:23-39 → lup.fut:83:51-63 → lup.fut:73:7-75:77,9,26175,9417.05,0.0784,newton_inner,ded,ergodic_with_dprice
3,autotrade/equilibrium.fut,551:60-679:70,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:551:60-679:70,3,70,9126.66,0.0761,newton_inner,newton_step_other,newton_step
4,lib/github.com/diku-dk/linalg/lup.fut,73:7-75:77,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:675:33-44 → equilibrium.fut:131:20-34 → lup.fut:106:18-23 → lup.fut:83:51-63 → lup.fut:73:7-75:77,9,27261,5409.16,0.0451,newton_inner,ed,ergodic
5,lib/github.com/diku-dk/linalg/perm.fut,49:17-23,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:61-562:61 → equilibrium.fut:481:23-39 → lup.fut:83:51-63 → lup.fut:70:13-29 → perm.fut:49:17-23,3,3234,3065.13,0.0255,newton_inner,ded,ergodic_with_dprice
6,lib/github.com/diku-dk/linalg/lu.fut,117:5-118:74,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:647:42-658:58 → equilibrium.fut:646:66-654:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:117:5-118:74,6,588,2398.44,0.0200,newton_inner,newton_step_other,newton_step
7,<unknown>,futhark_mc_segmap_parloop_544339,<unknown>,1,17248,2102.40,0.0175,other,other,<unknown>
8,lib/github.com/diku-dk/linalg/lu.fut,118:32-73,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:647:42-658:58 → equilibrium.fut:646:66-654:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:118:32-73,3,6300,1843.50,0.0154,newton_inner,newton_step_other,newton_step
9,<unknown>,futhark_mc_segmap_parloop_544413,<unknown>,1,17248,1840.11,0.0153,other,other,<unknown>
10,lib/github.com/diku-dk/linalg/lu.fut,85:39-97:31,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:44-559:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-97:31,3,700,1692.27,0.0142,newton_inner,ded,dev_fixed_point_dprice
11,lib/github.com/diku-dk/linalg/lu.fut,85:39-96:39,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:647:42-658:58 → equilibrium.fut:646:66-654:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-96:39,3,7560,1657.32,0.0138,newton_inner,newton_step_other,newton_step
12,lib/github.com/diku-dk/linalg/lu.fut,117:5-118:74,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:44-559:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:117:5-118:74,6,588,1578.19,0.0130,newton_inner,ded,dev_fixed_point_dprice
13,lib/github.com/diku-dk/linalg/lu.fut,85:39-97:31,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:647:42-658:58 → equilibrium.fut:646:66-654:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-97:31,3,700,1556.09,0.0130,newton_inner,newton_step_other,newton_step
14,lib/github.com/diku-dk/linalg/lu.fut,85:39-96:39,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:44-559:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-96:39,3,7560,1433.11,0.0120,newton_inner,ded,dev_fixed_point_dprice
15,lib/github.com/diku-dk/linalg/lu.fut,85:39-98:30,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:44-559:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-98:30,3,252,1399.59,0.0117,newton_inner,ded,dev_fixed_point_dprice
16,autotrade/equilibrium.fut,81:101-84:99,equilibrium.fut:90:28-94:43 → equilibrium.fut:89:45-94:43 → equilibrium.fut:81:101-84:99,3,8,1384.09,0.0115,init,init_dp,solve_spp_single
17,lib/github.com/diku-dk/linalg/lu.fut,85:39-98:30,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:647:42-658:58 → equilibrium.fut:646:66-654:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-98:30,3,252,1201.50,0.0101,newton_inner,newton_step_other,newton_step
18,autotrade/trmodel.fut,456:10-89,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-670:59 → trmodel.fut:462:10-463:58 → trmodel.fut:458:41-463:58 → trmodel.fut:456:10-89,6,826,1120.56,0.0094,newton_inner,newton_step_other,newton_step
19,<unknown>,futhark_mc_segmap_task_544411,<unknown>,1,1078,1069.92,0.0089,other,other,<unknown>
20,<unknown>,futhark_mc_segmap_task_544337,<unknown>,1,1078,1020.09,0.0085,other,other,<unknown>
21,<unknown>,futhark_mc_segmap_parloop_544413_total,<unknown>,1,1078,994.04,0.0083,other,other,<unknown>
22,<unknown>,futhark_mc_segmap_parloop_544339_total,<unknown>,1,1078,980.62,0.0082,other,other,<unknown>
23,lib/github.com/diku-dk/linalg/lu.fut,118:32-73,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:44-559:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:118:32-73,3,6300,832.39,0.0070,newton_inner,ded,dev_fixed_point_dprice
24,lib/github.com/diku-dk/linalg/lu.fut,62:59-71:16,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:44-559:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:126:27-63 → lu.fut:62:59-71:16,3,252,810.01,0.0067,newton_inner,ded,dev_fixed_point_dprice
25,lib/github.com/diku-dk/linalg/lu.fut,66:21-70:28,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:44-559:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:126:27-63 → lu.fut:66:21-70:28,3,2520,615.74,0.0051,newton_inner,ded,dev_fixed_point_dprice
26,lib/github.com/diku-dk/linalg/lu.fut,117:5-118:74,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:47:20-49 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:117:5-118:74,6,294,563.19,0.0045,newton_outer,newton_outer_linsolve,newton_step
27,lib/github.com/diku-dk/linalg/lu.fut,76:15-80:22,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:647:42-658:58 → equilibrium.fut:646:66-654:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:130:27-63 → lu.fut:76:15-80:22,3,2520,538.42,0.0045,newton_inner,newton_step_other,newton_step
28,lib/github.com/diku-dk/linalg/lu.fut,118:32-73,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:47:20-49 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:118:32-73,3,3150,431.91,0.0036,newton_outer,newton_outer_linsolve,newton_step
29,lib/github.com/diku-dk/linalg/lu.fut,85:39-96:39,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:47:20-49 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-96:39,3,3780,422.04,0.0035,newton_outer,newton_outer_linsolve,newton_step

### `3_spec-run_equilibrium_man-futhark01-multicore.by-source.txt`

_(no data rows)_

### `3_spec-run_equilibrium_man-local-multicore.by-source.txt`

**Hierarchical subtotals (phase → bucket → function)**

,phase,bucket,function,sum_ms,count,frac
0,newton_inner,,,74658.17,93597,0.709972
1,,ded,,56776.22,48003,0.539921
2,,,ded_dprice_tau_man,33327.84,1194,0.316936
3,,,ergodic_with_dprice,16171.70,31409,0.153787
4,,,dev_fixed_point_dprice,7276.68,15400,0.069199
5,,newton_step_other,,14413.08,19502,0.137063
6,,,newton_step,14413.08,19502,0.137063
7,,ed,,3468.87,26092,0.032988
8,,,ergodic,2943.87,25840,0.027995
9,,,demand_supply_tau,525.00,252,0.004993
10,other,,,28661.67,38808,0.272562
11,,other,,28661.67,38808,0.272562
12,,,<unknown>,28661.67,38808,0.272562
13,init,,,1337.72,8,0.012721
14,,init_dp,,1337.72,8,0.012721
15,,,solve_spp_single,1337.72,8,0.012721
16,newton_outer,,,498.90,294,0.004744
17,,newton_outer_linsolve,,498.90,294,0.004744
18,,,newton_step,498.90,294,0.004744

**Per-source rows**

,deepest_file,deepest_lines,call_path,#kernels,count,sum_ms,frac,phase,bucket,function
0,autotrade/equilibrium.fut,568:60-884:122,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:568:60-884:122,9,298,22722.84,0.2020,newton_inner,ded,ded_dprice_tau_man
1,<unknown>,futhark_mc_segmap_parloop_514214,<unknown>,1,17248,19082.77,0.1698,other,other,<unknown>
2,autotrade/equilibrium.fut,884:60-65,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:884:60-65,3,756,7759.69,0.0691,newton_inner,newton_step_other,newton_step
3,lib/github.com/diku-dk/linalg/lup.fut,73:7-75:77,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:65-581:61 → equilibrium.fut:481:23-39 → lup.fut:83:51-63 → lup.fut:73:7-75:77,9,30583,7503.10,0.0668,newton_inner,ded,ergodic_with_dprice
4,autotrade/equilibrium.fut,479:38-488:41,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:65-581:61 → equilibrium.fut:479:38-488:41,3,756,6575.84,0.0585,newton_inner,ded,ergodic_with_dprice
5,autotrade/equilibrium.fut,402:13-408:43,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:48-579:49 → equilibrium.fut:402:13-408:43,3,756,5841.22,0.0519,newton_inner,ded,ded_dprice_tau_man
6,<unknown>,futhark_mc_segmap_task_514212,<unknown>,1,1078,3070.88,0.0273,other,other,<unknown>
7,<unknown>,futhark_mc_segmap_parloop_514214_total,<unknown>,1,1078,3050.38,0.0271,other,other,<unknown>
8,lib/github.com/diku-dk/linalg/lup.fut,73:7-75:77,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:880:33-44 → equilibrium.fut:131:20-34 → lup.fut:106:18-23 → lup.fut:83:51-63 → lup.fut:73:7-75:77,9,25840,2943.87,0.0262,newton_inner,ed,ergodic
9,autotrade/equilibrium.fut,568:60-884:70,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:568:60-884:70,3,70,2677.15,0.0238,newton_inner,ded,ded_dprice_tau_man
10,autotrade/equilibrium.fut,478:78-489:18,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:65-581:61 → equilibrium.fut:478:78-489:18,3,70,2092.76,0.0186,newton_inner,ded,ergodic_with_dprice
11,autotrade/equilibrium.fut,401:9-409:14,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:48-579:49 → equilibrium.fut:401:9-409:14,3,70,2086.63,0.0185,newton_inner,ded,ded_dprice_tau_man
12,lib/github.com/diku-dk/linalg/lu.fut,117:5-118:74,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:48-577:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:117:5-118:74,6,588,2085.98,0.0186,newton_inner,ded,dev_fixed_point_dprice
13,<unknown>,futhark_mc_segmap_parloop_513595,<unknown>,1,17248,1871.57,0.0167,other,other,<unknown>
14,lib/github.com/diku-dk/linalg/lu.fut,118:32-73,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:48-577:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:118:32-73,3,6300,1685.04,0.0149,newton_inner,ded,dev_fixed_point_dprice
15,lib/github.com/diku-dk/linalg/lu.fut,117:5-118:74,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:852:42-863:58 → equilibrium.fut:851:70-859:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:117:5-118:74,6,588,1362.46,0.0121,newton_inner,newton_step_other,newton_step
16,autotrade/equilibrium.fut,81:101-84:99,equilibrium.fut:90:28-94:43 → equilibrium.fut:89:45-94:43 → equilibrium.fut:81:101-84:99,3,8,1337.72,0.0120,init,init_dp,solve_spp_single
17,lib/github.com/diku-dk/linalg/lu.fut,85:39-98:30,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:48-577:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-98:30,3,252,1218.90,0.0108,newton_inner,ded,dev_fixed_point_dprice
18,lib/github.com/diku-dk/linalg/lu.fut,85:39-97:31,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:48-577:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-97:31,3,700,1208.45,0.0108,newton_inner,ded,dev_fixed_point_dprice
19,lib/github.com/diku-dk/linalg/lu.fut,85:39-96:39,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:48-577:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-96:39,3,7560,1078.31,0.0096,newton_inner,ded,dev_fixed_point_dprice
20,autotrade/trmodel.fut,456:10-89,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-875:59 → trmodel.fut:462:10-463:58 → trmodel.fut:458:41-463:58 → trmodel.fut:456:10-89,6,826,1049.77,0.0094,newton_inner,newton_step_other,newton_step
21,lib/github.com/diku-dk/linalg/lu.fut,85:39-97:31,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:852:42-863:58 → equilibrium.fut:851:70-859:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-97:31,3,700,957.00,0.0085,newton_inner,newton_step_other,newton_step
22,lib/github.com/diku-dk/linalg/lu.fut,85:39-96:39,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:852:42-863:58 → equilibrium.fut:851:70-859:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-96:39,3,7560,956.69,0.0085,newton_inner,newton_step_other,newton_step
23,lib/github.com/diku-dk/linalg/lu.fut,118:32-73,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:852:42-863:58 → equilibrium.fut:851:70-859:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:118:32-73,3,6300,935.29,0.0083,newton_inner,newton_step_other,newton_step
24,lib/github.com/diku-dk/linalg/lu.fut,85:39-98:30,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:852:42-863:58 → equilibrium.fut:851:70-859:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-98:30,3,252,861.83,0.0077,newton_inner,newton_step_other,newton_step
25,<unknown>,futhark_mc_segmap_task_513593,<unknown>,1,1078,802.23,0.0071,other,other,<unknown>
26,<unknown>,futhark_mc_segmap_parloop_513595_total,<unknown>,1,1078,783.84,0.0070,other,other,<unknown>
27,lib/github.com/diku-dk/linalg/lu.fut,76:15-80:22,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:852:42-863:58 → equilibrium.fut:851:70-859:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:130:27-63 → lu.fut:76:15-80:22,3,2520,530.35,0.0047,newton_inner,newton_step_other,newton_step
28,autotrade/equilibrium.fut,145:34-41,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-881:64 → equilibrium.fut:153:93-154:95 → equilibrium.fut:145:34-41,3,252,525.00,0.0047,newton_inner,ed,demand_supply_tau
29,lib/github.com/diku-dk/linalg/lu.fut,117:5-118:74,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:47:20-49 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:117:5-118:74,6,294,498.90,0.0045,newton_outer,newton_outer_linsolve,newton_step

### `5_spec-run_equilibrium-local-multicore.by-source.txt`

**Hierarchical subtotals (phase → bucket → function)**

,phase,bucket,function,sum_ms,count,frac
0,newton_inner,,,259101.08,201595,0.866373
1,,newton_step_other,,213825.08,50604,0.714981
2,,,newton_step,213825.08,50604,0.714981
3,,ded,,27617.79,96353,0.092347
4,,,dev_fixed_point_dprice,20080.04,60096,0.067143
5,,,ergodic_with_dprice,7537.75,36257,0.025204
6,,ed,,17658.21,54638,0.059045
7,,,ergodic,17658.21,54638,0.059045
8,other,,,28999.34,54864,0.096967
9,,other,,28999.34,54864,0.096967
10,,,<unknown>,28999.34,54864,0.096967
11,newton_outer,,,7290.55,17088,0.024378
12,,newton_outer_linsolve,,7290.55,17088,0.024378
13,,,newton_step,7290.55,17088,0.024378
14,init,,,3673.23,12,0.012282
15,,init_dp,,3673.23,12,0.012282
16,,,solve_spp_single,3673.23,12,0.012282

**Per-source rows**

,deepest_file,deepest_lines,call_path,#kernels,count,sum_ms,frac,phase,bucket,function
0,autotrade/equilibrium.fut,679:60-65,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:679:60-65,3,1080,100377.90,0.3216,newton_inner,newton_step_other,newton_step
1,autotrade/equilibrium.fut,551:60-679:122,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:551:60-679:122,9,276,53084.29,0.1702,newton_inner,newton_step_other,newton_step
2,autotrade/equilibrium.fut,551:60-679:70,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:551:60-679:70,3,84,40577.26,0.1301,newton_inner,newton_step_other,newton_step
3,lib/github.com/diku-dk/linalg/lup.fut,66:14-67:75,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:675:33-44 → equilibrium.fut:131:20-34 → lup.fut:106:18-23 → lup.fut:83:51-63 → lup.fut:66:14-67:75,3,20052,9197.11,0.0295,newton_inner,ed,ergodic
4,lib/github.com/diku-dk/linalg/lup.fut,73:7-75:77,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:675:33-44 → equilibrium.fut:131:20-34 → lup.fut:106:18-23 → lup.fut:83:51-63 → lup.fut:73:7-75:77,9,34586,8461.10,0.0271,newton_inner,ed,ergodic
5,lib/github.com/diku-dk/linalg/lup.fut,73:7-75:77,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:61-562:61 → equilibrium.fut:481:23-39 → lup.fut:83:51-63 → lup.fut:73:7-75:77,9,36257,7537.75,0.0243,newton_inner,ded,ergodic_with_dprice
6,<unknown>,futhark_mc_segmap_parloop_544413,<unknown>,1,24384,6907.79,0.0221,other,other,<unknown>
7,<unknown>,futhark_mc_segmap_parloop_544339,<unknown>,1,24384,6240.93,0.0200,other,other,<unknown>
8,<unknown>,futhark_mc_segmap_task_544337,<unknown>,1,1524,6096.22,0.0195,other,other,<unknown>
9,<unknown>,futhark_mc_segmap_parloop_544339_total,<unknown>,1,1524,6061.89,0.0194,other,other,<unknown>
10,lib/github.com/diku-dk/linalg/lu.fut,85:39-97:31,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:44-559:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-97:31,3,2352,4902.11,0.0157,newton_inner,ded,dev_fixed_point_dprice
11,lib/github.com/diku-dk/linalg/lu.fut,85:39-97:31,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:647:42-658:58 → equilibrium.fut:646:66-654:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-97:31,3,2352,4784.54,0.0154,newton_inner,newton_step_other,newton_step
12,lib/github.com/diku-dk/linalg/lu.fut,85:39-96:39,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:44-559:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-96:39,3,30240,4564.40,0.0147,newton_inner,ded,dev_fixed_point_dprice
13,lib/github.com/diku-dk/linalg/lu.fut,85:39-96:39,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:647:42-658:58 → equilibrium.fut:646:66-654:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-96:39,3,30240,4562.98,0.0146,newton_inner,newton_step_other,newton_step
14,autotrade/equilibrium.fut,81:101-84:99,equilibrium.fut:90:28-94:43 → equilibrium.fut:89:45-94:43 → equilibrium.fut:81:101-84:99,3,12,3673.23,0.0118,init,init_dp,solve_spp_single
15,lib/github.com/diku-dk/linalg/lu.fut,117:5-118:74,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:44-559:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:117:5-118:74,6,1080,3298.77,0.0105,newton_inner,ded,dev_fixed_point_dprice
16,lib/github.com/diku-dk/linalg/lu.fut,117:5-118:74,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:647:42-658:58 → equilibrium.fut:646:66-654:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:117:5-118:74,6,1080,3019.52,0.0097,newton_inner,newton_step_other,newton_step
17,lib/github.com/diku-dk/linalg/lu.fut,85:39-98:30,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:44-559:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-98:30,3,504,2922.42,0.0094,newton_inner,ded,dev_fixed_point_dprice
18,lib/github.com/diku-dk/linalg/lu.fut,85:39-98:30,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:647:42-658:58 → equilibrium.fut:646:66-654:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-98:30,3,504,2756.89,0.0088,newton_inner,newton_step_other,newton_step
19,autotrade/trmodel.fut,456:10-89,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-670:59 → trmodel.fut:462:10-463:58 → trmodel.fut:458:41-463:58 → trmodel.fut:456:10-89,6,1164,2755.16,0.0088,newton_inner,newton_step_other,newton_step
20,lib/github.com/diku-dk/linalg/lu.fut,85:39-96:39,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:47:20-49 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-96:39,3,15120,2528.50,0.0081,newton_outer,newton_outer_linsolve,newton_step
21,lib/github.com/diku-dk/linalg/lu.fut,85:39-97:31,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:47:20-49 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-97:31,3,1176,2191.87,0.0071,newton_outer,newton_outer_linsolve,newton_step
22,lib/github.com/diku-dk/linalg/lu.fut,118:32-73,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:44-559:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:118:32-73,3,13824,1990.11,0.0064,newton_inner,ded,dev_fixed_point_dprice
23,lib/github.com/diku-dk/linalg/lu.fut,118:32-73,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:647:42-658:58 → equilibrium.fut:646:66-654:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:118:32-73,3,13824,1906.54,0.0060,newton_inner,newton_step_other,newton_step
24,<unknown>,futhark_mc_segmap_task_544411,<unknown>,1,1524,1901.22,0.0061,other,other,<unknown>
25,<unknown>,futhark_mc_segmap_parloop_544413_total,<unknown>,1,1524,1791.29,0.0057,other,other,<unknown>
26,lib/github.com/diku-dk/linalg/lu.fut,117:5-118:74,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:47:20-49 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:117:5-118:74,6,540,1442.95,0.0045,newton_outer,newton_outer_linsolve,newton_step
27,lib/github.com/diku-dk/linalg/lu.fut,66:21-70:28,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:44-559:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:126:27-63 → lu.fut:66:21-70:28,3,6048,1244.43,0.0040,newton_inner,ded,dev_fixed_point_dprice
28,lib/github.com/diku-dk/linalg/lu.fut,76:15-80:22,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium.fut:15:26-46 → equilibrium.fut:646:46-661:44 → equilibrium.fut:550:44-559:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:130:27-63 → lu.fut:76:15-80:22,3,6048,1157.80,0.0037,newton_inner,ded,dev_fixed_point_dprice
29,lib/github.com/diku-dk/linalg/lu.fut,85:39-98:30,run_equilibrium.fut:110:7-112:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:47:20-49 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-98:30,3,252,1127.23,0.0036,newton_outer,newton_outer_linsolve,newton_step

### `5_spec-run_equilibrium_man-local-multicore.by-source.txt`

**Hierarchical subtotals (phase → bucket → function)**

,phase,bucket,function,sum_ms,count,frac
0,newton_inner,,,274071.94,171702,0.576392
1,,ded,,217647.63,86201,0.457728
2,,,ded_dprice_tau_man,119200.92,1524,0.250688
3,,,ergodic_with_dprice,74917.36,36677,0.157556
4,,,dev_fixed_point_dprice,23529.35,48000,0.049484
5,,newton_step_other,,48217.98,50244,0.101406
6,,,newton_step,48217.98,50244,0.101406
7,,ed,,8206.33,35257,0.017258
8,,,ergodic,8206.33,35257,0.017258
9,other,,,189276.94,54864,0.398062
10,,other,,189276.94,54864,0.398062
11,,,<unknown>,189276.94,54864,0.398062
12,newton_outer,,,7576.21,22572,0.015933
13,,newton_outer_linsolve,,7576.21,22572,0.015933
14,,,newton_step,7576.21,22572,0.015933
15,init,,,4570.80,12,0.009613
16,,init_dp,,4570.80,12,0.009613
17,,,solve_spp_single,4570.80,12,0.009613

**Per-source rows**

,deepest_file,deepest_lines,call_path,#kernels,count,sum_ms,frac,phase,bucket,function
0,<unknown>,futhark_mc_segmap_parloop_514214,<unknown>,1,24384,148903.10,0.2997,other,other,<unknown>
1,autotrade/equilibrium.fut,568:60-884:122,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:568:60-884:122,9,276,83444.94,0.1679,newton_inner,ded,ded_dprice_tau_man
2,lib/github.com/diku-dk/linalg/lup.fut,73:7-75:77,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:65-581:61 → equilibrium.fut:481:23-39 → lup.fut:83:51-63 → lup.fut:73:7-75:77,9,35513,43656.34,0.0879,newton_inner,ded,ergodic_with_dprice
3,autotrade/equilibrium.fut,479:38-488:41,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:65-581:61 → equilibrium.fut:479:38-488:41,3,1080,23235.16,0.0468,newton_inner,ded,ergodic_with_dprice
4,autotrade/equilibrium.fut,884:60-65,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:884:60-65,3,1080,22554.44,0.0454,newton_inner,newton_step_other,newton_step
5,autotrade/equilibrium.fut,402:13-408:43,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:48-579:49 → equilibrium.fut:402:13-408:43,3,1080,19781.47,0.0397,newton_inner,ded,ded_dprice_tau_man
6,<unknown>,futhark_mc_segmap_task_514212,<unknown>,1,1524,14498.06,0.0292,other,other,<unknown>
7,<unknown>,futhark_mc_segmap_parloop_514214_total,<unknown>,1,1524,14446.49,0.0291,other,other,<unknown>
8,autotrade/equilibrium.fut,568:60-884:70,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:568:60-884:70,3,84,9182.66,0.0185,newton_inner,ded,ded_dprice_tau_man
9,lib/github.com/diku-dk/linalg/lup.fut,73:7-75:77,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:880:33-44 → equilibrium.fut:131:20-34 → lup.fut:106:18-23 → lup.fut:83:51-63 → lup.fut:73:7-75:77,9,35257,8206.33,0.0166,newton_inner,ed,ergodic
10,autotrade/equilibrium.fut,478:78-489:18,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:65-581:61 → equilibrium.fut:478:78-489:18,3,84,8025.86,0.0162,newton_inner,ded,ergodic_with_dprice
11,<unknown>,futhark_mc_segmap_parloop_513595,<unknown>,1,24384,7192.82,0.0145,other,other,<unknown>
12,autotrade/equilibrium.fut,401:9-409:14,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:48-579:49 → equilibrium.fut:401:9-409:14,3,84,6791.85,0.0137,newton_inner,ded,ded_dprice_tau_man
13,lib/github.com/diku-dk/linalg/lu.fut,85:39-97:31,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:48-577:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-97:31,3,2352,5940.11,0.0120,newton_inner,ded,dev_fixed_point_dprice
14,lib/github.com/diku-dk/linalg/lu.fut,85:39-97:31,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:852:42-863:58 → equilibrium.fut:851:70-859:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-97:31,3,2352,5801.63,0.0117,newton_inner,newton_step_other,newton_step
15,lib/github.com/diku-dk/linalg/lu.fut,85:39-96:39,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:852:42-863:58 → equilibrium.fut:851:70-859:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-96:39,3,30240,5510.43,0.0111,newton_inner,newton_step_other,newton_step
16,lib/github.com/diku-dk/linalg/lu.fut,85:39-96:39,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:48-577:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-96:39,3,30240,5301.70,0.0106,newton_inner,ded,dev_fixed_point_dprice
17,lib/github.com/diku-dk/linalg/lu.fut,117:5-118:74,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:48-577:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:117:5-118:74,6,1080,5221.95,0.0106,newton_inner,ded,dev_fixed_point_dprice
18,lib/github.com/diku-dk/linalg/lu.fut,117:5-118:74,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:852:42-863:58 → equilibrium.fut:851:70-859:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:117:5-118:74,6,1080,4614.67,0.0093,newton_inner,newton_step_other,newton_step
19,autotrade/equilibrium.fut,81:101-84:99,equilibrium.fut:90:28-94:43 → equilibrium.fut:89:45-94:43 → equilibrium.fut:81:101-84:99,3,12,4570.80,0.0091,init,init_dp,solve_spp_single
20,lib/github.com/diku-dk/linalg/lu.fut,85:39-98:30,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:48-577:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-98:30,3,504,3778.28,0.0076,newton_inner,ded,dev_fixed_point_dprice
21,lib/github.com/diku-dk/linalg/lu.fut,85:39-98:30,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:852:42-863:58 → equilibrium.fut:851:70-859:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-98:30,3,504,3607.59,0.0073,newton_inner,newton_step_other,newton_step
22,lib/github.com/diku-dk/linalg/lu.fut,118:32-73,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-866:48 → equilibrium.fut:567:48-577:57 → equilibrium.fut:292:21-41 → lu.fut:157:13-28 → lu.fut:118:32-73,3,13824,3287.31,0.0066,newton_inner,ded,dev_fixed_point_dprice
23,lib/github.com/diku-dk/linalg/lu.fut,117:5-118:74,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:47:20-49 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:117:5-118:74,6,540,3186.86,0.0066,newton_outer,newton_outer_linsolve,newton_step
24,autotrade/trmodel.fut,456:10-89,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:851:50-875:59 → trmodel.fut:462:10-463:58 → trmodel.fut:458:41-463:58 → trmodel.fut:456:10-89,6,1164,3149.98,0.0063,newton_inner,newton_step_other,newton_step
25,lib/github.com/diku-dk/linalg/lu.fut,118:32-73,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:35:8-38:35 → run_equilibrium_module.fut:28:8-32:45 → run_equilibrium_man.fut:14:26-50 → equilibrium.fut:852:42-863:58 → equilibrium.fut:851:70-859:123 → dpsolve.fut:228:28-238:57 → dpsolve.fut:206:32-63 → dpsolve.fut:257:48-64 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:118:32-73,3,13824,2979.24,0.0059,newton_inner,newton_step_other,newton_step
26,lib/github.com/diku-dk/linalg/lu.fut,118:32-73,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:47:20-49 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:118:32-73,3,6912,2302.76,0.0046,newton_outer,newton_outer_linsolve,newton_step
27,<unknown>,futhark_mc_segmap_task_513593,<unknown>,1,1524,2142.84,0.0043,other,other,<unknown>
28,<unknown>,futhark_mc_segmap_parloop_513595_total,<unknown>,1,1524,2093.63,0.0042,other,other,<unknown>
29,lib/github.com/diku-dk/linalg/lu.fut,85:39-96:39,run_equilibrium_man.fut:109:7-111:69 → run_equilibrium_module.fut:59:34-66:142 → run_equilibrium_module.fut:47:20-49 → lu.fut:183:17-31 → lu.fut:157:13-28 → lu.fut:134:22-77 → lu.fut:85:39-96:39,3,15120,2086.59,0.0042,newton_outer,newton_outer_linsolve,newton_step