### Notebook for processing the validation of the Futhark results

In [85]:
import ast
import re
import numpy as np
import pandas as pd
from pathlib import Path

##### Functions for processing Matlab and Futhark Prices

In [86]:
FUT_TYPE_SUFFIX = re.compile(r'(f16|f32|f64|i8|i16|i32|i64|u8|u16|u32|u64)\b')

def parse_futhark_prices(path):
    """Parse the price matrix from line 1 of a Futhark validate_solve .val file.

    The first line is a Futhark literal of shape [c][Ax], e.g.
    `[[200.0f64, 169.6f64, ...], [260.0f64, ...], ...]`.
    Returns a numpy.ndarray of shape (c, Ax) with dtype float64.
    """
    with open(path) as f:
        first_line = f.readline()
    cleaned = FUT_TYPE_SUFFIX.sub('', first_line)
    nested = ast.literal_eval(cleaned)
    return np.asarray(nested, dtype=np.float64)

def parse_matlab_prices(path):
    """Parse the price matrix from a MATLAB validate_run_illustrations_test .dat file.

    The file is a CSV (one row per car type, columns = ages 0..Ax-1).
    Returns a numpy.ndarray of shape (c, Ax) with dtype float64.
    """
    return np.loadtxt(path, delimiter=',', dtype=np.float64)

In [87]:
parse_futhark_prices('validation_files/run_equilibrium-local-validate_solve-2-3-25-5-0-M.val')

array([[200.        , 169.2948619 , 141.47740163, 117.0506919 ,
         95.96637377,  77.96530383,  62.62372555,  49.514447  ,
         38.31752597,  28.83231542,  20.94596407,  14.59768623,
          9.74911362,   6.33721219,   4.18410726,   2.96706019,
          2.33557   ,   2.0274529 ,   1.88412023,   1.81988041,
          1.79051281,   1.7704009 ,   1.73140671,   1.5988312 ,
          1.06290795],
       [260.        , 225.25506523, 193.02633663, 163.79794474,
        137.68705753, 114.73608295,  94.842273  ,  77.72158179,
         62.98567507,  50.27381226,  39.32270211,  29.96686878,
         22.11232877,  15.70826562,  10.72367414,   7.11425982,
          4.74873215,   3.35688607,   2.60697298,   2.22655565,
          2.03958087,   1.94245189,   1.8640367 ,   1.70520958,
          1.1400604 ],
       [260.        , 225.25506523, 193.02633663, 163.79794474,
        137.68705753, 114.73608295,  94.842273  ,  77.72158179,
         62.98567507,  50.27381226,  39.32270211,  29.96686878,
         22.11232877,  15.70826562,  10.72367414,   7.11425982,
          4.74873215,   3.35688607,   2.60697298,   2.22655565,
          2.03958087,   1.94245189,   1.8640367 ,   1.70520958,
          1.1400604 ]])

In [88]:
parse_matlab_prices('matlab_results_for_validation/matlab-validate_solve-2-3-25-5-0.dat')

array([[200.        , 169.29486084, 141.4773999 , 117.05068984,
         95.96637165,  77.96530179,  62.62372362,  49.5144452 ,
         38.3175243 ,  28.83231391,  20.94596275,  14.59768512,
          9.7491127 ,   6.33721146,   4.18410672,   2.96705985,
          2.3355698 ,   2.02745279,   1.88412018,   1.81988038,
          1.7905128 ,   1.7704009 ,   1.73140671,   1.5988312 ,
          1.06290794],
       [260.        , 225.25506359, 193.0263338 , 163.79794114,
        137.68705352, 114.73607879,  94.84226882,  77.72157762,
         62.98567095,  50.27380827,  39.32269838,  29.96686546,
         22.11232603,  15.70826358,  10.72367279,   7.11425896,
          4.7487316 ,   3.35688573,   2.60697279,   2.22655554,
          2.03958082,   1.94245186,   1.86403669,   1.70520957,
          1.14006039],
       [260.        , 225.25506359, 193.0263338 , 163.79794114,
        137.68705352, 114.73607879,  94.84226882,  77.72157762,
         62.98567095,  50.27380827,  39.32269838,  29.96686546,
         22.11232603,  15.70826358,  10.72367279,   7.11425896,
          4.7487316 ,   3.35688573,   2.60697279,   2.22655554,
          2.03958082,   1.94245186,   1.86403669,   1.70520957,
          1.14006039]])

##### Functions for comparing Futhark and Matlab

In [89]:
_FUT_NAME_RE = re.compile(r'validate_solve-(\d+)-(\d+)-(\d+)-(\d+)-(\d+)-[A-Z]\.val$')

def compare_validation(futhark_name, rtol=1e-4, atol=1e-6,
                         val_dir='validation_files',
                         mat_dir='matlab_results_for_validation'):
      """Compare prices in a Futhark .val file against the matching MATLAB .dat file.

      Pass/fail uses numpy.allclose semantics:
          |fut - mat| <= atol + rtol * |mat|

      Parameters
      ----------
      futhark_name : str
          Filename inside `val_dir`, e.g.
          'run_equilibrium-local-validate_solve-2-7-25-5-0-C.val'.
      rtol : float, default 1e-4
          Relative tolerance (dominates for large prices).
      atol : float, default 1e-6
          Absolute tolerance floor (dominates near scrap, where prices ~ 0).
      val_dir, mat_dir : str or Path
          Directories holding the Futhark and MATLAB validation files.

      Returns
      -------
      None
          If no MATLAB file matches the parameter tuple in `futhark_name`.
      dict
          Keys:
            'within_tol'   bool   passes np.allclose(fut, mat, rtol, atol)
            'max_abs_diff' float  max |fut - mat|
            'max_rel_diff' float  max |fut - mat| / max(|mat|, atol)
            'matlab_path'  Path
      """
      m = _FUT_NAME_RE.search(futhark_name)
      if m is None:
          raise ValueError(f"Could not extract parameter tuple from: {futhark_name}")
      n, c, abar, acc0, trans = m.groups()

      matlab_name = f"matlab-validate_solve-{n}-{c}-{abar}-{acc0}-{trans}.dat"
      matlab_path = Path(mat_dir) / matlab_name
      if not matlab_path.exists():
          return None

      fut = parse_futhark_prices(Path(val_dir) / futhark_name)
      mat = parse_matlab_prices(matlab_path)

      abs_diff = np.abs(fut - mat)
      max_abs_diff = float(np.max(abs_diff))
      max_rel_diff = float(np.max(abs_diff / np.maximum(np.abs(mat), atol)))
      return {
          'within_tol':   bool(np.allclose(fut, mat, rtol=rtol, atol=atol)),
          'max_abs_diff': max_abs_diff,
          'max_rel_diff': max_rel_diff,
          'matlab_path':  matlab_path,
      }

##### Futhark Functions for parsing and summarizing validation files

In [90]:
def parse_futhark_validation(path):
      """Parse all fields from a Futhark validate_solve .val file.

      Returns a dict with:
        'prices'        ndarray  shape (c, Ax), float64
        'max_abs_ed'    float
        'stat_res'      float
        'norm_err'      float
        'min_q'         float
        'iter'          int      Newton outer iterations
        'conv'          bool     convergence flag
        'sa_iters_tot'  list[int]  per-household SA iteration totals
        'nk_iters_tot'  list[int]  per-household NK iteration totals
        'rtrips_tot'    list[int]  per-household round-trip totals
      """
      with open(path) as f:
          lines = f.read().splitlines()

      def strip(s):
          return FUT_TYPE_SUFFIX.sub('', s)

      return {
          'prices':       np.asarray(ast.literal_eval(strip(lines[0])), dtype=np.float64),
          'max_abs_ed':   float(ast.literal_eval(strip(lines[1]))),
          'stat_res':     float(ast.literal_eval(strip(lines[2]))),
          'norm_err':     float(ast.literal_eval(strip(lines[3]))),
          'min_q':        float(ast.literal_eval(strip(lines[4]))),
          'iter':         int(ast.literal_eval(strip(lines[5]))),
          'conv':         lines[6].strip() == 'true',
          'sa_iters_tot': list(ast.literal_eval(strip(lines[7]))),
          'nk_iters_tot': list(ast.literal_eval(strip(lines[8]))),
          'rtrips_tot':   list(ast.literal_eval(strip(lines[9]))),
      }

In [91]:
def summarize_futhark_run(futhark_name, rtol=1e-4, atol=1e-6,
                            val_dir='validation_files',
                            mat_dir='matlab_results_for_validation'):
      """All Futhark validation fields (except the price matrix) plus the
      MATLAB comparison verdict.

      See parse_futhark_validation for the remaining field names. Adds:
        'within_tol'    bool or None  (None if no matching MATLAB file)
        'max_abs_diff'  float or None
        'max_rel_diff'  float or None
        'matlab_path'   Path  or None
      """
      fields = parse_futhark_validation(Path(val_dir) / futhark_name)
      del fields['prices']
      cmp = compare_validation(futhark_name, rtol=rtol, atol=atol,
                               val_dir=val_dir, mat_dir=mat_dir)
      if cmp is None:
          fields.update(within_tol=None, max_abs_diff=None,
                        max_rel_diff=None, matlab_path=None)
      else:
          fields.update(cmp)
      return fields

##### Summarize all Futhark Validation Files

In [92]:
_FUT_FILE_RE = re.compile(
      r'^(?P<run_equi>[^-]+)-(?P<val_name>.+?)-validate_solve-'
      r'(?P<n>\d+)-(?P<c>\d+)-(?P<abar>\d+)-(?P<acc0>\d+)-(?P<trans>\d+)-'
      r'(?P<backend>[A-Z])\.val$'
  )

def summarize_all_futhark(rtol=1e-4, atol=1e-6,
                            val_dir='validation_files',
                            mat_dir='matlab_results_for_validation'):
      """Summarize every .val file in `val_dir`.

      Each row is a dict carrying:
        filename       str       the .val filename
        run_equi       str       e.g. 'run_equilibrium' / 'run_equilibrium_man'
        val_name       str       VAL_NAME tag, e.g. 'local' / 'default'
        n, c, abar, acc0, trans  int   parameter tuple
        backend        str       'C', 'M', 'O', 'U'
      plus everything `summarize_futhark_run` returns (prices, max_abs_ed,
      stat_res, norm_err, min_q, iter, conv, sa_iters_tot, nk_iters_tot,
      rtrips_tot, within_tol, max_abs_diff, max_rel_diff, matlab_path).

      Files whose names don't match the validate_solve pattern are skipped.
      """
      val_dir = Path(val_dir)
      int_keys = {'n', 'c', 'abar', 'acc0', 'trans'}
      rows = []
      for path in sorted(val_dir.glob('*.val')):
          m = _FUT_FILE_RE.match(path.name)
          if m is None:
              continue
          meta = {k: int(v) if k in int_keys else v
                  for k, v in m.groupdict().items()}
          meta['filename'] = path.name
          summary = summarize_futhark_run(path.name, rtol=rtol, atol=atol,
                                          val_dir=val_dir, mat_dir=mat_dir)
          rows.append({**meta, **summary})
      return rows

In [93]:
rows = summarize_all_futhark()
print(rows[0])  # Print the first row, adjust index as needed

{'run_equi': 'run_equilibrium', 'val_name': '3_local_new', 'n': 2, 'c': 1, 'abar': 25, 'acc0': 5, 'trans': 0, 'backend': 'C', 'filename': 'run_equilibrium-3_local_new-validate_solve-2-1-25-5-0-C.val', 'max_abs_ed': 1.77606e-10, 'stat_res': 3e-15, 'norm_err': 0.0, 'min_q': 0.00047250047593, 'iter': 7, 'conv': True, 'sa_iters_tot': [30, 33], 'nk_iters_tot': [12, 7], 'rtrips_tot': [7, 7], 'within_tol': True, 'max_abs_diff': 2.064203300733425e-06, 'max_rel_diff': 1.0413759811939476e-07, 'matlab_path': WindowsPath('matlab_results_for_validation/matlab-validate_solve-2-1-25-5-0.dat')}

##### Benchmark parsing

In [94]:
def parse_matlab_benchmark(path):
    """Parse matlab_eqb_<variant>.dat. Columns: n c abar acc0 trans mean stdev se."""
    arr = np.loadtxt(path)
    if arr.ndim == 1:
        arr = arr[None, :]
    cols = ['n', 'c', 'abar', 'acc0', 'trans', 'mean', 'stdev', 'se']
    return [dict(zip(cols, row)) for row in arr]

def parse_futhark_benchmark(path):
    """Parse a Futhark bench_solve_<variant>.dat (or saved copy).
    Columns: n c abar acc0 trans backend mean stdev se."""
    rows = []
    with open(path) as f:
        for line in f:
            parts = line.split()
            if len(parts) != 9:
                continue
            rows.append({
                'n':       int(parts[0]),  'c':       int(parts[1]),
                'abar':    int(parts[2]),  'acc0':    int(parts[3]),
                'trans':   int(parts[4]),  'backend': parts[5],
                'mean':    float(parts[6]),
                'stdev':   float(parts[7]),
                'se':      float(parts[8]),
            })
    return rows

In [95]:
_SAVED_BENCH_RE = re.compile(
      r'^(?P<run_equi>[^-]+)-(?P<val_name>.+?)-bench(?P<runs>\d+)-'
      r'(?P<variant>cars_longest|cars_longer|cars_long|cars|households|age)\.dat$'
  )

def bench_time_table(variant, saved_dir='saved_futhark_benchmarks'):
    """Long-format DataFrame of bench mean & stdev for the given variant.
    One row per (source, run_equi, val_name, backend, parameter tuple)."""
    rows = []

    mat_path = Path(f'matlab_eqb_{variant}.dat')
    if mat_path.exists():
        for r in parse_matlab_benchmark(mat_path):
            rows.append({
                'source': 'matlab', 'run_equi': '-', 'val_name': '-',
                'backend': '-',     'runs': '-',
                'n': int(r['n']), 'c': int(r['c']), 'abar': int(r['abar']),
                'mean': r['mean'], 'stdev': r['stdev'],
            })

    for path in sorted(Path(saved_dir).glob(f'*-{variant}.dat')):
        m = _SAVED_BENCH_RE.match(path.name)
        if m is None:
            continue
        meta = m.groupdict()
        for r in parse_futhark_benchmark(path):
            rows.append({
                'source':   'futhark',
                'run_equi': meta['run_equi'],
                'val_name': meta['val_name'],
                'backend':  r['backend'],
                'runs':     int(meta['runs']),
                'n': r['n'], 'c': r['c'], 'abar': r['abar'],
                'mean': r['mean'], 'stdev': r['stdev'],
            })

    df = pd.DataFrame(rows)
    if not df.empty:
        sort_key = {'cars': 'c', 'households': 'n', 'age': 'abar', 'cars_long': 'c', 'cars_longer': 'c', 'cars_longest': 'c'}[variant]
        df = df.sort_values([sort_key, 'source', 'run_equi', 'val_name', 'backend'])
    return df.reset_index(drop=True)

##### Comparison Table for Validation

In [96]:
def comparison_table(variant, rtol=1e-4, atol=1e-6,
                       val_dir='validation_files',
                       mat_dir='matlab_results_for_validation'):
      """DataFrame summarising every .val file that belongs to this variant.

      Each row: one (run_equi, val_name, backend, parameter tuple) combination,
      with columns including within_tol, max_abs_diff, max_rel_diff, and the
      parsed Futhark fields (iter, conv, sa_iters_tot, nk_iters_tot, etc.).

      Note: cars_long is intentionally folded into 'cars' here -- the 'cars'
      validation table covers the whole (n=2, abar=25) plane, including the
      extended c values (17, 21). cars_long is only a separate variant for the
      bench-time tables, which read variant-specific .dat files.
      """
      rows = summarize_all_futhark(rtol=rtol, atol=atol,
                                   val_dir=val_dir, mat_dir=mat_dir)
      if variant == 'cars':
          keep = lambda r: r['n'] == 2 and r['abar'] == 25
          sort_key = 'c'
      elif variant == 'households':
          keep = lambda r: r['c'] == 7 and r['abar'] == 25
          sort_key = 'n'
      elif variant == 'age':
          keep = lambda r: r['n'] == 2 and r['c'] == 7
          sort_key = 'abar'
      else:
          raise ValueError(f"Unknown variant: {variant!r}")

      df = pd.DataFrame([r for r in rows if keep(r)])
      if not df.empty:
          df = (df.drop(columns=['matlab_path'], errors='ignore')
                  .sort_values(['run_equi', 'val_name', 'backend', sort_key])
                  .reset_index(drop=True))
      return df

##### Tables

In [97]:
for v in ['cars', 'households', 'age', 'cars_long']:
    print(f"\n=== {v}: bench times ===")
    display(bench_time_table(v))

for v in ['cars', 'households', 'age']:
    print(f"\n=== {v}: MATLAB comparison + Futhark diagnostics ===")
    display(comparison_table(v))

=== cars: bench times ===

,source,run_equi,val_name,backend,runs,n,c,abar,mean,stdev
0,futhark,run_equilibrium,3_local_new,C,3,2,1,25,0.021070,0.001137
1,futhark,run_equilibrium,3_local_new,M,3,2,1,25,0.115907,0.040948
2,futhark,run_equilibrium,default,C,5,2,1,25,0.071775,0.000074
3,futhark,run_equilibrium,default,M,5,2,1,25,0.070213,0.000340
4,futhark,run_equilibrium,default,U,5,2,1,25,0.166022,0.108779
5,futhark,run_equilibrium,futhark01,C,10,2,1,25,0.090386,0.000233
6,futhark,run_equilibrium,futhark01,C,3,2,1,25,0.078432,0.000819
7,futhark,run_equilibrium,futhark01,M,10,2,1,25,0.075278,0.004125
8,futhark,run_equilibrium,futhark01,M,3,2,1,25,0.071403,0.005256
9,futhark,run_equilibrium,futhark01,U,10,2,1,25,0.685231,0.149442
10,futhark,run_equilibrium,futhark01,U,3,2,1,25,0.307815,0.225473
11,futhark,run_equilibrium,local,C,3,2,1,25,0.015431,0.000122
12,futhark,run_equilibrium,local,M,3,2,1,25,0.047325,0.014614
13,futhark,run_equilibrium,modular,C,3,2,1,25,0.015932,0.000451
14,futhark,run_equilibrium,modular,M,3,2,1,25,0.090969,0.041528
15,futhark,run_equilibrium,modular_old_check,C,3,2,1,25,0.015084,0.000119
16,futhark,run_equilibrium,modular_old_check,M,3,2,1,25,0.104048,0.027593
17,futhark,run_equilibrium_dp_solve,local,C,3,2,1,25,0.052432,0.000838
18,futhark,run_equilibrium_dp_solve,local,M,3,2,1,25,0.062828,0.007458
19,futhark,run_equilibrium_full_ad,futhark01,C,10,2,1,25,0.120320,0.004746
20,futhark,run_equilibrium_full_ad,futhark01,C,3,2,1,25,0.122620,0.000207
21,futhark,run_equilibrium_full_ad,futhark01,M,10,2,1,25,0.077486,0.007847
22,futhark,run_equilibrium_full_ad,futhark01,M,3,2,1,25,0.084181,0.004252
23,futhark,run_equilibrium_full_ad,futhark01,U,10,2,1,25,0.245517,0.072150
24,futhark,run_equilibrium_full_ad,futhark01,U,3,2,1,25,0.436115,0.110851
25,futhark,run_equilibrium_full_ad,local,C,3,2,1,25,0.023094,0.000215
26,futhark,run_equilibrium_full_ad,local,M,3,2,1,25,0.046272,0.005105
27,futhark,run_equilibrium_man,futhark01,C,3,2,1,25,0.024319,0.000030
28,futhark,run_equilibrium_man,futhark01,M,3,2,1,25,0.058998,0.000799
29,futhark,run_equilibrium_man,futhark01,U,3,2,1,25,0.292506,0.000426
30,futhark,run_equilibrium_man,local,C,3,2,1,25,0.006132,0.000041
31,futhark,run_equilibrium_man,local,M,3,2,1,25,0.104294,0.029356
32,futhark,run_equilibrium_man,modular_man,C,3,2,1,25,0.009365,0.000118
33,futhark,run_equilibrium_man,modular_man,M,3,2,1,25,0.054045,0.013556
34,futhark,run_equilibrium_man_old,old_comparison_to_modular,C,3,2,1,25,0.009888,0.000161
35,futhark,run_equilibrium_man_old,old_comparison_to_modular,M,3,2,1,25,0.032744,0.001276
36,futhark,run_equilibrium_man_sa,local,C,3,2,1,25,0.011003,0.000173
37,futhark,run_equilibrium_man_sa,local,M,3,2,1,25,0.072842,0.021598
38,futhark,run_equilibrium_old,futhark01,C,10,2,1,25,0.069339,0.000711
39,futhark,run_equilibrium_old,futhark01,C,3,2,1,25,0.069082,0.000131
40,futhark,run_equilibrium_old,futhark01,M,10,2,1,25,0.069923,0.002700
41,futhark,run_equilibrium_old,futhark01,M,3,2,1,25,0.076641,0.002689
42,futhark,run_equilibrium_old,futhark01,U,10,2,1,25,0.183705,0.146324
43,futhark,run_equilibrium_old,futhark01,U,3,2,1,25,0.162064,0.182462
44,futhark,run_equilibrium_old,old_to_modular_compar,C,3,2,1,25,0.017218,0.000840
45,futhark,run_equilibrium_old,old_to_modular_compar,M,3,2,1,25,0.050214,0.008887
46,futhark,run_equilibrium_sa,local,C,3,2,1,25,0.054083,0.000404
47,futhark,run_equilibrium_sa,local,M,3,2,1,25,0.090929,0.008409
48,matlab,-,-,-,-,2,1,25,0.068386,0.020576
49,futhark,run_equilibrium,3_local_new,C,3,2,3,25,0.475384,0.034759
50,futhark,run_equilibrium,3_local_new,M,3,2,3,25,0.312984,0.011410
51,futhark,run_equilibrium,default,C,5,2,3,25,1.017586,0.008958
52,futhark,run_equilibrium,default,M,5,2,3,25,0.551311,0.086892
53,futhark,run_equilibrium,default,U,5,2,3,25,2.053470,0.254596
54,futhark,run_equilibrium,futhark01,C,10,2,3,25,1.283019,0.007699
55,futhark,run_equilibrium,futhark01,C,3,2,3,25,1.116019,0.049974
56,futhark,run_equilibrium,futhark01,M,10,2,3,25,0.404357,0.068408
57,futhark,run_equilibrium,futhark01,M,3,2,3,25,0.414538,0.031824
58,futhark,run_equilibrium,futhark01,U,10,2,3,25,2.028443,0.137212
59,futhark,run_equilibrium,futhark01,U,3,2,3,25,2.046693,0.219478
60,futhark,run_equilibrium,local,C,3,2,3,25,0.330239,0.000843
61,futhark,run_equilibrium,local,M,3,2,3,25,0.132433,0.008728
62,futhark,run_equilibrium,modular,C,3,2,3,25,0.403629,0.010532
63,futhark,run_equilibrium,modular,M,3,2,3,25,0.197468,0.050664
64,futhark,run_equilibrium,modular_old_check,C,3,2,3,25,0.391951,0.003360
65,futhark,run_equilibrium,modular_old_check,M,3,2,3,25,0.220105,0.016488
66,futhark,run_equilibrium_dp_solve,local,C,3,2,3,25,1.147393,0.080839
67,futhark,run_equilibrium_dp_solve,local,M,3,2,3,25,0.247876,0.004025
68,futhark,run_equilibrium_full_ad,futhark01,C,10,2,3,25,1.841278,0.003180
69,futhark,run_equilibrium_full_ad,futhark01,C,3,2,3,25,1.836515,0.002886
70,futhark,run_equilibrium_full_ad,futhark01,M,10,2,3,25,0.556332,0.158113
71,futhark,run_equilibrium_full_ad,futhark01,M,3,2,3,25,0.592459,0.122329
72,futhark,run_equilibrium_full_ad,futhark01,U,10,2,3,25,2.037763,0.132801
73,futhark,run_equilibrium_full_ad,futhark01,U,3,2,3,25,2.381286,0.085221
74,futhark,run_equilibrium_full_ad,local,C,3,2,3,25,0.578233,0.010144
75,futhark,run_equilibrium_full_ad,local,M,3,2,3,25,0.208651,0.007096
76,futhark,run_equilibrium_man,futhark01,C,3,2,3,25,0.172422,0.001714
77,futhark,run_equilibrium_man,futhark01,M,3,2,3,25,0.229042,0.009415
78,futhark,run_equilibrium_man,futhark01,U,3,2,3,25,1.473302,0.273700
79,futhark,run_equilibrium_man,local,C,3,2,3,25,0.075425,0.001057
80,futhark,run_equilibrium_man,local,M,3,2,3,25,0.129162,0.022089
81,futhark,run_equilibrium_man,modular_man,C,3,2,3,25,0.208750,0.002472
82,futhark,run_equilibrium_man,modular_man,M,3,2,3,25,0.278289,0.003848
83,futhark,run_equilibrium_man_old,old_comparison_to_modular,C,3,2,3,25,0.231433,0.001805
84,futhark,run_equilibrium_man_old,old_comparison_to_modular,M,3,2,3,25,0.150163,0.012824
85,futhark,run_equilibrium_man_sa,local,C,3,2,3,25,0.206229,0.003648
86,futhark,run_equilibrium_man_sa,local,M,3,2,3,25,0.323326,0.014678
87,futhark,run_equilibrium_old,futhark01,C,10,2,3,25,1.102364,0.206372
88,futhark,run_equilibrium_old,futhark01,C,3,2,3,25,1.023386,0.076273
89,futhark,run_equilibrium_old,futhark01,M,10,2,3,25,0.479450,0.087350
90,futhark,run_equilibrium_old,futhark01,M,3,2,3,25,0.578395,0.062793
91,futhark,run_equilibrium_old,futhark01,U,10,2,3,25,0.995413,0.252240
92,futhark,run_equilibrium_old,futhark01,U,3,2,3,25,1.234537,0.211841
93,futhark,run_equilibrium_old,old_to_modular_compar,C,3,2,3,25,0.427386,0.014817
94,futhark,run_equilibrium_old,old_to_modular_compar,M,3,2,3,25,0.185207,0.007508
95,futhark,run_equilibrium_sa,local,C,3,2,3,25,0.711337,0.009792
96,futhark,run_equilibrium_sa,local,M,3,2,3,25,0.677616,0.007987
97,matlab,-,-,-,-,2,3,25,0.485418,0.086544
98,futhark,run_equilibrium,3_local_new,C,3,2,5,25,1.850037,0.035498
99,futhark,run_equilibrium,3_local_new,M,3,2,5,25,0.541437,0.045276
100,futhark,run_equilibrium,default,C,5,2,5,25,4.257113,0.003268
101,futhark,run_equilibrium,default,M,5,2,5,25,1.033376,0.106401
102,futhark,run_equilibrium,default,U,5,2,5,25,4.202699,0.274972
103,futhark,run_equilibrium,futhark01,C,10,2,5,25,5.591503,0.314062
104,futhark,run_equilibrium,futhark01,C,3,2,5,25,4.331232,0.001341
105,futhark,run_equilibrium,futhark01,M,10,2,5,25,1.322939,0.198553
106,futhark,run_equilibrium,futhark01,M,3,2,5,25,0.728182,0.134236
107,futhark,run_equilibrium,futhark01,U,10,2,5,25,2.356479,1.093894
108,futhark,run_equilibrium,futhark01,U,3,2,5,25,2.552350,0.029912
109,futhark,run_equilibrium,local,C,3,2,5,25,1.270393,0.037300
110,futhark,run_equilibrium,local,M,3,2,5,25,0.308382,0.009547
111,futhark,run_equilibrium,modular,C,3,2,5,25,1.758420,0.038239
112,futhark,run_equilibrium,modular,M,3,2,5,25,0.585584,0.072816
113,futhark,run_equilibrium,modular_old_check,C,3,2,5,25,1.750879,0.038082
114,futhark,run_equilibrium,modular_old_check,M,3,2,5,25,0.579057,0.039478
115,futhark,run_equilibrium_dp_solve,local,C,3,2,5,25,4.688311,0.437496
116,futhark,run_equilibrium_dp_solve,local,M,3,2,5,25,0.753486,0.024100
117,futhark,run_equilibrium_full_ad,futhark01,C,10,2,5,25,7.738920,0.386584
118,futhark,run_equilibrium_full_ad,futhark01,C,3,2,5,25,8.153395,0.288947
119,futhark,run_equilibrium_full_ad,futhark01,M,10,2,5,25,1.365808,0.164671
120,futhark,run_equilibrium_full_ad,futhark01,M,3,2,5,25,1.345074,0.026853
121,futhark,run_equilibrium_full_ad,futhark01,U,10,2,5,25,2.910516,0.444213
122,futhark,run_equilibrium_full_ad,futhark01,U,3,2,5,25,3.054048,0.179781
123,futhark,run_equilibrium_full_ad,local,C,3,2,5,25,2.271425,0.017468
124,futhark,run_equilibrium_full_ad,local,M,3,2,5,25,0.654648,0.011433
125,futhark,run_equilibrium_man,futhark01,C,3,2,5,25,0.781393,0.191018
126,futhark,run_equilibrium_man,futhark01,M,3,2,5,25,0.403040,0.016153
127,futhark,run_equilibrium_man,futhark01,U,3,2,5,25,2.378817,0.514461
128,futhark,run_equilibrium_man,local,C,3,2,5,25,0.327413,0.007961
129,futhark,run_equilibrium_man,local,M,3,2,5,25,0.390180,0.076427
130,futhark,run_equilibrium_man,modular_man,C,3,2,5,25,0.979866,0.008359
131,futhark,run_equilibrium_man,modular_man,M,3,2,5,25,0.629658,0.060387
132,futhark,run_equilibrium_man_old,old_comparison_to_modular,C,3,2,5,25,1.089663,0.030121
133,futhark,run_equilibrium_man_old,old_comparison_to_modular,M,3,2,5,25,0.428335,0.039023
134,futhark,run_equilibrium_man_sa,local,C,3,2,5,25,1.587456,0.314871
135,futhark,run_equilibrium_man_sa,local,M,3,2,5,25,0.932053,0.164469
136,futhark,run_equilibrium_old,futhark01,C,10,2,5,25,4.182230,0.022182
137,futhark,run_equilibrium_old,futhark01,C,3,2,5,25,4.180182,0.003744
138,futhark,run_equilibrium_old,futhark01,M,10,2,5,25,1.044797,0.063542
139,futhark,run_equilibrium_old,futhark01,M,3,2,5,25,1.224175,0.146433
140,futhark,run_equilibrium_old,futhark01,U,10,2,5,25,4.250552,0.788360
141,futhark,run_equilibrium_old,futhark01,U,3,2,5,25,4.485262,0.205442
142,futhark,run_equilibrium_old,old_to_modular_compar,C,3,2,5,25,1.784986,0.048064
143,futhark,run_equilibrium_old,old_to_modular_compar,M,3,2,5,25,0.644558,0.120877
144,futhark,run_equilibrium_sa,local,C,3,2,5,25,2.239884,0.012615
145,futhark,run_equilibrium_sa,local,M,3,2,5,25,1.198351,0.053520
146,matlab,-,-,-,-,2,5,25,1.939685,0.108326
147,futhark,run_equilibrium,3_local_new,C,3,2,7,25,4.888184,0.050468
148,futhark,run_equilibrium,3_local_new,M,3,2,7,25,1.433253,0.017356
149,futhark,run_equilibrium,default,C,5,2,7,25,12.250263,0.005363
150,futhark,run_equilibrium,default,M,5,2,7,25,3.655607,0.188642
151,futhark,run_equilibrium,default,U,5,2,7,25,7.278269,0.020169
152,futhark,run_equilibrium,futhark01,C,10,2,7,25,15.737736,0.359184
153,futhark,run_equilibrium,futhark01,C,3,2,7,25,12.046656,0.480690
154,futhark,run_equilibrium,futhark01,M,10,2,7,25,2.885689,0.112988
155,futhark,run_equilibrium,futhark01,M,3,2,7,25,1.865896,0.447884
156,futhark,run_equilibrium,futhark01,U,10,2,7,25,4.633079,0.336224
157,futhark,run_equilibrium,futhark01,U,3,2,7,25,1.564589,0.122438
158,futhark,run_equilibrium,local,C,3,2,7,25,3.311001,0.021470
159,futhark,run_equilibrium,local,M,3,2,7,25,0.987857,0.025682
160,futhark,run_equilibrium,modular,C,3,2,7,25,5.035721,0.064800
161,futhark,run_equilibrium,modular,M,3,2,7,25,1.566795,0.026148
162,futhark,run_equilibrium,modular_old_check,C,3,2,7,25,4.963598,0.019989
163,futhark,run_equilibrium,modular_old_check,M,3,2,7,25,1.505925,0.025950
164,futhark,run_equilibrium_dp_solve,local,C,3,2,7,25,12.550822,0.391622
165,futhark,run_equilibrium_dp_solve,local,M,3,2,7,25,2.488624,0.013574
166,futhark,run_equilibrium_full_ad,futhark01,C,10,2,7,25,21.766562,0.497587
167,futhark,run_equilibrium_full_ad,futhark01,C,3,2,7,25,21.325202,0.030232
168,futhark,run_equilibrium_full_ad,futhark01,M,10,2,7,25,3.520068,0.237845
169,futhark,run_equilibrium_full_ad,futhark01,M,3,2,7,25,3.754563,0.209821
170,futhark,run_equilibrium_full_ad,futhark01,U,10,2,7,25,3.375598,1.505001
171,futhark,run_equilibrium_full_ad,futhark01,U,3,2,7,25,2.800394,1.557309
172,futhark,run_equilibrium_full_ad,local,C,3,2,7,25,6.365089,0.054998
173,futhark,run_equilibrium_full_ad,local,M,3,2,7,25,1.655991,0.075962
174,futhark,run_equilibrium_man,futhark01,C,3,2,7,25,1.795280,0.011455
175,futhark,run_equilibrium_man,futhark01,M,3,2,7,25,0.841779,0.072686
176,futhark,run_equilibrium_man,futhark01,U,3,2,7,25,2.096495,0.002889
177,futhark,run_equilibrium_man,local,C,3,2,7,25,0.933994,0.055560
178,futhark,run_equilibrium_man,local,M,3,2,7,25,0.531839,0.020373
179,futhark,run_equilibrium_man,modular_man,C,3,2,7,25,3.010738,0.024948
180,futhark,run_equilibrium_man,modular_man,M,3,2,7,25,1.295703,0.065784
181,futhark,run_equilibrium_man_old,old_comparison_to_modular,C,3,2,7,25,3.190131,0.007116
182,futhark,run_equilibrium_man_old,old_comparison_to_modular,M,3,2,7,25,1.188762,0.028971
183,futhark,run_equilibrium_man_sa,local,C,3,2,7,25,2.570010,0.028464
184,futhark,run_equilibrium_man_sa,local,M,3,2,7,25,1.710577,0.090149
185,futhark,run_equilibrium_old,futhark01,C,10,2,7,25,12.688732,0.434390
186,futhark,run_equilibrium_old,futhark01,C,3,2,7,25,12.252672,0.019253
187,futhark,run_equilibrium_old,futhark01,M,10,2,7,25,3.047151,0.130918
188,futhark,run_equilibrium_old,futhark01,M,3,2,7,25,3.431730,0.050951
189,futhark,run_equilibrium_old,futhark01,U,10,2,7,25,5.282530,2.315052
190,futhark,run_equilibrium_old,futhark01,U,3,2,7,25,7.383289,0.039402
191,futhark,run_equilibrium_old,old_to_modular_compar,C,3,2,7,25,5.306671,0.128096
192,futhark,run_equilibrium_old,old_to_modular_compar,M,3,2,7,25,1.811203,0.146547
193,futhark,run_equilibrium_sa,local,C,3,2,7,25,5.549505,0.045592
194,futhark,run_equilibrium_sa,local,M,3,2,7,25,2.308907,0.090265
195,matlab,-,-,-,-,2,7,25,7.587036,0.504120
196,futhark,run_equilibrium,3_local_new,C,3,2,9,25,9.078937,0.032125
197,futhark,run_equilibrium,3_local_new,M,3,2,9,25,2.556184,0.050917
198,futhark,run_equilibrium,default,C,5,2,9,25,25.576270,0.343433
199,futhark,run_equilibrium,default,M,5,2,9,25,7.829356,0.128147
200,futhark,run_equilibrium,default,U,5,2,9,25,7.589911,0.055897
201,futhark,run_equilibrium,futhark01,C,10,2,9,25,31.830842,0.379129
202,futhark,run_equilibrium,futhark01,C,3,2,9,25,27.097665,2.618424
203,futhark,run_equilibrium,futhark01,M,10,2,9,25,3.081936,0.170358
204,futhark,run_equilibrium,futhark01,M,3,2,9,25,2.568704,0.405934
205,futhark,run_equilibrium,futhark01,U,10,2,9,25,3.143918,1.592406
206,futhark,run_equilibrium,futhark01,U,3,2,9,25,5.107506,0.184299
207,futhark,run_equilibrium,local,C,3,2,9,25,5.712635,0.093886
208,futhark,run_equilibrium,local,M,3,2,9,25,1.842999,0.079794
209,futhark,run_equilibrium,modular,C,3,2,9,25,10.899231,0.408447
210,futhark,run_equilibrium,modular,M,3,2,9,25,3.419177,0.097338
211,futhark,run_equilibrium,modular_old_check,C,3,2,9,25,10.725853,0.142108
212,futhark,run_equilibrium,modular_old_check,M,3,2,9,25,3.273535,0.047768
213,futhark,run_equilibrium_dp_solve,local,C,3,2,9,25,24.469288,5.218870
214,futhark,run_equilibrium_dp_solve,local,M,3,2,9,25,6.623470,0.302143
215,futhark,run_equilibrium_full_ad,futhark01,C,10,2,9,25,42.362885,0.626068
216,futhark,run_equilibrium_full_ad,futhark01,C,3,2,9,25,42.658149,0.792616
217,futhark,run_equilibrium_full_ad,futhark01,M,10,2,9,25,2.973877,0.200246
218,futhark,run_equilibrium_full_ad,futhark01,M,3,2,9,25,9.260177,0.698013
219,futhark,run_equilibrium_full_ad,futhark01,U,10,2,9,25,5.671852,0.246345
220,futhark,run_equilibrium_full_ad,futhark01,U,3,2,9,25,5.735271,0.245731
221,futhark,run_equilibrium_full_ad,local,C,3,2,9,25,11.900662,0.166331
222,futhark,run_equilibrium_full_ad,local,M,3,2,9,25,3.025952,0.050044
223,futhark,run_equilibrium_man,futhark01,C,3,2,9,25,3.224055,0.008248
224,futhark,run_equilibrium_man,futhark01,M,3,2,9,25,1.272435,0.010355
225,futhark,run_equilibrium_man,futhark01,U,3,2,9,25,4.836228,0.023913
226,futhark,run_equilibrium_man,local,C,3,2,9,25,1.577144,0.113523
227,futhark,run_equilibrium_man,local,M,3,2,9,25,1.107416,0.007687
228,futhark,run_equilibrium_man,modular_man,C,3,2,9,25,7.027972,0.031786
229,futhark,run_equilibrium_man,modular_man,M,3,2,9,25,2.589957,0.083869
230,futhark,run_equilibrium_man_old,old_comparison_to_modular,C,3,2,9,25,7.321969,0.026063
231,futhark,run_equilibrium_man_old,old_comparison_to_modular,M,3,2,9,25,2.369500,0.101582
232,futhark,run_equilibrium_man_sa,local,C,3,2,9,25,5.717989,0.216998
233,futhark,run_equilibrium_man_sa,local,M,3,2,9,25,3.478516,0.035564
234,futhark,run_equilibrium_old,futhark01,C,10,2,9,25,26.186639,0.402781
235,futhark,run_equilibrium_old,futhark01,C,3,2,9,25,26.694389,0.368411
236,futhark,run_equilibrium_old,futhark01,M,10,2,9,25,7.448414,0.328802
237,futhark,run_equilibrium_old,futhark01,M,3,2,9,25,7.916476,0.366133
238,futhark,run_equilibrium_old,futhark01,U,10,2,9,25,5.549307,1.786611
239,futhark,run_equilibrium_old,futhark01,U,3,2,9,25,7.438766,0.047640
240,futhark,run_equilibrium_old,old_to_modular_compar,C,3,2,9,25,10.994445,0.367718
241,futhark,run_equilibrium_old,old_to_modular_compar,M,3,2,9,25,3.260171,0.244966
242,futhark,run_equilibrium_sa,local,C,3,2,9,25,9.616729,0.238460
243,futhark,run_equilibrium_sa,local,M,3,2,9,25,3.705886,0.017246
244,matlab,-,-,-,-,2,9,25,11.064450,0.675593
245,futhark,run_equilibrium,3_local_new,C,3,2,11,25,12.643610,0.354818
246,futhark,run_equilibrium,3_local_new,M,3,2,11,25,4.584247,0.090691
247,futhark,run_equilibrium,default,C,5,2,11,25,49.814709,1.412716
248,futhark,run_equilibrium,default,M,5,2,11,25,15.578127,0.194999
249,futhark,run_equilibrium,default,U,5,2,11,25,9.301355,0.300547
250,futhark,run_equilibrium,futhark01,C,10,2,11,25,61.991585,0.917316
251,futhark,run_equilibrium,futhark01,C,3,2,11,25,40.693528,1.630994
252,futhark,run_equilibrium,futhark01,M,10,2,11,25,5.305154,0.303164
253,futhark,run_equilibrium,futhark01,M,3,2,11,25,3.429527,0.270896
254,futhark,run_equilibrium,futhark01,U,10,2,11,25,7.754164,2.908148
255,futhark,run_equilibrium,futhark01,U,3,2,11,25,9.996767,0.693131
256,futhark,run_equilibrium,local,C,3,2,11,25,10.658316,0.191747
257,futhark,run_equilibrium,local,M,3,2,11,25,3.224413,0.022561
258,futhark,run_equilibrium,modular,C,3,2,11,25,20.764445,0.085205
259,futhark,run_equilibrium,modular,M,3,2,11,25,6.721849,0.365686
260,futhark,run_equilibrium,modular_old_check,C,3,2,11,25,20.892889,0.071651
261,futhark,run_equilibrium,modular_old_check,M,3,2,11,25,6.478809,0.170547
262,futhark,run_equilibrium_dp_solve,local,C,3,2,11,25,35.551694,0.635903
263,futhark,run_equilibrium_dp_solve,local,M,3,2,11,25,10.996520,0.046194
264,futhark,run_equilibrium_full_ad,futhark01,C,10,2,11,25,81.202996,0.775515
265,futhark,run_equilibrium_full_ad,futhark01,C,3,2,11,25,81.752951,1.250106
266,futhark,run_equilibrium_full_ad,futhark01,M,10,2,11,25,5.679015,0.268565
267,futhark,run_equilibrium_full_ad,futhark01,M,3,2,11,25,5.652762,0.329036
268,futhark,run_equilibrium_full_ad,futhark01,U,10,2,11,25,10.215038,0.203476
269,futhark,run_equilibrium_full_ad,futhark01,U,3,2,11,25,9.947965,0.106273
270,futhark,run_equilibrium_full_ad,local,C,3,2,11,25,22.148689,0.679425
271,futhark,run_equilibrium_full_ad,local,M,3,2,11,25,6.553496,0.832057
272,futhark,run_equilibrium_man,futhark01,C,3,2,11,25,6.050837,0.022267
273,futhark,run_equilibrium_man,futhark01,M,3,2,11,25,1.429798,0.033974
274,futhark,run_equilibrium_man,futhark01,U,3,2,11,25,3.851100,0.005857
275,futhark,run_equilibrium_man,local,C,3,2,11,25,2.562726,0.011287
276,futhark,run_equilibrium_man,local,M,3,2,11,25,1.727970,0.024323
277,futhark,run_equilibrium_man,modular_man,C,3,2,11,25,14.554773,0.538918
278,futhark,run_equilibrium_man,modular_man,M,3,2,11,25,5.398334,0.352527
279,futhark,run_equilibrium_man_old,old_comparison_to_modular,C,3,2,11,25,14.536650,0.145376
280,futhark,run_equilibrium_man_old,old_comparison_to_modular,M,3,2,11,25,4.720555,0.299336
281,futhark,run_equilibrium_man_sa,local,C,3,2,11,25,9.392760,0.060082

=== households: bench times ===

,source,run_equi,val_name,backend,runs,n,c,abar,mean,stdev
0,futhark,run_equilibrium,futhark01,C,3,2,7,25,12.046656,0.480690
1,futhark,run_equilibrium,futhark01,M,3,2,7,25,1.865896,0.447884
2,futhark,run_equilibrium,futhark01,U,3,2,7,25,1.564589,0.122438
3,futhark,run_equilibrium,local,C,3,2,7,25,3.311001,0.021470
4,futhark,run_equilibrium,local,M,3,2,7,25,0.987857,0.025682
5,futhark,run_equilibrium_dp_solve,local,C,3,2,7,25,12.550822,0.391622
6,futhark,run_equilibrium_dp_solve,local,M,3,2,7,25,2.488624,0.013574
7,futhark,run_equilibrium_full_ad,local,C,3,2,7,25,6.365089,0.054998
8,futhark,run_equilibrium_full_ad,local,M,3,2,7,25,1.655991,0.075962
9,futhark,run_equilibrium_man,futhark01,C,3,2,7,25,1.795280,0.011455
10,futhark,run_equilibrium_man,futhark01,M,3,2,7,25,0.841779,0.072686
11,futhark,run_equilibrium_man,futhark01,U,3,2,7,25,2.096495,0.002889
12,futhark,run_equilibrium_man,local,C,3,2,7,25,0.933994,0.055560
13,futhark,run_equilibrium_man,local,M,3,2,7,25,0.531839,0.020373
14,futhark,run_equilibrium_man_sa,local,C,3,2,7,25,2.570010,0.028464
15,futhark,run_equilibrium_man_sa,local,M,3,2,7,25,1.710577,0.090149
16,futhark,run_equilibrium_sa,local,C,3,2,7,25,5.549505,0.045592
17,futhark,run_equilibrium_sa,local,M,3,2,7,25,2.308907,0.090265
18,matlab,-,-,-,-,2,7,25,7.020355,0.190719
19,futhark,run_equilibrium,futhark01,C,3,3,7,25,16.930826,0.233814
20,futhark,run_equilibrium,futhark01,M,3,3,7,25,1.706790,0.192713
21,futhark,run_equilibrium,futhark01,U,3,3,7,25,5.378094,0.612289
22,futhark,run_equilibrium,local,C,3,3,7,25,4.233363,0.126168
23,futhark,run_equilibrium,local,M,3,3,7,25,1.175821,0.058068
24,futhark,run_equilibrium_dp_solve,local,C,3,3,7,25,11.358460,0.202879
25,futhark,run_equilibrium_dp_solve,local,M,3,3,7,25,2.950833,0.074102
26,futhark,run_equilibrium_full_ad,local,C,3,3,7,25,8.087743,0.160870
27,futhark,run_equilibrium_full_ad,local,M,3,3,7,25,1.988444,0.037820
28,futhark,run_equilibrium_man,futhark01,C,3,3,7,25,2.232492,0.003181
29,futhark,run_equilibrium_man,futhark01,M,3,3,7,25,0.862164,0.097244
30,futhark,run_equilibrium_man,futhark01,U,3,3,7,25,2.556853,0.005319
31,futhark,run_equilibrium_man,local,C,3,3,7,25,0.988676,0.074994
32,futhark,run_equilibrium_man,local,M,3,3,7,25,0.694000,0.051981
33,futhark,run_equilibrium_man_sa,local,C,3,3,7,25,3.886974,0.044122
34,futhark,run_equilibrium_man_sa,local,M,3,3,7,25,1.982830,0.021060
35,futhark,run_equilibrium_sa,local,C,3,3,7,25,7.235738,0.103090
36,futhark,run_equilibrium_sa,local,M,3,3,7,25,2.393281,0.042779
37,matlab,-,-,-,-,3,7,25,6.707738,0.021294
38,futhark,run_equilibrium,futhark01,C,3,4,7,25,20.206750,0.015438
39,futhark,run_equilibrium,futhark01,M,3,4,7,25,2.238506,0.544939
40,futhark,run_equilibrium,futhark01,U,3,4,7,25,7.163911,0.464348
41,futhark,run_equilibrium,local,C,3,4,7,25,5.326726,0.074081
42,futhark,run_equilibrium,local,M,3,4,7,25,1.498123,0.075818
43,futhark,run_equilibrium_dp_solve,local,C,3,4,7,25,14.390799,0.149292
44,futhark,run_equilibrium_dp_solve,local,M,3,4,7,25,4.161456,0.356631
45,futhark,run_equilibrium_full_ad,local,C,3,4,7,25,10.399207,0.083651
46,futhark,run_equilibrium_full_ad,local,M,3,4,7,25,2.563128,0.074889
47,futhark,run_equilibrium_man,futhark01,C,3,4,7,25,2.943561,0.011682
48,futhark,run_equilibrium_man,futhark01,M,3,4,7,25,0.717836,0.004292
49,futhark,run_equilibrium_man,futhark01,U,3,4,7,25,3.464874,0.000815
50,futhark,run_equilibrium_man,local,C,3,4,7,25,1.313793,0.099950
51,futhark,run_equilibrium_man,local,M,3,4,7,25,0.673661,0.052144
52,futhark,run_equilibrium_man_sa,local,C,3,4,7,25,5.027206,0.033769
53,futhark,run_equilibrium_man_sa,local,M,3,4,7,25,2.543376,0.074151
54,futhark,run_equilibrium_sa,local,C,3,4,7,25,9.349486,0.121576
55,futhark,run_equilibrium_sa,local,M,3,4,7,25,2.864798,0.068108
56,matlab,-,-,-,-,4,7,25,8.168758,0.021005
57,futhark,run_equilibrium,futhark01,C,3,5,7,25,22.470982,1.628230
58,futhark,run_equilibrium,futhark01,M,3,5,7,25,1.913726,0.220077
59,futhark,run_equilibrium,futhark01,U,3,5,7,25,2.740423,0.011989
60,futhark,run_equilibrium,local,C,3,5,7,25,6.525457,0.033199
61,futhark,run_equilibrium,local,M,3,5,7,25,1.755546,0.090920
62,futhark,run_equilibrium_dp_solve,local,C,3,5,7,25,18.107780,0.427154
63,futhark,run_equilibrium_dp_solve,local,M,3,5,7,25,5.736880,0.723407
64,futhark,run_equilibrium_full_ad,local,C,3,5,7,25,10.852802,0.064481
65,futhark,run_equilibrium_full_ad,local,M,3,5,7,25,2.749445,0.110550
66,futhark,run_equilibrium_man,futhark01,C,3,5,7,25,3.672142,0.007097
67,futhark,run_equilibrium_man,futhark01,M,3,5,7,25,0.847127,0.029048
68,futhark,run_equilibrium_man,futhark01,U,3,5,7,25,4.311975,0.010347
69,futhark,run_equilibrium_man,local,C,3,5,7,25,1.624572,0.064578
70,futhark,run_equilibrium_man,local,M,3,5,7,25,0.857089,0.038700
71,futhark,run_equilibrium_man_sa,local,C,3,5,7,25,6.227490,0.039900
72,futhark,run_equilibrium_man_sa,local,M,3,5,7,25,3.012447,0.046810
73,futhark,run_equilibrium_sa,local,C,3,5,7,25,9.632379,0.091005
74,futhark,run_equilibrium_sa,local,M,3,5,7,25,2.734658,0.062907
75,matlab,-,-,-,-,5,7,25,11.204162,0.043375
76,futhark,run_equilibrium,futhark01,C,3,6,7,25,27.291792,0.376319
77,futhark,run_equilibrium,futhark01,M,3,6,7,25,2.462285,0.247952
78,futhark,run_equilibrium,futhark01,U,3,6,7,25,9.013468,0.497106
79,futhark,run_equilibrium,local,C,3,6,7,25,7.827898,0.052284
80,futhark,run_equilibrium,local,M,3,6,7,25,2.442221,0.205999
81,futhark,run_equilibrium_dp_solve,local,C,3,6,7,25,22.179636,0.422082
82,futhark,run_equilibrium_dp_solve,local,M,3,6,7,25,6.129757,0.304857
83,futhark,run_equilibrium_full_ad,local,C,3,6,7,25,12.809102,0.043380
84,futhark,run_equilibrium_full_ad,local,M,3,6,7,25,3.243979,0.093879
85,futhark,run_equilibrium_man,futhark01,C,3,6,7,25,4.391486,0.006983
86,futhark,run_equilibrium_man,futhark01,M,3,6,7,25,0.910151,0.000876
87,futhark,run_equilibrium_man,futhark01,U,3,6,7,25,5.100635,0.002942
88,futhark,run_equilibrium_man,local,C,3,6,7,25,1.950545,0.026046
89,futhark,run_equilibrium_man,local,M,3,6,7,25,0.956494,0.039250
90,futhark,run_equilibrium_man_sa,local,C,3,6,7,25,7.456149,0.108145
91,futhark,run_equilibrium_man_sa,local,M,3,6,7,25,3.514833,0.214544
92,futhark,run_equilibrium_sa,local,C,3,6,7,25,11.409954,0.052591
93,futhark,run_equilibrium_sa,local,M,3,6,7,25,3.179089,0.107446
94,matlab,-,-,-,-,6,7,25,11.174867,0.044354

=== age: bench times ===

,source,run_equi,val_name,backend,runs,n,c,abar,mean,stdev
0,futhark,run_equilibrium,futhark01,C,3,2,7,10,0.779003,0.011113
1,futhark,run_equilibrium,futhark01,M,3,2,7,10,0.334705,0.021526
2,futhark,run_equilibrium,futhark01,U,3,2,7,10,3.861802,0.177398
3,futhark,run_equilibrium,local,C,3,2,7,10,0.275749,0.007175
4,futhark,run_equilibrium,local,M,3,2,7,10,0.105716,0.014869
5,futhark,run_equilibrium_dp_solve,local,C,3,2,7,10,0.657117,0.082414
6,futhark,run_equilibrium_dp_solve,local,M,3,2,7,10,0.197550,0.008847
7,futhark,run_equilibrium_full_ad,local,C,3,2,7,10,0.454884,0.012506
8,futhark,run_equilibrium_full_ad,local,M,3,2,7,10,0.139663,0.008736
9,futhark,run_equilibrium_man,futhark01,C,3,2,7,10,0.293442,0.023431
10,futhark,run_equilibrium_man,futhark01,M,3,2,7,10,0.181726,0.014864
11,futhark,run_equilibrium_man,futhark01,U,3,2,7,10,2.795656,0.014342
12,futhark,run_equilibrium_man,local,C,3,2,7,10,0.116780,0.004510
13,futhark,run_equilibrium_man,local,M,3,2,7,10,0.116753,0.026969
14,futhark,run_equilibrium_man_sa,local,C,3,2,7,10,0.251157,0.001595
15,futhark,run_equilibrium_man_sa,local,M,3,2,7,10,0.238014,0.003487
16,futhark,run_equilibrium_sa,local,C,3,2,7,10,0.608436,0.009203
17,futhark,run_equilibrium_sa,local,M,3,2,7,10,0.413464,0.005219
18,matlab,-,-,-,-,2,7,10,0.681014,0.037932
19,futhark,run_equilibrium,futhark01,C,3,2,7,15,2.200150,0.006156
20,futhark,run_equilibrium,futhark01,M,3,2,7,15,0.536865,0.105349
21,futhark,run_equilibrium,futhark01,U,3,2,7,15,1.682183,0.302057
22,futhark,run_equilibrium,local,C,3,2,7,15,0.668816,0.003574
23,futhark,run_equilibrium,local,M,3,2,7,15,0.327886,0.078854
24,futhark,run_equilibrium_dp_solve,local,C,3,2,7,15,1.774488,0.025030
25,futhark,run_equilibrium_dp_solve,local,M,3,2,7,15,0.470580,0.037068
26,futhark,run_equilibrium_full_ad,local,C,3,2,7,15,1.275728,0.023070
27,futhark,run_equilibrium_full_ad,local,M,3,2,7,15,0.338097,0.032860
28,futhark,run_equilibrium_man,futhark01,C,3,2,7,15,0.407447,0.001605
29,futhark,run_equilibrium_man,futhark01,M,3,2,7,15,0.291829,0.009642
30,futhark,run_equilibrium_man,futhark01,U,3,2,7,15,2.022720,0.002816
31,futhark,run_equilibrium_man,local,C,3,2,7,15,0.174147,0.003204
32,futhark,run_equilibrium_man,local,M,3,2,7,15,0.133550,0.018706
33,futhark,run_equilibrium_man_sa,local,C,3,2,7,15,0.626432,0.013893
34,futhark,run_equilibrium_man_sa,local,M,3,2,7,15,0.455670,0.042594
35,futhark,run_equilibrium_sa,local,C,3,2,7,15,1.384797,0.024339
36,futhark,run_equilibrium_sa,local,M,3,2,7,15,0.726867,0.010860
37,matlab,-,-,-,-,2,7,15,1.110800,0.038380
38,futhark,run_equilibrium,futhark01,C,3,2,7,20,5.115561,0.012335
39,futhark,run_equilibrium,futhark01,M,3,2,7,20,1.108679,0.124866
40,futhark,run_equilibrium,futhark01,U,3,2,7,20,3.332474,0.360947
41,futhark,run_equilibrium,local,C,3,2,7,20,1.439351,0.025735
42,futhark,run_equilibrium,local,M,3,2,7,20,0.397220,0.011858
43,futhark,run_equilibrium_dp_solve,local,C,3,2,7,20,3.882984,0.196958
44,futhark,run_equilibrium_dp_solve,local,M,3,2,7,20,0.972112,0.029731
45,futhark,run_equilibrium_full_ad,local,C,3,2,7,20,2.782754,0.043377
46,futhark,run_equilibrium_full_ad,local,M,3,2,7,20,0.726752,0.031917
47,futhark,run_equilibrium_man,futhark01,C,3,2,7,20,0.902509,0.149965
48,futhark,run_equilibrium_man,futhark01,M,3,2,7,20,0.443127,0.020106
49,futhark,run_equilibrium_man,futhark01,U,3,2,7,20,1.758688,0.002681
50,futhark,run_equilibrium_man,local,C,3,2,7,20,0.325053,0.002397
51,futhark,run_equilibrium_man,local,M,3,2,7,20,0.253099,0.032758
52,futhark,run_equilibrium_man_sa,local,C,3,2,7,20,1.337858,0.012970
53,futhark,run_equilibrium_man_sa,local,M,3,2,7,20,0.860924,0.025860
54,futhark,run_equilibrium_sa,local,C,3,2,7,20,2.763137,0.092160
55,futhark,run_equilibrium_sa,local,M,3,2,7,20,1.257648,0.021744
56,matlab,-,-,-,-,2,7,20,2.574031,0.156272
57,futhark,run_equilibrium,futhark01,C,3,2,7,25,12.046656,0.480690
58,futhark,run_equilibrium,futhark01,M,3,2,7,25,1.865896,0.447884
59,futhark,run_equilibrium,futhark01,U,3,2,7,25,1.564589,0.122438
60,futhark,run_equilibrium,local,C,3,2,7,25,3.311001,0.021470
61,futhark,run_equilibrium,local,M,3,2,7,25,0.987857,0.025682
62,futhark,run_equilibrium_dp_solve,local,C,3,2,7,25,12.550822,0.391622
63,futhark,run_equilibrium_dp_solve,local,M,3,2,7,25,2.488624,0.013574
64,futhark,run_equilibrium_full_ad,local,C,3,2,7,25,6.365089,0.054998
65,futhark,run_equilibrium_full_ad,local,M,3,2,7,25,1.655991,0.075962
66,futhark,run_equilibrium_man,futhark01,C,3,2,7,25,1.795280,0.011455
67,futhark,run_equilibrium_man,futhark01,M,3,2,7,25,0.841779,0.072686
68,futhark,run_equilibrium_man,futhark01,U,3,2,7,25,2.096495,0.002889
69,futhark,run_equilibrium_man,local,C,3,2,7,25,0.933994,0.055560
70,futhark,run_equilibrium_man,local,M,3,2,7,25,0.531839,0.020373
71,futhark,run_equilibrium_man_sa,local,C,3,2,7,25,2.570010,0.028464
72,futhark,run_equilibrium_man_sa,local,M,3,2,7,25,1.710577,0.090149
73,futhark,run_equilibrium_sa,local,C,3,2,7,25,5.549505,0.045592
74,futhark,run_equilibrium_sa,local,M,3,2,7,25,2.308907,0.090265
75,matlab,-,-,-,-,2,7,25,7.087320,0.248254
76,futhark,run_equilibrium,futhark01,C,3,2,7,30,20.422618,0.346601
77,futhark,run_equilibrium,futhark01,M,3,2,7,30,2.853636,0.550127
78,futhark,run_equilibrium,futhark01,U,3,2,7,30,4.952743,0.226049
79,futhark,run_equilibrium,local,C,3,2,7,30,5.562934,0.027941
80,futhark,run_equilibrium,local,M,3,2,7,30,1.846307,0.113170
81,futhark,run_equilibrium_dp_solve,local,C,3,2,7,30,17.798060,0.404006
82,futhark,run_equilibrium_dp_solve,local,M,3,2,7,30,5.391332,0.115926
83,futhark,run_equilibrium_full_ad,local,C,3,2,7,30,10.660734,0.094350
84,futhark,run_equilibrium_full_ad,local,M,3,2,7,30,2.961272,0.046005
85,futhark,run_equilibrium_man,futhark01,C,3,2,7,30,2.994438,0.009806
86,futhark,run_equilibrium_man,futhark01,M,3,2,7,30,0.992306,0.043175
87,futhark,run_equilibrium_man,futhark01,U,3,2,7,30,2.781881,0.031443
88,futhark,run_equilibrium_man,local,C,3,2,7,30,1.176528,0.015979
89,futhark,run_equilibrium_man,local,M,3,2,7,30,0.979580,0.040078
90,futhark,run_equilibrium_man_sa,local,C,3,2,7,30,3.268530,0.034333
91,futhark,run_equilibrium_man_sa,local,M,3,2,7,30,2.225415,0.054881
92,futhark,run_equilibrium_sa,local,C,3,2,7,30,9.402058,0.377466
93,futhark,run_equilibrium_sa,local,M,3,2,7,30,3.571811,0.161769
94,matlab,-,-,-,-,2,7,30,11.409867,0.942833
95,futhark,run_equilibrium,futhark01,C,3,2,7,35,34.696898,1.806308
96,futhark,run_equilibrium,futhark01,M,3,2,7,35,3.505286,0.732407
97,futhark,run_equilibrium,futhark01,U,3,2,7,35,5.816401,0.775647
98,futhark,run_equilibrium,local,C,3,2,7,35,8.920049,0.068249
99,futhark,run_equilibrium,local,M,3,2,7,35,2.925500,0.087916
100,futhark,run_equilibrium_dp_solve,local,C,3,2,7,35,29.409879,0.386321
101,futhark,run_equilibrium_dp_solve,local,M,3,2,7,35,10.337387,0.091351
102,futhark,run_equilibrium_full_ad,local,C,3,2,7,35,17.611199,0.200899
103,futhark,run_equilibrium_full_ad,local,M,3,2,7,35,4.678566,0.274103
104,futhark,run_equilibrium_man,futhark01,C,3,2,7,35,5.081210,0.027119
105,futhark,run_equilibrium_man,futhark01,M,3,2,7,35,2.000710,0.052975
106,futhark,run_equilibrium_man,futhark01,U,3,2,7,35,3.388287,0.005819
107,futhark,run_equilibrium_man,local,C,3,2,7,35,2.003913,0.021994
108,futhark,run_equilibrium_man,local,M,3,2,7,35,1.340415,0.057960
109,futhark,run_equilibrium_man_sa,local,C,3,2,7,35,4.422974,0.018862
110,futhark,run_equilibrium_man_sa,local,M,3,2,7,35,2.697703,0.023150
111,futhark,run_equilibrium_sa,local,C,3,2,7,35,14.124853,0.232747
112,futhark,run_equilibrium_sa,local,M,3,2,7,35,5.512313,0.122313
113,matlab,-,-,-,-,2,7,35,19.765368,0.748713

=== cars_long: bench times ===

,source,run_equi,val_name,backend,runs,n,c,abar,mean,stdev
0,futhark,run_equilibrium,futhark01,C,3,2,1,25,0.077338,0.000086
1,futhark,run_equilibrium,futhark01,M,3,2,1,25,0.065449,0.006283
2,futhark,run_equilibrium,futhark01,U,3,2,1,25,0.289159,0.000572
3,futhark,run_equilibrium,local,C,3,2,1,25,0.015431,0.000122
4,futhark,run_equilibrium,local,M,3,2,1,25,0.047325,0.014614
5,futhark,run_equilibrium_almost_full_ad,futhark01,C,3,2,1,25,0.073071,0.000068
6,futhark,run_equilibrium_almost_full_ad,futhark01,M,3,2,1,25,0.083028,0.007827
7,futhark,run_equilibrium_almost_full_ad,futhark01,U,3,2,1,25,0.285914,0.000693
8,futhark,run_equilibrium_almost_full_ad,local,C,3,2,1,25,0.014388,0.000287
9,futhark,run_equilibrium_almost_full_ad,local,M,3,2,1,25,0.038469,0.007098
10,futhark,run_equilibrium_full_ad,local,C,3,2,1,25,0.031693,0.003330
11,futhark,run_equilibrium_full_ad,local,M,3,2,1,25,0.062610,0.012917
12,futhark,run_equilibrium_full_ad_alt,local,C,3,2,1,25,0.020164,0.001232
13,futhark,run_equilibrium_full_ad_alt,local,M,3,2,1,25,0.038322,0.001186
14,futhark,run_equilibrium_man,futhark01,C,3,2,1,25,0.024319,0.000030
15,futhark,run_equilibrium_man,futhark01,M,3,2,1,25,0.058998,0.000799
16,futhark,run_equilibrium_man,futhark01,U,3,2,1,25,0.292506,0.000426
17,futhark,run_equilibrium_man,local,C,3,2,1,25,0.005668,0.000408
18,futhark,run_equilibrium_man,local,M,3,2,1,25,0.060869,0.017337
19,futhark,run_equilibrium_man_sa,local,C,3,2,1,25,0.011003,0.000173
20,futhark,run_equilibrium_man_sa,local,M,3,2,1,25,0.072842,0.021598
21,matlab,-,-,-,-,2,1,25,0.105785,0.027910
22,futhark,run_equilibrium,futhark01,C,3,2,5,25,3.934542,0.309512
23,futhark,run_equilibrium,futhark01,M,3,2,5,25,0.588528,0.044075
24,futhark,run_equilibrium,futhark01,U,3,2,5,25,1.312285,0.000909
25,futhark,run_equilibrium,local,C,3,2,5,25,1.270393,0.037300
26,futhark,run_equilibrium,local,M,3,2,5,25,0.308382,0.009547
27,futhark,run_equilibrium_almost_full_ad,futhark01,C,3,2,5,25,3.349011,0.003201
28,futhark,run_equilibrium_almost_full_ad,futhark01,M,3,2,5,25,0.637250,0.064860
29,futhark,run_equilibrium_almost_full_ad,futhark01,U,3,2,5,25,1.292245,0.000265
30,futhark,run_equilibrium_almost_full_ad,local,C,3,2,5,25,1.157584,0.014966
31,futhark,run_equilibrium_almost_full_ad,local,M,3,2,5,25,0.284802,0.005058
32,futhark,run_equilibrium_full_ad,local,C,3,2,5,25,2.402666,0.155169
33,futhark,run_equilibrium_full_ad,local,M,3,2,5,25,0.714740,0.056340
34,futhark,run_equilibrium_full_ad_alt,local,C,3,2,5,25,1.571765,0.059677
35,futhark,run_equilibrium_full_ad_alt,local,M,3,2,5,25,0.401156,0.008851
36,futhark,run_equilibrium_man,futhark01,C,3,2,5,25,0.781393,0.191018
37,futhark,run_equilibrium_man,futhark01,M,3,2,5,25,0.403040,0.016153
38,futhark,run_equilibrium_man,futhark01,U,3,2,5,25,2.378817,0.514461
39,futhark,run_equilibrium_man,local,C,3,2,5,25,0.271691,0.003122
40,futhark,run_equilibrium_man,local,M,3,2,5,25,0.217664,0.029567
41,futhark,run_equilibrium_man_sa,local,C,3,2,5,25,1.587456,0.314871
42,futhark,run_equilibrium_man_sa,local,M,3,2,5,25,0.932053,0.164469
43,matlab,-,-,-,-,2,5,25,1.754218,0.030317
44,futhark,run_equilibrium,futhark01,C,3,2,9,25,17.633968,0.075447
45,futhark,run_equilibrium,futhark01,M,3,2,9,25,1.371026,0.084310
46,futhark,run_equilibrium,futhark01,U,3,2,9,25,2.535535,0.000933
47,futhark,run_equilibrium,local,C,3,2,9,25,5.712635,0.093886
48,futhark,run_equilibrium,local,M,3,2,9,25,1.842999,0.079794
49,futhark,run_equilibrium_almost_full_ad,futhark01,C,3,2,9,25,16.428222,0.482743
50,futhark,run_equilibrium_almost_full_ad,futhark01,M,3,2,9,25,1.840060,0.031618
51,futhark,run_equilibrium_almost_full_ad,futhark01,U,3,2,9,25,2.474481,0.002746
52,futhark,run_equilibrium_almost_full_ad,local,C,3,2,9,25,5.634460,0.057806
53,futhark,run_equilibrium_almost_full_ad,local,M,3,2,9,25,1.686068,0.075000
54,futhark,run_equilibrium_full_ad,local,C,3,2,9,25,10.351677,1.322068
55,futhark,run_equilibrium_full_ad,local,M,3,2,9,25,2.670150,0.098190
56,futhark,run_equilibrium_full_ad_alt,local,C,3,2,9,25,7.370573,0.139803
57,futhark,run_equilibrium_full_ad_alt,local,M,3,2,9,25,2.018871,0.106323
58,futhark,run_equilibrium_man,futhark01,C,3,2,9,25,3.224055,0.008248
59,futhark,run_equilibrium_man,futhark01,M,3,2,9,25,1.272435,0.010355
60,futhark,run_equilibrium_man,futhark01,U,3,2,9,25,4.836228,0.023913
61,futhark,run_equilibrium_man,local,C,3,2,9,25,1.354198,0.031164
62,futhark,run_equilibrium_man,local,M,3,2,9,25,0.935198,0.064591
63,futhark,run_equilibrium_man_sa,local,C,3,2,9,25,5.717989,0.216998
64,futhark,run_equilibrium_man_sa,local,M,3,2,9,25,3.478516,0.035564
65,matlab,-,-,-,-,2,9,25,10.211754,0.054219
66,futhark,run_equilibrium,futhark01,C,3,2,13,25,54.497105,0.445599
67,futhark,run_equilibrium,futhark01,M,3,2,13,25,3.872397,0.077124
68,futhark,run_equilibrium,futhark01,U,3,2,13,25,5.183548,0.004455
69,futhark,run_equilibrium,local,C,3,2,13,25,18.838399,1.161052
70,futhark,run_equilibrium,local,M,3,2,13,25,5.590788,0.113585
71,futhark,run_equilibrium_almost_full_ad,futhark01,C,3,2,13,25,49.161078,0.461043
72,futhark,run_equilibrium_almost_full_ad,futhark01,M,3,2,13,25,4.895131,0.096433
73,futhark,run_equilibrium_almost_full_ad,futhark01,U,3,2,13,25,5.018405,0.001390
74,futhark,run_equilibrium_almost_full_ad,local,C,3,2,13,25,17.505248,0.256408
75,futhark,run_equilibrium_almost_full_ad,local,M,3,2,13,25,4.539291,0.073331
76,futhark,run_equilibrium_full_ad,local,C,3,2,13,25,31.363837,1.214048
77,futhark,run_equilibrium_full_ad,local,M,3,2,13,25,8.113052,0.573088
78,futhark,run_equilibrium_full_ad_alt,local,C,3,2,13,25,23.526333,0.349581
79,futhark,run_equilibrium_full_ad_alt,local,M,3,2,13,25,5.401614,0.223962
80,futhark,run_equilibrium_man,futhark01,C,3,2,13,25,9.978703,0.004948
81,futhark,run_equilibrium_man,futhark01,M,3,2,13,25,2.589353,0.053451
82,futhark,run_equilibrium_man,futhark01,U,3,2,13,25,9.241270,0.330094
83,futhark,run_equilibrium_man,local,C,3,2,13,25,3.870256,0.006960
84,futhark,run_equilibrium_man,local,M,3,2,13,25,2.520932,0.109756
85,futhark,run_equilibrium_man_sa,local,C,3,2,13,25,16.820068,0.060414
86,futhark,run_equilibrium_man_sa,local,M,3,2,13,25,9.552806,0.094128
87,matlab,-,-,-,-,2,13,25,33.853231,3.864335
88,futhark,run_equilibrium,futhark01,C,3,2,17,25,126.820564,1.259650
89,futhark,run_equilibrium,futhark01,M,3,2,17,25,9.221466,0.076523
90,futhark,run_equilibrium,futhark01,U,3,2,17,25,6.878315,0.004409
91,futhark,run_equilibrium,local,C,3,2,17,25,42.287842,0.384940
92,futhark,run_equilibrium,local,M,3,2,17,25,13.801242,0.162382
93,futhark,run_equilibrium_almost_full_ad,futhark01,C,3,2,17,25,112.680211,0.884286
94,futhark,run_equilibrium_almost_full_ad,futhark01,M,3,2,17,25,10.614800,0.242930
95,futhark,run_equilibrium_almost_full_ad,futhark01,U,3,2,17,25,6.646844,0.006109
96,futhark,run_equilibrium_almost_full_ad,local,C,3,2,17,25,39.185543,0.479234
97,futhark,run_equilibrium_almost_full_ad,local,M,3,2,17,25,11.145464,0.308525
98,futhark,run_equilibrium_full_ad,local,C,3,2,17,25,66.775759,1.342854
99,futhark,run_equilibrium_full_ad,local,M,3,2,17,25,19.744620,0.450399
100,futhark,run_equilibrium_full_ad_alt,local,C,3,2,17,25,58.453828,0.271068
101,futhark,run_equilibrium_full_ad_alt,local,M,3,2,17,25,13.813504,0.568665
102,futhark,run_equilibrium_man,futhark01,C,3,2,17,25,21.492664,0.134910
103,futhark,run_equilibrium_man,futhark01,M,3,2,17,25,4.572540,0.360613
104,futhark,run_equilibrium_man,futhark01,U,3,2,17,25,11.841203,0.363658
105,futhark,run_equilibrium_man,local,C,3,2,17,25,8.994878,0.260844
106,futhark,run_equilibrium_man,local,M,3,2,17,25,5.475673,0.127985
107,futhark,run_equilibrium_man_sa,local,C,3,2,17,25,41.321785,0.859462
108,futhark,run_equilibrium_man_sa,local,M,3,2,17,25,23.249297,0.959392
109,matlab,-,-,-,-,2,17,25,118.626387,9.634622
110,futhark,run_equilibrium,futhark01,C,3,2,21,25,241.287080,1.816869
111,futhark,run_equilibrium,futhark01,M,3,2,21,25,13.855926,0.826463
112,futhark,run_equilibrium,futhark01,U,3,2,21,25,10.065132,0.002027
113,futhark,run_equilibrium,local,C,3,2,21,25,79.799575,0.705347
114,futhark,run_equilibrium,local,M,3,2,21,25,27.488477,1.779575
115,futhark,run_equilibrium_almost_full_ad,futhark01,C,3,2,21,25,219.303641,0.216799
116,futhark,run_equilibrium_almost_full_ad,futhark01,M,3,2,21,25,11.938648,0.487781
117,futhark,run_equilibrium_almost_full_ad,futhark01,U,3,2,21,25,9.484229,0.009105
118,futhark,run_equilibrium_almost_full_ad,local,C,3,2,21,25,80.888549,2.554037
119,futhark,run_equilibrium_almost_full_ad,local,M,3,2,21,25,22.533856,1.503948
120,futhark,run_equilibrium_full_ad,local,C,3,2,21,25,125.627635,1.257848
121,futhark,run_equilibrium_full_ad,local,M,3,2,21,25,37.656210,0.895366
122,futhark,run_equilibrium_full_ad_alt,local,C,3,2,21,25,118.690494,0.281580
123,futhark,run_equilibrium_full_ad_alt,local,M,3,2,21,25,25.173534,0.468155
124,futhark,run_equilibrium_man,futhark01,C,3,2,21,25,44.341214,0.037179
125,futhark,run_equilibrium_man,futhark01,M,3,2,21,25,10.746129,0.170451
126,futhark,run_equilibrium_man,futhark01,U,3,2,21,25,17.243547,0.262607
127,futhark,run_equilibrium_man,local,C,3,2,21,25,17.418605,0.081673
128,futhark,run_equilibrium_man,local,M,3,2,21,25,13.173890,2.010562
129,futhark,run_equilibrium_man_sa,local,C,3,2,21,25,76.806857,3.288866
130,futhark,run_equilibrium_man_sa,local,M,3,2,21,25,125.197974,48.727548
131,matlab,-,-,-,-,2,21,25,407.037305,36.981903

=== cars: MATLAB comparison + Futhark diagnostics ===

,run_equi,val_name,n,c,abar,acc0,trans,backend,filename,max_abs_ed,stat_res,norm_err,min_q,iter,conv,sa_iters_tot,nk_iters_tot,rtrips_tot,within_tol,max_abs_diff,max_rel_diff
0,run_equilibrium,3_local_new,2,1,25,5,0,C,run_equilibrium-3_local_new-validate_solve-2-1...,1.776060e-10,3.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041376e-07
1,run_equilibrium,3_local_new,2,3,25,5,0,C,run_equilibrium-3_local_new-validate_solve-2-3...,1.500000e-14,5.300000e-14,0.000000e+00,2.429617e-04,8,True,"[32, 32]","[8, 8]","[8, 8]",True,0.000004,1.298640e-07
2,run_equilibrium,3_local_new,2,5,25,5,0,C,run_equilibrium-3_local_new-validate_solve-2-5...,1.199000e-12,3.700000e-14,1.000000e-15,1.645633e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,2.444766e-07
3,run_equilibrium,3_local_new,2,7,25,5,0,C,run_equilibrium-3_local_new-validate_solve-2-7...,9.000000e-14,2.500000e-13,0.000000e+00,1.245906e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635894e-07
4,run_equilibrium,3_local_new,2,9,25,5,0,C,run_equilibrium-3_local_new-validate_solve-2-9...,1.601310e-10,1.190000e-13,1.000000e-15,1.002891e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.857835e-07
5,run_equilibrium,3_local_new,2,11,25,5,0,C,run_equilibrium-3_local_new-validate_solve-2-1...,1.488700e-11,3.640000e-13,1.000000e-15,8.393742e-05,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.817334e-07
6,run_equilibrium,3_local_new,2,13,25,5,0,C,run_equilibrium-3_local_new-validate_solve-2-1...,3.034000e-12,2.380000e-13,1.000000e-15,7.217770e-05,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.614682e-07
7,run_equilibrium,3_local_new,2,1,25,5,0,M,run_equilibrium-3_local_new-validate_solve-2-1...,1.776060e-10,6.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041376e-07
8,run_equilibrium,3_local_new,2,3,25,5,0,M,run_equilibrium-3_local_new-validate_solve-2-3...,1.500000e-14,5.300000e-14,0.000000e+00,2.429617e-04,8,True,"[32, 32]","[8, 8]","[8, 8]",True,0.000004,1.298640e-07
9,run_equilibrium,3_local_new,2,5,25,5,0,M,run_equilibrium-3_local_new-validate_solve-2-5...,1.199000e-12,3.700000e-14,1.000000e-15,1.645633e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,2.444766e-07
10,run_equilibrium,3_local_new,2,7,25,5,0,M,run_equilibrium-3_local_new-validate_solve-2-7...,9.000000e-14,2.500000e-13,0.000000e+00,1.245906e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635894e-07
11,run_equilibrium,3_local_new,2,9,25,5,0,M,run_equilibrium-3_local_new-validate_solve-2-9...,1.601310e-10,1.190000e-13,1.000000e-15,1.002891e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.857835e-07
12,run_equilibrium,3_local_new,2,11,25,5,0,M,run_equilibrium-3_local_new-validate_solve-2-1...,1.488700e-11,3.640000e-13,1.000000e-15,8.393742e-05,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.817334e-07
13,run_equilibrium,3_local_new,2,13,25,5,0,M,run_equilibrium-3_local_new-validate_solve-2-1...,3.034000e-12,2.380000e-13,1.000000e-15,7.217770e-05,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.614682e-07
14,run_equilibrium,futhark01,2,1,25,5,0,C,run_equilibrium-futhark01-validate_solve-2-1-2...,1.776050e-10,6.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041376e-07
15,run_equilibrium,futhark01,2,3,25,5,0,C,run_equilibrium-futhark01-validate_solve-2-3-2...,2.800000e-14,6.400000e-14,1.000000e-15,2.429617e-04,8,True,"[32, 32]","[8, 8]","[8, 8]",True,0.000004,1.298642e-07
16,run_equilibrium,futhark01,2,5,25,5,0,C,run_equilibrium-futhark01-validate_solve-2-5-2...,8.164651e-08,4.400000e-14,1.000000e-15,1.645633e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,2.442028e-07
17,run_equilibrium,futhark01,2,7,25,5,0,C,run_equilibrium-futhark01-validate_solve-2-7-2...,1.170000e-13,9.000000e-14,0.000000e+00,1.245906e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635888e-07
18,run_equilibrium,futhark01,2,9,25,5,0,C,run_equilibrium-futhark01-validate_solve-2-9-2...,7.078428e-07,1.310000e-13,0.000000e+00,1.002891e-04,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.696208e-07
19,run_equilibrium,futhark01,2,11,25,5,0,C,run_equilibrium-futhark01-validate_solve-2-11-...,1.488600e-11,2.320000e-13,0.000000e+00,8.393742e-05,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.817315e-07
20,run_equilibrium,futhark01,2,13,25,5,0,C,run_equilibrium-futhark01-validate_solve-2-13-...,9.993377e-08,3.360000e-13,1.000000e-15,7.217770e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.608359e-07
21,run_equilibrium,futhark01,2,17,25,5,0,C,run_equilibrium-futhark01-validate_solve-2-17-...,1.153871e-07,9.900000e-14,0.000000e+00,5.638751e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,3.015387e-07
22,run_equilibrium,futhark01,2,21,25,5,0,C,run_equilibrium-futhark01-validate_solve-2-21-...,1.140144e-07,9.070000e-13,0.000000e+00,4.626974e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,2.334436e-07
23,run_equilibrium,futhark01,2,1,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-1-2...,1.776050e-10,6.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041376e-07
24,run_equilibrium,futhark01,2,3,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-3-2...,2.800000e-14,6.400000e-14,1.000000e-15,2.429617e-04,8,True,"[32, 32]","[8, 8]","[8, 8]",True,0.000004,1.298642e-07
25,run_equilibrium,futhark01,2,5,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-5-2...,8.164651e-08,4.400000e-14,1.000000e-15,1.645633e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,2.442028e-07
26,run_equilibrium,futhark01,2,7,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-7-2...,1.760000e-13,4.900000e-14,0.000000e+00,1.245906e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635900e-07
27,run_equilibrium,futhark01,2,9,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-9-2...,7.078428e-07,1.940000e-13,0.000000e+00,1.002891e-04,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.696205e-07
28,run_equilibrium,futhark01,2,11,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-11-...,1.488700e-11,2.800000e-13,0.000000e+00,8.393742e-05,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.817310e-07
29,run_equilibrium,futhark01,2,13,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-13-...,9.993377e-08,3.620000e-13,0.000000e+00,7.217770e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.608369e-07
30,run_equilibrium,futhark01,2,17,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-17-...,1.153871e-07,1.010000e-13,0.000000e+00,5.638751e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,3.015367e-07
31,run_equilibrium,futhark01,2,21,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-21-...,1.140144e-07,4.150000e-13,0.000000e+00,4.626974e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,2.334428e-07
32,run_equilibrium,futhark01,2,25,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-25-...,1.075137e-07,2.140000e-13,0.000000e+00,3.923198e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
33,run_equilibrium,futhark01,2,29,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-29-...,9.986430e-08,7.860000e-13,1.000000e-15,3.405317e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
34,run_equilibrium,futhark01,2,33,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-33-...,9.241465e-08,3.590000e-13,0.000000e+00,3.008252e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
35,run_equilibrium,futhark01,2,1,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-1-2...,1.776050e-10,3.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041376e-07
36,run_equilibrium,futhark01,2,3,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-3-2...,2.500000e-14,1.900000e-14,0.000000e+00,2.429617e-04,8,True,"[32, 32]","[8, 8]","[8, 8]",True,0.000004,1.298642e-07
37,run_equilibrium,futhark01,2,5,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-5-2...,8.164651e-08,8.000000e-15,0.000000e+00,1.645633e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,2.442024e-07
38,run_equilibrium,futhark01,2,7,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-7-2...,2.500000e-14,9.800000e-14,0.000000e+00,1.245906e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635889e-07
39,run_equilibrium,futhark01,2,9,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-9-2...,7.078428e-07,4.600000e-14,0.000000e+00,1.002891e-04,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.696213e-07
40,run_equilibrium,futhark01,2,11,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-11-...,3.838900e-11,9.200000e-14,0.000000e+00,8.393742e-05,9,True,"[36, 36]","[9, 9]","[9, 9]",True,0.000004,1.815439e-07
41,run_equilibrium,futhark01,2,13,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-13-...,1.640648e-07,1.320000e-13,0.000000e+00,7.217768e-05,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000041,4.329165e-06
42,run_equilibrium,futhark01,2,17,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-17-...,5.149398e-07,4.180000e-13,1.000000e-15,5.638832e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000787,6.281871e-05
43,run_equilibrium,futhark01,2,21,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-21-...,6.759107e-07,2.630000e-13,0.000000e+00,4.627704e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",False,0.005926,3.140754e-04
44,run_equilibrium,futhark01,2,25,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-25-...,3.956094e-07,4.020000e-13,0.000000e+00,3.923579e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
45,run_equilibrium,futhark01,2,29,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-29-...,2.498612e-07,1.004000e-12,1.000000e-15,3.405534e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
46,run_equilibrium,futhark01,2,33,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-33-...,4.838467e-08,5.420000e-13,0.000000e+00,3.008261e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
47,run_equilibrium,local,2,1,25,5,0,C,run_equilibrium-local-validate_solve-2-1-25-5-...,1.776060e-10,3.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041376e-07
48,run_equilibrium,local,2,3,25,5,0,C,run_equilibrium-local-validate_solve-2-3-25-5-...,6.159482e-09,2.800000e-14,0.000000e+00,2.429617e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.298638e-07
49,run_equilibrium,local,2,5,25,5,0,C,run_equilibrium-local-validate_solve-2-5-25-5-...,8.164651e-08,1.700000e-14,0.000000e+00,1.645633e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,2.442022e-07
50,run_equilibrium,local,2,7,25,5,0,C,run_equilibrium-local-validate_solve-2-7-25-5-...,2.134065e-09,1.610000e-13,1.000000e-15,1.245906e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.635885e-07
51,run_equilibrium,local,2,9,25,5,0,C,run_equilibrium-local-validate_solve-2-9-25-5-...,7.078428e-07,2.040000e-13,1.000000e-15,1.002891e-04,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.696210e-07
52,run_equilibrium,local,2,11,25,5,0,C,run_equilibrium-local-validate_solve-2-11-25-5...,1.947470e-07,1.460000e-13,0.000000e+00,8.393742e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.777388e-07
53,run_equilibrium,local,2,13,25,5,0,C,run_equilibrium-local-validate_solve-2-13-25-5...,9.993377e-08,2.350000e-13,0.000000e+00,7.217770e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.608386e-07
54,run_equilibrium,local,2,17,25,5,0,C,run_equilibrium-local-validate_solve-2-17-25-5...,1.153871e-07,3.220000e-13,0.000000e+00,5.638751e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,3.015375e-07
55,run_equilibrium,local,2,21,25,5,0,C,run_equilibrium-local-validate_solve-2-21-25-5...,1.140144e-07,4.010000e-13,1.000000e-15,4.626974e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,2.334411e-07
56,run_equilibrium,local,2,1,25,5,0,M,run_equilibrium-local-validate_solve-2-1-25-5-...,1.776060e-10,8.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041376e-07
57,run_equilibrium,local,2,3,25,5,0,M,run_equilibrium-local-validate_solve-2-3-25-5-...,6.159482e-09,2.800000e-14,0.000000e+00,2.429617e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.298638e-07
58,run_equilibrium,local,2,5,25,5,0,M,run_equilibrium-local-validate_solve-2-5-25-5-...,8.164651e-08,1.700000e-14,0.000000e+00,1.645633e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,2.442022e-07
59,run_equilibrium,local,2,7,25,5,0,M,run_equilibrium-local-validate_solve-2-7-25-5-...,2.134065e-09,1.610000e-13,1.000000e-15,1.245906e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.635885e-07
60,run_equilibrium,local,2,9,25,5,0,M,run_equilibrium-local-validate_solve-2-9-25-5-...,7.078428e-07,2.040000e-13,1.000000e-15,1.002891e-04,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.696210e-07
61,run_equilibrium,local,2,11,25,5,0,M,run_equilibrium-local-validate_solve-2-11-25-5...,1.947470e-07,1.460000e-13,0.000000e+00,8.393742e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.777388e-07
62,run_equilibrium,local,2,13,25,5,0,M,run_equilibrium-local-validate_solve-2-13-25-5...,9.993377e-08,2.350000e-13,0.000000e+00,7.217770e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.608386e-07
63,run_equilibrium,local,2,17,25,5,0,M,run_equilibrium-local-validate_solve-2-17-25-5...,1.153871e-07,3.220000e-13,0.000000e+00,5.638751e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,3.015375e-07
64,run_equilibrium,local,2,21,25,5,0,M,run_equilibrium-local-validate_solve-2-21-25-5...,1.140144e-07,4.010000e-13,0.000000e+00,4.626974e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,2.334411e-07
65,run_equilibrium_almost_full_ad,futhark01,2,1,25,5,0,C,run_equilibrium_almost_full_ad-futhark01-valid...,1.776060e-10,7.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041376e-07
66,run_equilibrium_almost_full_ad,futhark01,2,5,25,5,0,C,run_equilibrium_almost_full_ad-futhark01-valid...,8.164651e-08,7.100000e-14,0.000000e+00,1.645633e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,2.442025e-07
67,run_equilibrium_almost_full_ad,futhark01,2,9,25,5,0,C,run_equilibrium_almost_full_ad-futhark01-valid...,7.078428e-07,7.800000e-14,0.000000e+00,1.002891e-04,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.696217e-07
68,run_equilibrium_almost_full_ad,futhark01,2,13,25,5,0,C,run_equilibrium_almost_full_ad-futhark01-valid...,9.993377e-08,1.850000e-13,0.000000e+00,7.217770e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.608380e-07
69,run_equilibrium_almost_full_ad,futhark01,2,17,25,5,0,C,run_equilibrium_almost_full_ad-futhark01-valid...,1.153871e-07,3.050000e-13,0.000000e+00,5.638751e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,3.015356e-07
70,run_equilibrium_almost_full_ad,futhark01,2,21,25,5,0,C,run_equilibrium_almost_full_ad-futhark01-valid...,1.140144e-07,2.740000e-13,0.000000e+00,4.626974e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,2.334410e-07
71,run_equilibrium_almost_full_ad,futhark01,2,1,25,5,0,M,run_equilibrium_almost_full_ad-futhark01-valid...,1.776060e-10,7.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041376e-07
72,run_equilibrium_almost_full_ad,futhark01,2,5,25,5,0,M,run_equilibrium_almost_full_ad-futhark01-valid...,8.164651e-08,7.100000e-14,1.000000e-15,1.645633e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,2.442025e-07
73,run_equilibrium_almost_full_ad,futhark01,2,9,25,5,0,M,run_equilibrium_almost_full_ad-futhark01-valid...,7.078428e-07,7.800000e-14,0.000000e+00,1.002891e-04,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.696217e-07
74,run_equilibrium_almost_full_ad,futhark01,2,13,25,5,0,M,run_equilibrium_almost_full_ad-futhark01-valid...,9.993377e-08,3.080000e-13,0.000000e+00,7.217770e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.608393e-07
75,run_equilibrium_almost_full_ad,futhark01,2,17,25,5,0,M,run_equilibrium_almost_full_ad-futhark01-valid...,1.153871e-07,2.210000e-13,0.000000e+00,5.638751e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,3.015375e-07
76,run_equilibrium_almost_full_ad,futhark01,2,21,25,5,0,M,run_equilibrium_almost_full_ad-futhark01-valid...,1.140144e-07,7.950000e-13,1.000000e-15,4.626974e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,2.334419e-07
77,run_equilibrium_almost_full_ad,futhark01,2,25,25,5,0,M,run_equilibrium_almost_full_ad-futhark01-valid...,1.075137e-07,8.580000e-13,1.000000e-15,3.923198e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
78,run_equilibrium_almost_full_ad,futhark01,2,29,25,5,0,M,run_equilibrium_almost_full_ad-futhark01-valid...,9.986430e-08,1.075000e-12,0.000000e+00,3.405317e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
79,run_equilibrium_almost_full_ad,futhark01,2,33,25,5,0,M,run_equilibrium_almost_full_ad-futhark01-valid...,9.241464e-08,2.100000e-13,1.000000e-15,3.008252e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
80,run_equilibrium_almost_full_ad,futhark01,2,1,25,5,0,U,run_equilibrium_almost_full_ad-futhark01-valid...,1.776060e-10,4.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041377e-07
81,run_equilibrium_almost_full_ad,futhark01,2,5,25,5,0,U,run_equilibrium_almost_full_ad-futhark01-valid...,8.164651e-08,3.300000e-14,0.000000e+00,1.645633e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,2.442028e-07
82,run_equilibrium_almost_full_ad,futhark01,2,9,25,5,0,U,run_equilibrium_almost_full_ad-futhark01-valid...,7.078428e-07,1.190000e-13,0.000000e+00,1.002891e-04,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.696213e-07
83,run_equilibrium_almost_full_ad,futhark01,2,13,25,5,0,U,run_equilibrium_almost_full_ad-futhark01-valid...,1.640648e-07,1.940000e-13,0.000000e+00,7.217768e-05,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000041,4.329165e-06
84,run_equilibrium_almost_full_ad,futhark01,2,17,25,5,0,U,run_equilibrium_almost_full_ad-futhark01-valid...,5.149398e-07,1.390000e-13,0.000000e+00,5.638832e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000787,6.281871e-05
85,run_equilibrium_almost_full_ad,futhark01,2,21,25,5,0,U,run_equilibrium_almost_full_ad-futhark01-valid...,6.759107e-07,6.440000e-13,0.000000e+00,4.627704e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",False,0.005926,3.140754e-04
86,run_equilibrium_almost_full_ad,futhark01,2,25,25,5,0,U,run_equilibrium_almost_full_ad-futhark01-valid...,3.956094e-07,2.340000e-13,0.000000e+00,3.923579e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
87,run_equilibrium_almost_full_ad,futhark01,2,29,25,5,0,U,run_equilibrium_almost_full_ad-futhark01-valid...,2.498612e-07,1.329000e-12,1.000000e-15,3.405534e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
88,run_equilibrium_almost_full_ad,futhark01,2,33,25,5,0,U,run_equilibrium_almost_full_ad-futhark01-valid...,4.838467e-08,9.140000e-13,1.000000e-15,3.008261e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
89,run_equilibrium_almost_full_ad,local,2,1,25,5,0,C,run_equilibrium_almost_full_ad-local-validate_...,1.776060e-10,4.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041376e-07
90,run_equilibrium_almost_full_ad,local,2,5,25,5,0,C,run_equilibrium_almost_full_ad-local-validate_...,8.164651e-08,4.200000e-14,0.000000e+00,1.645633e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,2.442032e-07
91,run_equilibrium_almost_full_ad,local,2,9,25,5,0,C,run_equilibrium_almost_full_ad-local-validate_...,7.078428e-07,6.800000e-14,0.000000e+00,1.002891e-04,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.696219e-07
92,run_equilibrium_almost_full_ad,local,2,13,25,5,0,C,run_equilibrium_almost_full_ad-local-validate_...,9.993377e-08,3.090000e-13,0.000000e+00,7.217770e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.608364e-07
93,run_equilibrium_almost_full_ad,local,2,17,25,5,0,C,run_equilibrium_almost_full_ad-local-validate_...,1.153871e-07,2.240000e-13,0.000000e+00,5.638751e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,3.015358e-07

=== households: MATLAB comparison + Futhark diagnostics ===

,run_equi,val_name,n,c,abar,acc0,trans,backend,filename,max_abs_ed,stat_res,norm_err,min_q,iter,conv,sa_iters_tot,nk_iters_tot,rtrips_tot,within_tol,max_abs_diff,max_rel_diff
0,run_equilibrium,3_local_new,2,7,25,5,0,C,run_equilibrium-3_local_new-validate_solve-2-7...,9.000000e-14,2.500000e-13,0.000000e+00,0.000125,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635894e-07
1,run_equilibrium,3_local_new,2,7,25,5,0,M,run_equilibrium-3_local_new-validate_solve-2-7...,9.000000e-14,2.500000e-13,0.000000e+00,0.000125,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635894e-07
2,run_equilibrium,futhark01,2,7,25,5,0,C,run_equilibrium-futhark01-validate_solve-2-7-2...,1.170000e-13,9.000000e-14,0.000000e+00,0.000125,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635888e-07
3,run_equilibrium,futhark01,3,7,25,5,0,C,run_equilibrium-futhark01-validate_solve-3-7-2...,6.000000e-15,3.600000e-14,0.000000e+00,0.000273,6,True,"[24, 24, 24]","[6, 6, 6]","[6, 6, 6]",True,0.000007,3.291834e-07
4,run_equilibrium,futhark01,4,7,25,5,0,C,run_equilibrium-futhark01-validate_solve-4-7-2...,9.100000e-14,8.200000e-14,1.000000e-15,0.000384,6,True,"[24, 24, 24, 24]","[6, 6, 6, 6]","[6, 6, 6, 6]",True,0.000005,2.529969e-07
5,run_equilibrium,futhark01,5,7,25,5,0,C,run_equilibrium-futhark01-validate_solve-5-7-2...,6.869810e-10,1.020000e-13,0.000000e+00,0.000457,5,True,"[20, 20, 20, 20, 20]","[5, 5, 5, 5, 5]","[5, 5, 5, 5, 5]",True,0.000006,2.735996e-07
6,run_equilibrium,futhark01,6,7,25,5,0,C,run_equilibrium-futhark01-validate_solve-6-7-2...,5.541980e-10,2.800000e-14,1.000000e-15,0.000505,5,True,"[20, 20, 20, 20, 20, 20]","[5, 5, 5, 5, 5, 5]","[5, 5, 5, 5, 5, 5]",True,0.000006,2.805666e-07
7,run_equilibrium,futhark01,2,7,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-7-2...,1.760000e-13,4.900000e-14,0.000000e+00,0.000125,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635900e-07
8,run_equilibrium,futhark01,3,7,25,5,0,M,run_equilibrium-futhark01-validate_solve-3-7-2...,6.000000e-15,3.600000e-14,0.000000e+00,0.000273,6,True,"[24, 24, 24]","[6, 6, 6]","[6, 6, 6]",True,0.000007,3.291834e-07
9,run_equilibrium,futhark01,4,7,25,5,0,M,run_equilibrium-futhark01-validate_solve-4-7-2...,9.100000e-14,8.200000e-14,0.000000e+00,0.000384,6,True,"[24, 24, 24, 24]","[6, 6, 6, 6]","[6, 6, 6, 6]",True,0.000005,2.529969e-07
10,run_equilibrium,futhark01,5,7,25,5,0,M,run_equilibrium-futhark01-validate_solve-5-7-2...,6.869820e-10,7.100000e-14,0.000000e+00,0.000457,5,True,"[20, 20, 20, 20, 20]","[5, 5, 5, 5, 5]","[5, 5, 5, 5, 5]",True,0.000006,2.735992e-07
11,run_equilibrium,futhark01,6,7,25,5,0,M,run_equilibrium-futhark01-validate_solve-6-7-2...,5.541980e-10,5.000000e-14,1.000000e-15,0.000505,5,True,"[20, 20, 20, 20, 20, 20]","[5, 5, 5, 5, 5, 5]","[5, 5, 5, 5, 5, 5]",True,0.000006,2.805663e-07
12,run_equilibrium,futhark01,2,7,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-7-2...,2.500000e-14,9.800000e-14,0.000000e+00,0.000125,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635889e-07
13,run_equilibrium,futhark01,3,7,25,5,0,U,run_equilibrium-futhark01-validate_solve-3-7-2...,4.500000e-14,1.250000e-13,0.000000e+00,0.000273,6,True,"[24, 24, 24]","[6, 6, 6]","[6, 6, 6]",True,0.000007,3.291825e-07
14,run_equilibrium,futhark01,4,7,25,5,0,U,run_equilibrium-futhark01-validate_solve-4-7-2...,7.000000e-14,7.800000e-14,0.000000e+00,0.000384,6,True,"[24, 24, 24, 24]","[6, 6, 6, 6]","[6, 6, 6, 6]",True,0.000005,2.529949e-07
15,run_equilibrium,futhark01,5,7,25,5,0,U,run_equilibrium-futhark01-validate_solve-5-7-2...,6.869830e-10,9.100000e-14,0.000000e+00,0.000457,5,True,"[20, 20, 20, 20, 20]","[5, 5, 5, 5, 5]","[5, 5, 5, 5, 5]",True,0.000006,2.735991e-07
16,run_equilibrium,futhark01,6,7,25,5,0,U,run_equilibrium-futhark01-validate_solve-6-7-2...,5.541990e-10,1.270000e-13,0.000000e+00,0.000505,5,True,"[20, 20, 20, 20, 20, 20]","[5, 5, 5, 5, 5, 5]","[5, 5, 5, 5, 5, 5]",True,0.000006,2.805665e-07
17,run_equilibrium,local,2,7,25,5,0,C,run_equilibrium-local-validate_solve-2-7-25-5-...,2.134065e-09,1.610000e-13,1.000000e-15,0.000125,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.635885e-07
18,run_equilibrium,local,3,7,25,5,0,C,run_equilibrium-local-validate_solve-3-7-25-5-...,9.449931e-09,6.200000e-14,0.000000e+00,0.000273,5,True,"[20, 20, 20]","[5, 5, 5]","[5, 5, 5]",True,0.000007,3.291844e-07
19,run_equilibrium,local,4,7,25,5,0,C,run_equilibrium-local-validate_solve-4-7-25-5-...,2.219233e-09,3.400000e-14,1.000000e-15,0.000384,5,True,"[20, 20, 20, 20]","[5, 5, 5, 5]","[5, 5, 5, 5]",True,0.000005,2.529973e-07
20,run_equilibrium,local,5,7,25,5,0,C,run_equilibrium-local-validate_solve-5-7-25-5-...,6.869820e-10,1.820000e-13,0.000000e+00,0.000457,5,True,"[20, 20, 20, 20, 20]","[5, 5, 5, 5, 5]","[5, 5, 5, 5, 5]",True,0.000006,2.735985e-07
21,run_equilibrium,local,6,7,25,5,0,C,run_equilibrium-local-validate_solve-6-7-25-5-...,5.542000e-10,6.200000e-14,0.000000e+00,0.000505,5,True,"[20, 20, 20, 20, 20, 20]","[5, 5, 5, 5, 5, 5]","[5, 5, 5, 5, 5, 5]",True,0.000006,2.805694e-07
22,run_equilibrium,local,2,7,25,5,0,M,run_equilibrium-local-validate_solve-2-7-25-5-...,2.134065e-09,1.610000e-13,1.000000e-15,0.000125,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.635885e-07
23,run_equilibrium,local,3,7,25,5,0,M,run_equilibrium-local-validate_solve-3-7-25-5-...,9.449931e-09,6.200000e-14,0.000000e+00,0.000273,5,True,"[20, 20, 20]","[5, 5, 5]","[5, 5, 5]",True,0.000007,3.291844e-07
24,run_equilibrium,local,4,7,25,5,0,M,run_equilibrium-local-validate_solve-4-7-25-5-...,2.219233e-09,3.400000e-14,1.000000e-15,0.000384,5,True,"[20, 20, 20, 20]","[5, 5, 5, 5]","[5, 5, 5, 5]",True,0.000005,2.529973e-07
25,run_equilibrium,local,5,7,25,5,0,M,run_equilibrium-local-validate_solve-5-7-25-5-...,6.869820e-10,1.820000e-13,0.000000e+00,0.000457,5,True,"[20, 20, 20, 20, 20]","[5, 5, 5, 5, 5]","[5, 5, 5, 5, 5]",True,0.000006,2.735985e-07
26,run_equilibrium,local,6,7,25,5,0,M,run_equilibrium-local-validate_solve-6-7-25-5-...,5.542000e-10,6.200000e-14,0.000000e+00,0.000505,5,True,"[20, 20, 20, 20, 20, 20]","[5, 5, 5, 5, 5, 5]","[5, 5, 5, 5, 5, 5]",True,0.000006,2.805694e-07
27,run_equilibrium_dp_solve,local,2,7,25,5,0,C,run_equilibrium_dp_solve-local-validate_solve-...,1.400000e-14,1.260000e-13,0.000000e+00,0.000125,6,True,"[-1, -1]","[-1, -1]","[-1, -1]",True,0.000004,1.635885e-07
28,run_equilibrium_dp_solve,local,3,7,25,5,0,C,run_equilibrium_dp_solve-local-validate_solve-...,1.500000e-13,5.100000e-14,1.000000e-15,0.000273,5,True,"[-1, -1, -1]","[-1, -1, -1]","[-1, -1, -1]",True,0.000007,3.291819e-07
29,run_equilibrium_dp_solve,local,4,7,25,5,0,C,run_equilibrium_dp_solve-local-validate_solve-...,3.600000e-14,1.300000e-13,0.000000e+00,0.000384,5,True,"[-1, -1, -1, -1]","[-1, -1, -1, -1]","[-1, -1, -1, -1]",True,0.000005,2.529984e-07
30,run_equilibrium_dp_solve,local,5,7,25,5,0,C,run_equilibrium_dp_solve-local-validate_solve-...,3.800000e-14,1.300000e-13,0.000000e+00,0.000457,5,True,"[-1, -1, -1, -1, -1]","[-1, -1, -1, -1, -1]","[-1, -1, -1, -1, -1]",True,0.000006,2.736030e-07
31,run_equilibrium_dp_solve,local,6,7,25,5,0,C,run_equilibrium_dp_solve-local-validate_solve-...,1.180000e-13,1.240000e-13,0.000000e+00,0.000505,5,True,"[-1, -1, -1, -1, -1, -1]","[-1, -1, -1, -1, -1, -1]","[-1, -1, -1, -1, -1, -1]",True,0.000006,2.805689e-07
32,run_equilibrium_dp_solve,local,2,7,25,5,0,M,run_equilibrium_dp_solve-local-validate_solve-...,1.400000e-14,1.260000e-13,0.000000e+00,0.000125,6,True,"[-1, -1]","[-1, -1]","[-1, -1]",True,0.000004,1.635885e-07
33,run_equilibrium_dp_solve,local,3,7,25,5,0,M,run_equilibrium_dp_solve-local-validate_solve-...,1.500000e-13,5.100000e-14,1.000000e-15,0.000273,5,True,"[-1, -1, -1]","[-1, -1, -1]","[-1, -1, -1]",True,0.000007,3.291819e-07
34,run_equilibrium_dp_solve,local,4,7,25,5,0,M,run_equilibrium_dp_solve-local-validate_solve-...,3.600000e-14,1.300000e-13,0.000000e+00,0.000384,5,True,"[-1, -1, -1, -1]","[-1, -1, -1, -1]","[-1, -1, -1, -1]",True,0.000005,2.529984e-07
35,run_equilibrium_dp_solve,local,5,7,25,5,0,M,run_equilibrium_dp_solve-local-validate_solve-...,3.800000e-14,1.300000e-13,0.000000e+00,0.000457,5,True,"[-1, -1, -1, -1, -1]","[-1, -1, -1, -1, -1]","[-1, -1, -1, -1, -1]",True,0.000006,2.736030e-07
36,run_equilibrium_dp_solve,local,6,7,25,5,0,M,run_equilibrium_dp_solve-local-validate_solve-...,1.180000e-13,1.240000e-13,0.000000e+00,0.000505,5,True,"[-1, -1, -1, -1, -1, -1]","[-1, -1, -1, -1, -1, -1]","[-1, -1, -1, -1, -1, -1]",True,0.000006,2.805689e-07
37,run_equilibrium_full_ad,local,2,7,25,5,0,C,run_equilibrium_full_ad-local-validate_solve-2...,1.680000e-13,2.400000e-14,0.000000e+00,0.000125,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635874e-07
38,run_equilibrium_full_ad,local,3,7,25,5,0,C,run_equilibrium_full_ad-local-validate_solve-3...,8.500000e-14,1.590000e-13,1.000000e-15,0.000273,6,True,"[24, 24, 24]","[6, 6, 6]","[6, 6, 6]",True,0.000007,3.291819e-07
39,run_equilibrium_full_ad,local,4,7,25,5,0,C,run_equilibrium_full_ad-local-validate_solve-4...,1.200000e-13,8.100000e-14,1.000000e-15,0.000384,6,True,"[24, 24, 24, 24]","[6, 6, 6, 6]","[6, 6, 6, 6]",True,0.000005,2.529957e-07
40,run_equilibrium_full_ad,local,5,7,25,5,0,C,run_equilibrium_full_ad-local-validate_solve-5...,6.869810e-10,9.200000e-14,0.000000e+00,0.000457,5,True,"[20, 20, 20, 20, 20]","[5, 5, 5, 5, 5]","[5, 5, 5, 5, 5]",True,0.000006,2.736001e-07
41,run_equilibrium_full_ad,local,6,7,25,5,0,C,run_equilibrium_full_ad-local-validate_solve-6...,5.541990e-10,1.550000e-13,1.000000e-15,0.000505,5,True,"[20, 20, 20, 20, 20, 20]","[5, 5, 5, 5, 5, 5]","[5, 5, 5, 5, 5, 5]",True,0.000006,2.805680e-07
42,run_equilibrium_full_ad,local,2,7,25,5,0,M,run_equilibrium_full_ad-local-validate_solve-2...,1.680000e-13,2.400000e-14,0.000000e+00,0.000125,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635874e-07
43,run_equilibrium_full_ad,local,3,7,25,5,0,M,run_equilibrium_full_ad-local-validate_solve-3...,8.500000e-14,1.590000e-13,1.000000e-15,0.000273,6,True,"[24, 24, 24]","[6, 6, 6]","[6, 6, 6]",True,0.000007,3.291819e-07
44,run_equilibrium_full_ad,local,4,7,25,5,0,M,run_equilibrium_full_ad-local-validate_solve-4...,1.200000e-13,8.100000e-14,1.000000e-15,0.000384,6,True,"[24, 24, 24, 24]","[6, 6, 6, 6]","[6, 6, 6, 6]",True,0.000005,2.529957e-07
45,run_equilibrium_full_ad,local,5,7,25,5,0,M,run_equilibrium_full_ad-local-validate_solve-5...,6.869810e-10,9.200000e-14,0.000000e+00,0.000457,5,True,"[20, 20, 20, 20, 20]","[5, 5, 5, 5, 5]","[5, 5, 5, 5, 5]",True,0.000006,2.736001e-07
46,run_equilibrium_full_ad,local,6,7,25,5,0,M,run_equilibrium_full_ad-local-validate_solve-6...,5.541990e-10,1.550000e-13,1.000000e-15,0.000505,5,True,"[20, 20, 20, 20, 20, 20]","[5, 5, 5, 5, 5, 5]","[5, 5, 5, 5, 5, 5]",True,0.000006,2.805680e-07
47,run_equilibrium_man,futhark01,2,7,25,5,0,C,run_equilibrium_man-futhark01-validate_solve-2...,4.000000e-15,6.400000e-14,0.000000e+00,0.000125,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635897e-07
48,run_equilibrium_man,futhark01,3,7,25,5,0,C,run_equilibrium_man-futhark01-validate_solve-3...,9.600000e-14,1.130000e-13,0.000000e+00,0.000273,6,True,"[24, 24, 24]","[6, 6, 6]","[6, 6, 6]",True,0.000007,3.291826e-07
49,run_equilibrium_man,futhark01,4,7,25,5,0,C,run_equilibrium_man-futhark01-validate_solve-4...,4.700000e-14,1.610000e-13,0.000000e+00,0.000384,6,True,"[24, 24, 24, 24]","[6, 6, 6, 6]","[6, 6, 6, 6]",True,0.000005,2.529961e-07
50,run_equilibrium_man,futhark01,5,7,25,5,0,C,run_equilibrium_man-futhark01-validate_solve-5...,6.869820e-10,1.730000e-13,0.000000e+00,0.000457,5,True,"[20, 20, 20, 20, 20]","[5, 5, 5, 5, 5]","[5, 5, 5, 5, 5]",True,0.000006,2.736006e-07
51,run_equilibrium_man,futhark01,6,7,25,5,0,C,run_equilibrium_man-futhark01-validate_solve-6...,5.542000e-10,8.500000e-14,1.000000e-15,0.000505,5,True,"[20, 20, 20, 20, 20, 20]","[5, 5, 5, 5, 5, 5]","[5, 5, 5, 5, 5, 5]",True,0.000006,2.805668e-07
52,run_equilibrium_man,futhark01,2,7,25,5,0,M,run_equilibrium_man-futhark01-validate_solve-2...,4.000000e-15,6.400000e-14,0.000000e+00,0.000125,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635897e-07
53,run_equilibrium_man,futhark01,3,7,25,5,0,M,run_equilibrium_man-futhark01-validate_solve-3...,9.600000e-14,1.130000e-13,1.000000e-15,0.000273,6,True,"[24, 24, 24]","[6, 6, 6]","[6, 6, 6]",True,0.000007,3.291826e-07
54,run_equilibrium_man,futhark01,4,7,25,5,0,M,run_equilibrium_man-futhark01-validate_solve-4...,4.700000e-14,1.610000e-13,0.000000e+00,0.000384,6,True,"[24, 24, 24, 24]","[6, 6, 6, 6]","[6, 6, 6, 6]",True,0.000005,2.529961e-07
55,run_equilibrium_man,futhark01,5,7,25,5,0,M,run_equilibrium_man-futhark01-validate_solve-5...,6.869820e-10,1.730000e-13,0.000000e+00,0.000457,5,True,"[20, 20, 20, 20, 20]","[5, 5, 5, 5, 5]","[5, 5, 5, 5, 5]",True,0.000006,2.736006e-07
56,run_equilibrium_man,futhark01,6,7,25,5,0,M,run_equilibrium_man-futhark01-validate_solve-6...,5.542000e-10,8.500000e-14,1.000000e-15,0.000505,5,True,"[20, 20, 20, 20, 20, 20]","[5, 5, 5, 5, 5, 5]","[5, 5, 5, 5, 5, 5]",True,0.000006,2.805668e-07
57,run_equilibrium_man,futhark01,2,7,25,5,0,U,run_equilibrium_man-futhark01-validate_solve-2...,6.200000e-14,8.300000e-14,0.000000e+00,0.000125,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635887e-07
58,run_equilibrium_man,futhark01,3,7,25,5,0,U,run_equilibrium_man-futhark01-validate_solve-3...,1.900000e-14,5.300000e-14,0.000000e+00,0.000273,6,True,"[24, 24, 24]","[6, 6, 6]","[6, 6, 6]",True,0.000007,3.291824e-07
59,run_equilibrium_man,futhark01,4,7,25,5,0,U,run_equilibrium_man-futhark01-validate_solve-4...,2.000000e-15,1.600000e-13,1.000000e-15,0.000384,6,True,"[24, 24, 24, 24]","[6, 6, 6, 6]","[6, 6, 6, 6]",True,0.000005,2.529974e-07
60,run_equilibrium_man,futhark01,5,7,25,5,0,U,run_equilibrium_man-futhark01-validate_solve-5...,6.869820e-10,8.700000e-14,0.000000e+00,0.000457,5,True,"[20, 20, 20, 20, 20]","[5, 5, 5, 5, 5]","[5, 5, 5, 5, 5]",True,0.000006,2.735982e-07
61,run_equilibrium_man,futhark01,6,7,25,5,0,U,run_equilibrium_man-futhark01-validate_solve-6...,5.541990e-10,7.600000e-14,0.000000e+00,0.000505,5,True,"[20, 20, 20, 20, 20, 20]","[5, 5, 5, 5, 5, 5]","[5, 5, 5, 5, 5, 5]",True,0.000006,2.805671e-07
62,run_equilibrium_man,local,2,7,25,5,0,C,run_equilibrium_man-local-validate_solve-2-7-2...,2.134065e-09,1.490000e-13,1.000000e-15,0.000125,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.635871e-07
63,run_equilibrium_man,local,3,7,25,5,0,C,run_equilibrium_man-local-validate_solve-3-7-2...,9.449986e-09,8.700000e-14,0.000000e+00,0.000273,5,True,"[20, 20, 20]","[5, 5, 5]","[5, 5, 5]",True,0.000007,3.291827e-07
64,run_equilibrium_man,local,4,7,25,5,0,C,run_equilibrium_man-local-validate_solve-4-7-2...,2.219132e-09,1.560000e-13,0.000000e+00,0.000384,5,True,"[20, 20, 20, 20]","[5, 5, 5, 5]","[5, 5, 5, 5]",True,0.000005,2.529968e-07
65,run_equilibrium_man,local,5,7,25,5,0,C,run_equilibrium_man-local-validate_solve-5-7-2...,6.869810e-10,1.570000e-13,0.000000e+00,0.000457,5,True,"[20, 20, 20, 20, 20]","[5, 5, 5, 5, 5]","[5, 5, 5, 5, 5]",True,0.000006,2.735986e-07
66,run_equilibrium_man,local,6,7,25,5,0,C,run_equilibrium_man-local-validate_solve-6-7-2...,5.541990e-10,7.100000e-14,0.000000e+00,0.000505,5,True,"[20, 20, 20, 20, 20, 20]","[5, 5, 5, 5, 5, 5]","[5, 5, 5, 5, 5, 5]",True,0.000006,2.805675e-07
67,run_equilibrium_man,local,2,7,25,5,0,M,run_equilibrium_man-local-validate_solve-2-7-2...,2.134065e-09,1.490000e-13,1.000000e-15,0.000125,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.635871e-07
68,run_equilibrium_man,local,3,7,25,5,0,M,run_equilibrium_man-local-validate_solve-3-7-2...,9.449986e-09,8.700000e-14,0.000000e+00,0.000273,5,True,"[20, 20, 20]","[5, 5, 5]","[5, 5, 5]",True,0.000007,3.291827e-07
69,run_equilibrium_man,local,4,7,25,5,0,M,run_equilibrium_man-local-validate_solve-4-7-2...,2.219132e-09,1.560000e-13,0.000000e+00,0.000384,5,True,"[20, 20, 20, 20]","[5, 5, 5, 5]","[5, 5, 5, 5]",True,0.000005,2.529968e-07
70,run_equilibrium_man,local,5,7,25,5,0,M,run_equilibrium_man-local-validate_solve-5-7-2...,6.869810e-10,1.570000e-13,0.000000e+00,0.000457,5,True,"[20, 20, 20, 20, 20]","[5, 5, 5, 5, 5]","[5, 5, 5, 5, 5]",True,0.000006,2.735986e-07
71,run_equilibrium_man,local,6,7,25,5,0,M,run_equilibrium_man-local-validate_solve-6-7-2...,5.541990e-10,7.100000e-14,0.000000e+00,0.000505,5,True,"[20, 20, 20, 20, 20, 20]","[5, 5, 5, 5, 5, 5]","[5, 5, 5, 5, 5, 5]",True,0.000006,2.805675e-07
72,run_equilibrium_man_sa,local,2,7,25,5,0,C,run_equilibrium_man_sa-local-validate_solve-2-...,1.186979e+00,1.240000e-13,1.000000e-15,0.000008,20,False,"[400, 400]","[0, 0]","[0, 0]",False,91.750232,3.780317e+01
73,run_equilibrium_man_sa,local,3,7,25,5,0,C,run_equilibrium_man_sa-local-validate_solve-3-...,1.072225e+00,1.420000e-13,1.000000e-15,0.000003,20,False,"[400, 400, 400]","[0, 0, 0]","[0, 0, 0]",False,75.807328,3.231293e+01
74,run_equilibrium_man_sa,local,4,7,25,5,0,C,run_equilibrium_man_sa-local-validate_solve-4-...,9.977834e-01,8.800000e-14,1.000000e-15,0.000003,20,False,"[400, 400, 400, 400]","[0, 0, 0, 0]","[0, 0, 0, 0]",False,70.182389,3.335467e+01
75,run_equilibrium_man_sa,local,5,7,25,5,0,C,run_equilibrium_man_sa-local-validate_solve-5-...,9.687971e-01,3.700000e-14,1.000000e-15,0.000003,20,False,"[400, 400, 400, 400, 400]","[0, 0, 0, 0, 0]","[0, 0, 0, 0, 0]",False,71.390121,3.641879e+01
76,run_equilibrium_man_sa,local,6,7,25,5,0,C,run_equilibrium_man_sa-local-validate_solve-6-...,9.568379e-01,3.000000e-14,0.000000e+00,0.000003,20,False,"[400, 400, 400, 400, 400, 400]","[0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0]",False,75.578176,4.039876e+01
77,run_equilibrium_man_sa,local,2,7,25,5,0,M,run_equilibrium_man_sa-local-validate_solve-2-...,1.186979e+00,1.240000e-13,1.000000e-15,0.000008,20,False,"[400, 400]","[0, 0]","[0, 0]",False,91.750232,3.780317e+01
78,run_equilibrium_man_sa,local,3,7,25,5,0,M,run_equilibrium_man_sa-local-validate_solve-3-...,1.072225e+00,1.420000e-13,0.000000e+00,0.000003,20,False,"[400, 400, 400]","[0, 0, 0]","[0, 0, 0]",False,75.807328,3.231293e+01
79,run_equilibrium_man_sa,local,4,7,25,5,0,M,run_equilibrium_man_sa-local-validate_solve-4-...,9.977834e-01,8.800000e-14,0.000000e+00,0.000003,20,False,"[400, 400, 400, 400]","[0, 0, 0, 0]","[0, 0, 0, 0]",False,70.182389,3.335467e+01
80,run_equilibrium_man_sa,local,5,7,25,5,0,M,run_equilibrium_man_sa-local-validate_solve-5-...,9.687971e-01,3.700000e-14,0.000000e+00,0.000003,20,False,"[400, 400, 400, 400, 400]","[0, 0, 0, 0, 0]","[0, 0, 0, 0, 0]",False,71.390121,3.641879e+01
81,run_equilibrium_man_sa,local,6,7,25,5,0,M,run_equilibrium_man_sa-local-validate_solve-6-...,9.568379e-01,3.000000e-14,0.000000e+00,0.000003,20,False,"[400, 400, 400, 400, 400, 400]","[0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0]",False,75.578176,4.039876e+01
82,run_equilibrium_sa,local,2,7,25,5,0,C,run_equilibrium_sa-local-validate_solve-2-7-25...,1.930000e-13,1.690000e-13,0.000000e+00,0.000125,7,True,"[3403, 3295]","[0, 0]","[0, 0]",True,0.000004,1.647874e-07
83,run_equilibrium_sa,local,3,7,25,5,0,C,run_equilibrium_sa-local-validate_solve-3-7-25...,5.300000e-14,1.460000e-13,2.000000e-15,0.000273,6,True,"[2918, 2806, 2806]","[0, 0, 0]","[0, 0, 0]",True,0.000007,3.301034e-07
84,run_equilibrium_sa,local,4,7,25,5,0,C,run_equilibrium_sa-local-validate_solve-4-7-25...,1.100000e-14,9.500000e-14,0.000000e+00,0.000384,6,True,"[2922, 2798, 2798, 2798]","[0, 0, 0, 0]","[0, 0, 0, 0]",True,0.000005,2.544437e-07
85,run_equilibrium_sa,local,5,7,25,5,0,C,run_equilibrium_sa-local-validate_solve-5-7-25...,6.869820e-10,7.000000e-14,0.000000e+00,0.000457,5,True,"[2435, 2327, 2327, 2327, 2327]","[0, 0, 0, 0, 0]","[0, 0, 0, 0, 0]",True,0.000006,2.749746e-07
86,run_equilibrium_sa,local,6,7,25,5,0,C,run_equilibrium_sa-local-validate_solve-6-7-25...,5.541990e-10,1.440000e-13,0.000000e+00,0.000505,5,True,"[2435, 2324, 2324, 2324, 2324, 2324]","[0, 0, 0, 0, 0, 0]","[0, 0, 0, 0, 0, 0]",True,0.000006,2.819752e-07

=== age: MATLAB comparison + Futhark diagnostics ===

,run_equi,val_name,n,c,abar,acc0,trans,backend,filename,max_abs_ed,stat_res,norm_err,min_q,iter,conv,sa_iters_tot,nk_iters_tot,rtrips_tot,within_tol,max_abs_diff,max_rel_diff
0,run_equilibrium,3_local_new,2,7,25,5,0,C,run_equilibrium-3_local_new-validate_solve-2-7...,9.000000e-14,2.500000e-13,0.000000e+00,1.245906e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635894e-07
1,run_equilibrium,3_local_new,2,7,25,5,0,M,run_equilibrium-3_local_new-validate_solve-2-7...,9.000000e-14,2.500000e-13,0.000000e+00,1.245906e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635894e-07
2,run_equilibrium,futhark01,2,7,10,5,0,C,run_equilibrium-futhark01-validate_solve-2-7-1...,2.167800e-11,6.900000e-14,1.000000e-15,9.404310e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000002,4.316708e-08
3,run_equilibrium,futhark01,2,7,15,5,0,C,run_equilibrium-futhark01-validate_solve-2-7-1...,1.100000e-14,1.000000e-13,1.000000e-15,8.037581e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000005,1.926052e-07
4,run_equilibrium,futhark01,2,7,20,5,0,C,run_equilibrium-futhark01-validate_solve-2-7-2...,8.179000e-12,9.200000e-14,0.000000e+00,1.622109e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.662682e-07
5,run_equilibrium,futhark01,2,7,25,5,0,C,run_equilibrium-futhark01-validate_solve-2-7-2...,1.170000e-13,9.000000e-14,0.000000e+00,1.245906e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635888e-07
6,run_equilibrium,futhark01,2,7,30,5,0,C,run_equilibrium-futhark01-validate_solve-2-7-3...,1.500000e-13,1.460000e-13,1.000000e-15,1.013898e-05,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000007,2.794752e-07
7,run_equilibrium,futhark01,2,7,35,5,0,C,run_equilibrium-futhark01-validate_solve-2-7-3...,2.370000e-13,1.180000e-13,1.000000e-15,8.315462e-07,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000007,2.799875e-07
8,run_equilibrium,futhark01,2,7,10,5,0,M,run_equilibrium-futhark01-validate_solve-2-7-1...,2.167800e-11,6.900000e-14,1.000000e-15,9.404310e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000002,4.316708e-08
9,run_equilibrium,futhark01,2,7,15,5,0,M,run_equilibrium-futhark01-validate_solve-2-7-1...,1.100000e-14,1.000000e-13,1.000000e-15,8.037581e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000005,1.926052e-07
10,run_equilibrium,futhark01,2,7,20,5,0,M,run_equilibrium-futhark01-validate_solve-2-7-2...,8.179000e-12,9.200000e-14,0.000000e+00,1.622109e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.662682e-07
11,run_equilibrium,futhark01,2,7,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-7-2...,1.760000e-13,4.900000e-14,0.000000e+00,1.245906e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635900e-07
12,run_equilibrium,futhark01,2,7,30,5,0,M,run_equilibrium-futhark01-validate_solve-2-7-3...,9.000000e-15,5.400000e-14,0.000000e+00,1.013898e-05,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000007,2.794746e-07
13,run_equilibrium,futhark01,2,7,35,5,0,M,run_equilibrium-futhark01-validate_solve-2-7-3...,1.360000e-13,6.800000e-14,0.000000e+00,8.315462e-07,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000007,2.799863e-07
14,run_equilibrium,futhark01,2,7,10,5,0,U,run_equilibrium-futhark01-validate_solve-2-7-1...,2.167800e-11,5.000000e-15,0.000000e+00,9.404310e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000002,4.316712e-08
15,run_equilibrium,futhark01,2,7,15,5,0,U,run_equilibrium-futhark01-validate_solve-2-7-1...,1.600000e-14,5.800000e-14,0.000000e+00,8.037581e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000005,1.926050e-07
16,run_equilibrium,futhark01,2,7,20,5,0,U,run_equilibrium-futhark01-validate_solve-2-7-2...,8.179000e-12,6.400000e-14,0.000000e+00,1.622109e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.662678e-07
17,run_equilibrium,futhark01,2,7,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-7-2...,2.500000e-14,9.800000e-14,0.000000e+00,1.245906e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635889e-07
18,run_equilibrium,futhark01,2,7,30,5,0,U,run_equilibrium-futhark01-validate_solve-2-7-3...,6.100000e-14,1.190000e-13,0.000000e+00,1.013898e-05,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000007,2.794750e-07
19,run_equilibrium,futhark01,2,7,35,5,0,U,run_equilibrium-futhark01-validate_solve-2-7-3...,1.110000e-13,8.300000e-14,0.000000e+00,8.315462e-07,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000007,2.799874e-07
20,run_equilibrium,local,2,7,10,5,0,C,run_equilibrium-local-validate_solve-2-7-10-5-...,6.709063e-07,1.100000e-14,0.000000e+00,9.404310e-03,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000002,4.317028e-08
21,run_equilibrium,local,2,7,15,5,0,C,run_equilibrium-local-validate_solve-2-7-15-5-...,2.005111e-08,1.500000e-14,0.000000e+00,8.037581e-03,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,1.926053e-07
22,run_equilibrium,local,2,7,20,5,0,C,run_equilibrium-local-validate_solve-2-7-20-5-...,2.208934e-07,8.900000e-14,1.000000e-15,1.622109e-03,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.658904e-07
23,run_equilibrium,local,2,7,25,5,0,C,run_equilibrium-local-validate_solve-2-7-25-5-...,2.134065e-09,1.610000e-13,1.000000e-15,1.245906e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.635885e-07
24,run_equilibrium,local,2,7,30,5,0,C,run_equilibrium-local-validate_solve-2-7-30-5-...,3.740529e-09,6.400000e-14,0.000000e+00,1.013898e-05,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000007,2.794743e-07
25,run_equilibrium,local,2,7,35,5,0,C,run_equilibrium-local-validate_solve-2-7-35-5-...,3.944061e-09,5.600000e-14,0.000000e+00,8.315462e-07,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000007,2.799872e-07
26,run_equilibrium,local,2,7,10,5,0,M,run_equilibrium-local-validate_solve-2-7-10-5-...,6.709063e-07,1.100000e-14,0.000000e+00,9.404310e-03,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000002,4.317028e-08
27,run_equilibrium,local,2,7,15,5,0,M,run_equilibrium-local-validate_solve-2-7-15-5-...,2.005111e-08,1.500000e-14,0.000000e+00,8.037581e-03,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,1.926053e-07
28,run_equilibrium,local,2,7,20,5,0,M,run_equilibrium-local-validate_solve-2-7-20-5-...,2.208934e-07,8.900000e-14,1.000000e-15,1.622109e-03,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.658904e-07
29,run_equilibrium,local,2,7,25,5,0,M,run_equilibrium-local-validate_solve-2-7-25-5-...,2.134065e-09,1.610000e-13,1.000000e-15,1.245906e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.635885e-07
30,run_equilibrium,local,2,7,30,5,0,M,run_equilibrium-local-validate_solve-2-7-30-5-...,3.740529e-09,6.400000e-14,0.000000e+00,1.013898e-05,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000007,2.794743e-07
31,run_equilibrium,local,2,7,35,5,0,M,run_equilibrium-local-validate_solve-2-7-35-5-...,3.944061e-09,5.600000e-14,0.000000e+00,8.315462e-07,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000007,2.799872e-07
32,run_equilibrium_dp_solve,local,2,7,10,5,0,C,run_equilibrium_dp_solve-local-validate_solve-...,2.301700e-11,1.800000e-14,0.000000e+00,9.404310e-03,5,True,"[-1, -1]","[-1, -1]","[-1, -1]",True,0.000002,4.317064e-08
33,run_equilibrium_dp_solve,local,2,7,15,5,0,C,run_equilibrium_dp_solve-local-validate_solve-...,3.700000e-14,6.200000e-14,0.000000e+00,8.037581e-03,5,True,"[-1, -1]","[-1, -1]","[-1, -1]",True,0.000005,1.926056e-07
34,run_equilibrium_dp_solve,local,2,7,20,5,0,C,run_equilibrium_dp_solve-local-validate_solve-...,8.182000e-12,1.300000e-14,1.000000e-15,1.622109e-03,5,True,"[-1, -1]","[-1, -1]","[-1, -1]",True,0.000004,1.658542e-07
35,run_equilibrium_dp_solve,local,2,7,25,5,0,C,run_equilibrium_dp_solve-local-validate_solve-...,1.400000e-14,1.260000e-13,0.000000e+00,1.245906e-04,6,True,"[-1, -1]","[-1, -1]","[-1, -1]",True,0.000004,1.635885e-07
36,run_equilibrium_dp_solve,local,2,7,30,5,0,C,run_equilibrium_dp_solve-local-validate_solve-...,1.900000e-13,7.800000e-14,0.000000e+00,1.013898e-05,6,True,"[-1, -1]","[-1, -1]","[-1, -1]",True,0.000007,2.794762e-07
37,run_equilibrium_dp_solve,local,2,7,35,5,0,C,run_equilibrium_dp_solve-local-validate_solve-...,7.200000e-14,1.690000e-13,0.000000e+00,8.315462e-07,6,True,"[-1, -1]","[-1, -1]","[-1, -1]",True,0.000007,2.799879e-07
38,run_equilibrium_dp_solve,local,2,7,10,5,0,M,run_equilibrium_dp_solve-local-validate_solve-...,2.301700e-11,1.800000e-14,0.000000e+00,9.404310e-03,5,True,"[-1, -1]","[-1, -1]","[-1, -1]",True,0.000002,4.317064e-08
39,run_equilibrium_dp_solve,local,2,7,15,5,0,M,run_equilibrium_dp_solve-local-validate_solve-...,3.700000e-14,6.200000e-14,0.000000e+00,8.037581e-03,5,True,"[-1, -1]","[-1, -1]","[-1, -1]",True,0.000005,1.926056e-07
40,run_equilibrium_dp_solve,local,2,7,20,5,0,M,run_equilibrium_dp_solve-local-validate_solve-...,8.182000e-12,1.300000e-14,1.000000e-15,1.622109e-03,5,True,"[-1, -1]","[-1, -1]","[-1, -1]",True,0.000004,1.658542e-07
41,run_equilibrium_dp_solve,local,2,7,25,5,0,M,run_equilibrium_dp_solve-local-validate_solve-...,1.400000e-14,1.260000e-13,0.000000e+00,1.245906e-04,6,True,"[-1, -1]","[-1, -1]","[-1, -1]",True,0.000004,1.635885e-07
42,run_equilibrium_dp_solve,local,2,7,30,5,0,M,run_equilibrium_dp_solve-local-validate_solve-...,1.900000e-13,7.800000e-14,0.000000e+00,1.013898e-05,6,True,"[-1, -1]","[-1, -1]","[-1, -1]",True,0.000007,2.794762e-07
43,run_equilibrium_dp_solve,local,2,7,35,5,0,M,run_equilibrium_dp_solve-local-validate_solve-...,7.200000e-14,1.690000e-13,0.000000e+00,8.315462e-07,6,True,"[-1, -1]","[-1, -1]","[-1, -1]",True,0.000007,2.799879e-07
44,run_equilibrium_full_ad,local,2,7,10,5,0,C,run_equilibrium_full_ad-local-validate_solve-2...,2.167700e-11,6.000000e-15,0.000000e+00,9.404310e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000002,4.316711e-08
45,run_equilibrium_full_ad,local,2,7,15,5,0,C,run_equilibrium_full_ad-local-validate_solve-2...,5.000000e-14,4.600000e-14,0.000000e+00,8.037581e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000005,1.926053e-07
46,run_equilibrium_full_ad,local,2,7,20,5,0,C,run_equilibrium_full_ad-local-validate_solve-2...,8.179000e-12,1.490000e-13,1.000000e-15,1.622109e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.662691e-07
47,run_equilibrium_full_ad,local,2,7,25,5,0,C,run_equilibrium_full_ad-local-validate_solve-2...,1.680000e-13,2.400000e-14,0.000000e+00,1.245906e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635874e-07
48,run_equilibrium_full_ad,local,2,7,30,5,0,C,run_equilibrium_full_ad-local-validate_solve-2...,2.000000e-14,1.520000e-13,0.000000e+00,1.013898e-05,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000007,2.794758e-07
49,run_equilibrium_full_ad,local,2,7,35,5,0,C,run_equilibrium_full_ad-local-validate_solve-2...,1.630000e-13,9.400000e-14,1.000000e-15,8.315462e-07,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000007,2.799866e-07
50,run_equilibrium_full_ad,local,2,7,10,5,0,M,run_equilibrium_full_ad-local-validate_solve-2...,2.167700e-11,6.000000e-15,0.000000e+00,9.404310e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000002,4.316711e-08
51,run_equilibrium_full_ad,local,2,7,15,5,0,M,run_equilibrium_full_ad-local-validate_solve-2...,5.000000e-14,4.600000e-14,0.000000e+00,8.037581e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000005,1.926053e-07
52,run_equilibrium_full_ad,local,2,7,20,5,0,M,run_equilibrium_full_ad-local-validate_solve-2...,8.179000e-12,1.490000e-13,1.000000e-15,1.622109e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.662691e-07
53,run_equilibrium_full_ad,local,2,7,25,5,0,M,run_equilibrium_full_ad-local-validate_solve-2...,1.680000e-13,2.400000e-14,0.000000e+00,1.245906e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635874e-07
54,run_equilibrium_full_ad,local,2,7,30,5,0,M,run_equilibrium_full_ad-local-validate_solve-2...,2.000000e-14,1.520000e-13,0.000000e+00,1.013898e-05,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000007,2.794758e-07
55,run_equilibrium_full_ad,local,2,7,35,5,0,M,run_equilibrium_full_ad-local-validate_solve-2...,1.630000e-13,9.400000e-14,1.000000e-15,8.315462e-07,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000007,2.799866e-07
56,run_equilibrium_man,futhark01,2,7,10,5,0,C,run_equilibrium_man-futhark01-validate_solve-2...,2.167800e-11,1.400000e-14,0.000000e+00,9.404310e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000002,4.316710e-08
57,run_equilibrium_man,futhark01,2,7,15,5,0,C,run_equilibrium_man-futhark01-validate_solve-2...,3.400000e-14,6.900000e-14,0.000000e+00,8.037581e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000005,1.926051e-07
58,run_equilibrium_man,futhark01,2,7,20,5,0,C,run_equilibrium_man-futhark01-validate_solve-2...,8.178000e-12,6.400000e-14,0.000000e+00,1.622109e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.662674e-07
59,run_equilibrium_man,futhark01,2,7,25,5,0,C,run_equilibrium_man-futhark01-validate_solve-2...,4.000000e-15,6.400000e-14,0.000000e+00,1.245906e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635897e-07
60,run_equilibrium_man,futhark01,2,7,30,5,0,C,run_equilibrium_man-futhark01-validate_solve-2...,1.010000e-13,1.580000e-13,0.000000e+00,1.013898e-05,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000007,2.794749e-07
61,run_equilibrium_man,futhark01,2,7,35,5,0,C,run_equilibrium_man-futhark01-validate_solve-2...,1.280000e-13,1.650000e-13,0.000000e+00,8.315462e-07,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000007,2.799868e-07
62,run_equilibrium_man,futhark01,2,7,10,5,0,M,run_equilibrium_man-futhark01-validate_solve-2...,2.167800e-11,2.700000e-14,0.000000e+00,9.404310e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000002,4.316713e-08
63,run_equilibrium_man,futhark01,2,7,15,5,0,M,run_equilibrium_man-futhark01-validate_solve-2...,3.400000e-14,6.900000e-14,0.000000e+00,8.037581e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000005,1.926051e-07
64,run_equilibrium_man,futhark01,2,7,20,5,0,M,run_equilibrium_man-futhark01-validate_solve-2...,8.178000e-12,6.400000e-14,0.000000e+00,1.622109e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.662674e-07
65,run_equilibrium_man,futhark01,2,7,25,5,0,M,run_equilibrium_man-futhark01-validate_solve-2...,4.000000e-15,6.400000e-14,0.000000e+00,1.245906e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635897e-07
66,run_equilibrium_man,futhark01,2,7,30,5,0,M,run_equilibrium_man-futhark01-validate_solve-2...,1.010000e-13,1.580000e-13,0.000000e+00,1.013898e-05,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000007,2.794749e-07
67,run_equilibrium_man,futhark01,2,7,35,5,0,M,run_equilibrium_man-futhark01-validate_solve-2...,3.300000e-14,5.700000e-14,0.000000e+00,8.315462e-07,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000007,2.799868e-07
68,run_equilibrium_man,futhark01,2,7,10,5,0,U,run_equilibrium_man-futhark01-validate_solve-2...,2.167800e-11,1.600000e-14,0.000000e+00,9.404310e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000002,4.316710e-08
69,run_equilibrium_man,futhark01,2,7,15,5,0,U,run_equilibrium_man-futhark01-validate_solve-2...,1.500000e-14,6.900000e-14,0.000000e+00,8.037581e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000005,1.926049e-07
70,run_equilibrium_man,futhark01,2,7,20,5,0,U,run_equilibrium_man-futhark01-validate_solve-2...,8.179000e-12,1.900000e-14,0.000000e+00,1.622109e-03,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.662683e-07
71,run_equilibrium_man,futhark01,2,7,25,5,0,U,run_equilibrium_man-futhark01-validate_solve-2...,6.200000e-14,8.300000e-14,0.000000e+00,1.245906e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635887e-07
72,run_equilibrium_man,futhark01,2,7,30,5,0,U,run_equilibrium_man-futhark01-validate_solve-2...,6.600000e-14,8.400000e-14,0.000000e+00,1.013898e-05,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000007,2.794747e-07
73,run_equilibrium_man,futhark01,2,7,35,5,0,U,run_equilibrium_man-futhark01-validate_solve-2...,4.600000e-14,1.150000e-13,0.000000e+00,8.315462e-07,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000007,2.799875e-07
74,run_equilibrium_man,local,2,7,10,5,0,C,run_equilibrium_man-local-validate_solve-2-7-1...,6.709063e-07,2.000000e-14,1.000000e-15,9.404310e-03,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000002,4.317029e-08
75,run_equilibrium_man,local,2,7,15,5,0,C,run_equilibrium_man-local-validate_solve-2-7-1...,2.005107e-08,4.300000e-14,0.000000e+00,8.037581e-03,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,1.926053e-07
76,run_equilibrium_man,local,2,7,20,5,0,C,run_equilibrium_man-local-validate_solve-2-7-2...,2.208935e-07,1.560000e-13,0.000000e+00,1.622109e-03,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.658910e-07
77,run_equilibrium_man,local,2,7,25,5,0,C,run_equilibrium_man-local-validate_solve-2-7-2...,2.134065e-09,1.490000e-13,1.000000e-15,1.245906e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.635871e-07
78,run_equilibrium_man,local,2,7,30,5,0,C,run_equilibrium_man-local-validate_solve-2-7-3...,3.740528e-09,5.400000e-14,0.000000e+00,1.013898e-05,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000007,2.794750e-07
79,run_equilibrium_man,local,2,7,35,5,0,C,run_equilibrium_man-local-validate_solve-2-7-3...,3.944062e-09,1.200000e-13,1.000000e-15,8.315462e-07,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000007,2.799868e-07
80,run_equilibrium_man,local,2,7,10,5,0,M,run_equilibrium_man-local-validate_solve-2-7-1...,6.709063e-07,2.000000e-14,1.000000e-15,9.404310e-03,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000002,4.317029e-08
81,run_equilibrium_man,local,2,7,15,5,0,M,run_equilibrium_man-local-validate_solve-2-7-1...,2.005107e-08,4.300000e-14,0.000000e+00,8.037581e-03,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,1.926053e-07
82,run_equilibrium_man,local,2,7,20,5,0,M,run_equilibrium_man-local-validate_solve-2-7-2...,2.208935e-07,1.560000e-13,0.000000e+00,1.622109e-03,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.658910e-07
83,run_equilibrium_man,local,2,7,25,5,0,M,run_equilibrium_man-local-validate_solve-2-7-2...,2.134065e-09,1.490000e-13,1.000000e-15,1.245906e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.635871e-07
84,run_equilibrium_man,local,2,7,30,5,0,M,run_equilibrium_man-local-validate_solve-2-7-3...,3.740528e-09,5.400000e-14,0.000000e+00,1.013898e-05,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000007,2.794750e-07
85,run_equilibrium_man,local,2,7,35,5,0,M,run_equilibrium_man-local-validate_solve-2-7-3...,3.944062e-09,1.200000e-13,1.000000e-15,8.315462e-07,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000007,2.799868e-07
86,run_equilibrium_man_sa,local,2,7,10,5,0,C,run_equilibrium_man_sa-local-validate_solve-2-...,7.526158e-01,1.200000e-14,0.000000e+00,1.201976e-04,20,False,"[400, 400]","[0, 0]","[0, 0]",False,66.303509,1.804035e+00
87,run_equilibrium_man_sa,local,2,7,15,5,0,C,run_equilibrium_man_sa-local-validate_solve-2-...,1.038377e+00,5.600000e-14,0.000000e+00,4.412165e-05,20,False,"[400, 400]","[0, 0]","[0, 0]",False,74.278942,3.175556e+00
88,run_equilibrium_man_sa,local,2,7,20,5,0,C,run_equilibrium_man_sa-local-validate_solve-2-...,1.108708e+00,1.020000e-13,0.000000e+00,1.347907e-05,20,False,"[400, 400]","[0, 0]","[0, 0]",False,90.147517,9.913883e+00
89,run_equilibrium_man_sa,local,2,7,25,5,0,C,run_equilibrium_man_sa-local-validate_solve-2-...,1.186979e+00,1.240000e-13,1.000000e-15,8.168593e-06,20,False,"[400, 400]","[0, 0]","[0, 0]",False,91.750232,3.780317e+01
90,run_equilibrium_man_sa,local,2,7,30,5,0,C,run_equilibrium_man_sa-local-validate_solve-2-...,0.000000e+00,1.300000e-13,1.000000e-15,2.610000e-13,16,True,"[320, 320]","[0, 0]","[0, 0]",False,224.499095,9.955654e-01
91,run_equilibrium_man_sa,local,2,7,35,5,0,C,run_equilibrium_man_sa-local-validate_solve-2-...,0.000000e+00,2.060000e-13,0.000000e+00,2.610000e-13,13,True,"[260, 260]","[0, 0]","[0, 0]",False,224.497108,9.955654e-01
92,run_equilibrium_man_sa,local,2,7,10,5,0,M,run_equilibrium_man_sa-local-validate_solve-2-...,7.526158e-01,1.200000e-14,0.000000e+00,1.201976e-04,20,False,"[400, 400]","[0, 0]","[0, 0]",False,66.303509,1.804035e+00
93,run_equilibrium_man_sa,local,2,7,15,5,0,M,run_equilibrium_man_sa-local-validate_solve-2-...,1.038377e+00,5.600000e-14,0.000000e+00,4.412165e-05,20,False,"[400, 400]","[0, 0]","[0, 0]",False,74.278942,3.175556e+00

In [98]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

display(bench_time_table("cars_long"))

for system in ["local", "futhark01"]:
    for run_equi in ["run_equilibrium", "run_equilibrium_man"]:
        df = bench_time_table("cars_long")
        df = df[
            ((df["source"] == "matlab") |
             ((df["source"] == "futhark") &
              (df["val_name"] == system) &
              (df["run_equi"] == run_equi)))
        ]
        display(df)

,source,run_equi,val_name,backend,runs,n,c,abar,mean,stdev
0,futhark,run_equilibrium,futhark01,C,3,2,1,25,0.077338,0.000086
1,futhark,run_equilibrium,futhark01,M,3,2,1,25,0.065449,0.006283
2,futhark,run_equilibrium,futhark01,U,3,2,1,25,0.289159,0.000572
3,futhark,run_equilibrium,local,C,3,2,1,25,0.015431,0.000122
4,futhark,run_equilibrium,local,M,3,2,1,25,0.047325,0.014614
5,futhark,run_equilibrium_almost_full_ad,futhark01,C,3,2,1,25,0.073071,0.000068
6,futhark,run_equilibrium_almost_full_ad,futhark01,M,3,2,1,25,0.083028,0.007827
7,futhark,run_equilibrium_almost_full_ad,futhark01,U,3,2,1,25,0.285914,0.000693
8,futhark,run_equilibrium_almost_full_ad,local,C,3,2,1,25,0.014388,0.000287
9,futhark,run_equilibrium_almost_full_ad,local,M,3,2,1,25,0.038469,0.007098
10,futhark,run_equilibrium_full_ad,local,C,3,2,1,25,0.031693,0.003330
11,futhark,run_equilibrium_full_ad,local,M,3,2,1,25,0.062610,0.012917
12,futhark,run_equilibrium_full_ad_alt,local,C,3,2,1,25,0.020164,0.001232
13,futhark,run_equilibrium_full_ad_alt,local,M,3,2,1,25,0.038322,0.001186
14,futhark,run_equilibrium_man,futhark01,C,3,2,1,25,0.024319,0.000030
15,futhark,run_equilibrium_man,futhark01,M,3,2,1,25,0.058998,0.000799
16,futhark,run_equilibrium_man,futhark01,U,3,2,1,25,0.292506,0.000426
17,futhark,run_equilibrium_man,local,C,3,2,1,25,0.005668,0.000408
18,futhark,run_equilibrium_man,local,M,3,2,1,25,0.060869,0.017337
19,futhark,run_equilibrium_man_sa,local,C,3,2,1,25,0.011003,0.000173
20,futhark,run_equilibrium_man_sa,local,M,3,2,1,25,0.072842,0.021598
21,matlab,-,-,-,-,2,1,25,0.105785,0.027910
22,futhark,run_equilibrium,futhark01,C,3,2,5,25,3.934542,0.309512
23,futhark,run_equilibrium,futhark01,M,3,2,5,25,0.588528,0.044075
24,futhark,run_equilibrium,futhark01,U,3,2,5,25,1.312285,0.000909
25,futhark,run_equilibrium,local,C,3,2,5,25,1.270393,0.037300
26,futhark,run_equilibrium,local,M,3,2,5,25,0.308382,0.009547
27,futhark,run_equilibrium_almost_full_ad,futhark01,C,3,2,5,25,3.349011,0.003201
28,futhark,run_equilibrium_almost_full_ad,futhark01,M,3,2,5,25,0.637250,0.064860
29,futhark,run_equilibrium_almost_full_ad,futhark01,U,3,2,5,25,1.292245,0.000265
30,futhark,run_equilibrium_almost_full_ad,local,C,3,2,5,25,1.157584,0.014966
31,futhark,run_equilibrium_almost_full_ad,local,M,3,2,5,25,0.284802,0.005058
32,futhark,run_equilibrium_full_ad,local,C,3,2,5,25,2.402666,0.155169
33,futhark,run_equilibrium_full_ad,local,M,3,2,5,25,0.714740,0.056340
34,futhark,run_equilibrium_full_ad_alt,local,C,3,2,5,25,1.571765,0.059677
35,futhark,run_equilibrium_full_ad_alt,local,M,3,2,5,25,0.401156,0.008851
36,futhark,run_equilibrium_man,futhark01,C,3,2,5,25,0.781393,0.191018
37,futhark,run_equilibrium_man,futhark01,M,3,2,5,25,0.403040,0.016153
38,futhark,run_equilibrium_man,futhark01,U,3,2,5,25,2.378817,0.514461
39,futhark,run_equilibrium_man,local,C,3,2,5,25,0.271691,0.003122
40,futhark,run_equilibrium_man,local,M,3,2,5,25,0.217664,0.029567
41,futhark,run_equilibrium_man_sa,local,C,3,2,5,25,1.587456,0.314871
42,futhark,run_equilibrium_man_sa,local,M,3,2,5,25,0.932053,0.164469
43,matlab,-,-,-,-,2,5,25,1.754218,0.030317
44,futhark,run_equilibrium,futhark01,C,3,2,9,25,17.633968,0.075447
45,futhark,run_equilibrium,futhark01,M,3,2,9,25,1.371026,0.084310
46,futhark,run_equilibrium,futhark01,U,3,2,9,25,2.535535,0.000933
47,futhark,run_equilibrium,local,C,3,2,9,25,5.712635,0.093886
48,futhark,run_equilibrium,local,M,3,2,9,25,1.842999,0.079794
49,futhark,run_equilibrium_almost_full_ad,futhark01,C,3,2,9,25,16.428222,0.482743
50,futhark,run_equilibrium_almost_full_ad,futhark01,M,3,2,9,25,1.840060,0.031618
51,futhark,run_equilibrium_almost_full_ad,futhark01,U,3,2,9,25,2.474481,0.002746
52,futhark,run_equilibrium_almost_full_ad,local,C,3,2,9,25,5.634460,0.057806
53,futhark,run_equilibrium_almost_full_ad,local,M,3,2,9,25,1.686068,0.075000
54,futhark,run_equilibrium_full_ad,local,C,3,2,9,25,10.351677,1.322068
55,futhark,run_equilibrium_full_ad,local,M,3,2,9,25,2.670150,0.098190
56,futhark,run_equilibrium_full_ad_alt,local,C,3,2,9,25,7.370573,0.139803
57,futhark,run_equilibrium_full_ad_alt,local,M,3,2,9,25,2.018871,0.106323
58,futhark,run_equilibrium_man,futhark01,C,3,2,9,25,3.224055,0.008248
59,futhark,run_equilibrium_man,futhark01,M,3,2,9,25,1.272435,0.010355
60,futhark,run_equilibrium_man,futhark01,U,3,2,9,25,4.836228,0.023913
61,futhark,run_equilibrium_man,local,C,3,2,9,25,1.354198,0.031164
62,futhark,run_equilibrium_man,local,M,3,2,9,25,0.935198,0.064591
63,futhark,run_equilibrium_man_sa,local,C,3,2,9,25,5.717989,0.216998
64,futhark,run_equilibrium_man_sa,local,M,3,2,9,25,3.478516,0.035564
65,matlab,-,-,-,-,2,9,25,10.211754,0.054219
66,futhark,run_equilibrium,futhark01,C,3,2,13,25,54.497105,0.445599
67,futhark,run_equilibrium,futhark01,M,3,2,13,25,3.872397,0.077124
68,futhark,run_equilibrium,futhark01,U,3,2,13,25,5.183548,0.004455
69,futhark,run_equilibrium,local,C,3,2,13,25,18.838399,1.161052
70,futhark,run_equilibrium,local,M,3,2,13,25,5.590788,0.113585
71,futhark,run_equilibrium_almost_full_ad,futhark01,C,3,2,13,25,49.161078,0.461043
72,futhark,run_equilibrium_almost_full_ad,futhark01,M,3,2,13,25,4.895131,0.096433
73,futhark,run_equilibrium_almost_full_ad,futhark01,U,3,2,13,25,5.018405,0.001390
74,futhark,run_equilibrium_almost_full_ad,local,C,3,2,13,25,17.505248,0.256408
75,futhark,run_equilibrium_almost_full_ad,local,M,3,2,13,25,4.539291,0.073331
76,futhark,run_equilibrium_full_ad,local,C,3,2,13,25,31.363837,1.214048
77,futhark,run_equilibrium_full_ad,local,M,3,2,13,25,8.113052,0.573088
78,futhark,run_equilibrium_full_ad_alt,local,C,3,2,13,25,23.526333,0.349581
79,futhark,run_equilibrium_full_ad_alt,local,M,3,2,13,25,5.401614,0.223962
80,futhark,run_equilibrium_man,futhark01,C,3,2,13,25,9.978703,0.004948
81,futhark,run_equilibrium_man,futhark01,M,3,2,13,25,2.589353,0.053451
82,futhark,run_equilibrium_man,futhark01,U,3,2,13,25,9.241270,0.330094
83,futhark,run_equilibrium_man,local,C,3,2,13,25,3.870256,0.006960
84,futhark,run_equilibrium_man,local,M,3,2,13,25,2.520932,0.109756
85,futhark,run_equilibrium_man_sa,local,C,3,2,13,25,16.820068,0.060414
86,futhark,run_equilibrium_man_sa,local,M,3,2,13,25,9.552806,0.094128
87,matlab,-,-,-,-,2,13,25,33.853231,3.864335
88,futhark,run_equilibrium,futhark01,C,3,2,17,25,126.820564,1.259650
89,futhark,run_equilibrium,futhark01,M,3,2,17,25,9.221466,0.076523
90,futhark,run_equilibrium,futhark01,U,3,2,17,25,6.878315,0.004409
91,futhark,run_equilibrium,local,C,3,2,17,25,42.287842,0.384940
92,futhark,run_equilibrium,local,M,3,2,17,25,13.801242,0.162382
93,futhark,run_equilibrium_almost_full_ad,futhark01,C,3,2,17,25,112.680211,0.884286
94,futhark,run_equilibrium_almost_full_ad,futhark01,M,3,2,17,25,10.614800,0.242930
95,futhark,run_equilibrium_almost_full_ad,futhark01,U,3,2,17,25,6.646844,0.006109
96,futhark,run_equilibrium_almost_full_ad,local,C,3,2,17,25,39.185543,0.479234
97,futhark,run_equilibrium_almost_full_ad,local,M,3,2,17,25,11.145464,0.308525
98,futhark,run_equilibrium_full_ad,local,C,3,2,17,25,66.775759,1.342854
99,futhark,run_equilibrium_full_ad,local,M,3,2,17,25,19.744620,0.450399
100,futhark,run_equilibrium_full_ad_alt,local,C,3,2,17,25,58.453828,0.271068
101,futhark,run_equilibrium_full_ad_alt,local,M,3,2,17,25,13.813504,0.568665
102,futhark,run_equilibrium_man,futhark01,C,3,2,17,25,21.492664,0.134910
103,futhark,run_equilibrium_man,futhark01,M,3,2,17,25,4.572540,0.360613
104,futhark,run_equilibrium_man,futhark01,U,3,2,17,25,11.841203,0.363658
105,futhark,run_equilibrium_man,local,C,3,2,17,25,8.994878,0.260844
106,futhark,run_equilibrium_man,local,M,3,2,17,25,5.475673,0.127985
107,futhark,run_equilibrium_man_sa,local,C,3,2,17,25,41.321785,0.859462
108,futhark,run_equilibrium_man_sa,local,M,3,2,17,25,23.249297,0.959392
109,matlab,-,-,-,-,2,17,25,118.626387,9.634622
110,futhark,run_equilibrium,futhark01,C,3,2,21,25,241.287080,1.816869
111,futhark,run_equilibrium,futhark01,M,3,2,21,25,13.855926,0.826463
112,futhark,run_equilibrium,futhark01,U,3,2,21,25,10.065132,0.002027
113,futhark,run_equilibrium,local,C,3,2,21,25,79.799575,0.705347
114,futhark,run_equilibrium,local,M,3,2,21,25,27.488477,1.779575
115,futhark,run_equilibrium_almost_full_ad,futhark01,C,3,2,21,25,219.303641,0.216799
116,futhark,run_equilibrium_almost_full_ad,futhark01,M,3,2,21,25,11.938648,0.487781
117,futhark,run_equilibrium_almost_full_ad,futhark01,U,3,2,21,25,9.484229,0.009105
118,futhark,run_equilibrium_almost_full_ad,local,C,3,2,21,25,80.888549,2.554037
119,futhark,run_equilibrium_almost_full_ad,local,M,3,2,21,25,22.533856,1.503948
120,futhark,run_equilibrium_full_ad,local,C,3,2,21,25,125.627635,1.257848
121,futhark,run_equilibrium_full_ad,local,M,3,2,21,25,37.656210,0.895366
122,futhark,run_equilibrium_full_ad_alt,local,C,3,2,21,25,118.690494,0.281580
123,futhark,run_equilibrium_full_ad_alt,local,M,3,2,21,25,25.173534,0.468155
124,futhark,run_equilibrium_man,futhark01,C,3,2,21,25,44.341214,0.037179
125,futhark,run_equilibrium_man,futhark01,M,3,2,21,25,10.746129,0.170451
126,futhark,run_equilibrium_man,futhark01,U,3,2,21,25,17.243547,0.262607
127,futhark,run_equilibrium_man,local,C,3,2,21,25,17.418605,0.081673
128,futhark,run_equilibrium_man,local,M,3,2,21,25,13.173890,2.010562
129,futhark,run_equilibrium_man_sa,local,C,3,2,21,25,76.806857,3.288866
130,futhark,run_equilibrium_man_sa,local,M,3,2,21,25,125.197974,48.727548
131,matlab,-,-,-,-,2,21,25,407.037305,36.981903

,source,run_equi,val_name,backend,runs,n,c,abar,mean,stdev
3,futhark,run_equilibrium,local,C,3,2,1,25,0.015431,0.000122
4,futhark,run_equilibrium,local,M,3,2,1,25,0.047325,0.014614
21,matlab,-,-,-,-,2,1,25,0.105785,0.027910
25,futhark,run_equilibrium,local,C,3,2,5,25,1.270393,0.037300
26,futhark,run_equilibrium,local,M,3,2,5,25,0.308382,0.009547
43,matlab,-,-,-,-,2,5,25,1.754218,0.030317
47,futhark,run_equilibrium,local,C,3,2,9,25,5.712635,0.093886
48,futhark,run_equilibrium,local,M,3,2,9,25,1.842999,0.079794
65,matlab,-,-,-,-,2,9,25,10.211754,0.054219
69,futhark,run_equilibrium,local,C,3,2,13,25,18.838399,1.161052
70,futhark,run_equilibrium,local,M,3,2,13,25,5.590788,0.113585
87,matlab,-,-,-,-,2,13,25,33.853231,3.864335
91,futhark,run_equilibrium,local,C,3,2,17,25,42.287842,0.384940
92,futhark,run_equilibrium,local,M,3,2,17,25,13.801242,0.162382
109,matlab,-,-,-,-,2,17,25,118.626387,9.634622
113,futhark,run_equilibrium,local,C,3,2,21,25,79.799575,0.705347
114,futhark,run_equilibrium,local,M,3,2,21,25,27.488477,1.779575
131,matlab,-,-,-,-,2,21,25,407.037305,36.981903

,source,run_equi,val_name,backend,runs,n,c,abar,mean,stdev
17,futhark,run_equilibrium_man,local,C,3,2,1,25,0.005668,0.000408
18,futhark,run_equilibrium_man,local,M,3,2,1,25,0.060869,0.017337
21,matlab,-,-,-,-,2,1,25,0.105785,0.027910
39,futhark,run_equilibrium_man,local,C,3,2,5,25,0.271691,0.003122
40,futhark,run_equilibrium_man,local,M,3,2,5,25,0.217664,0.029567
43,matlab,-,-,-,-,2,5,25,1.754218,0.030317
61,futhark,run_equilibrium_man,local,C,3,2,9,25,1.354198,0.031164
62,futhark,run_equilibrium_man,local,M,3,2,9,25,0.935198,0.064591
65,matlab,-,-,-,-,2,9,25,10.211754,0.054219
83,futhark,run_equilibrium_man,local,C,3,2,13,25,3.870256,0.006960
84,futhark,run_equilibrium_man,local,M,3,2,13,25,2.520932,0.109756
87,matlab,-,-,-,-,2,13,25,33.853231,3.864335
105,futhark,run_equilibrium_man,local,C,3,2,17,25,8.994878,0.260844
106,futhark,run_equilibrium_man,local,M,3,2,17,25,5.475673,0.127985
109,matlab,-,-,-,-,2,17,25,118.626387,9.634622
127,futhark,run_equilibrium_man,local,C,3,2,21,25,17.418605,0.081673
128,futhark,run_equilibrium_man,local,M,3,2,21,25,13.173890,2.010562
131,matlab,-,-,-,-,2,21,25,407.037305,36.981903

,source,run_equi,val_name,backend,runs,n,c,abar,mean,stdev
0,futhark,run_equilibrium,futhark01,C,3,2,1,25,0.077338,0.000086
1,futhark,run_equilibrium,futhark01,M,3,2,1,25,0.065449,0.006283
2,futhark,run_equilibrium,futhark01,U,3,2,1,25,0.289159,0.000572
21,matlab,-,-,-,-,2,1,25,0.105785,0.027910
22,futhark,run_equilibrium,futhark01,C,3,2,5,25,3.934542,0.309512
23,futhark,run_equilibrium,futhark01,M,3,2,5,25,0.588528,0.044075
24,futhark,run_equilibrium,futhark01,U,3,2,5,25,1.312285,0.000909
43,matlab,-,-,-,-,2,5,25,1.754218,0.030317
44,futhark,run_equilibrium,futhark01,C,3,2,9,25,17.633968,0.075447
45,futhark,run_equilibrium,futhark01,M,3,2,9,25,1.371026,0.084310
46,futhark,run_equilibrium,futhark01,U,3,2,9,25,2.535535,0.000933
65,matlab,-,-,-,-,2,9,25,10.211754,0.054219
66,futhark,run_equilibrium,futhark01,C,3,2,13,25,54.497105,0.445599
67,futhark,run_equilibrium,futhark01,M,3,2,13,25,3.872397,0.077124
68,futhark,run_equilibrium,futhark01,U,3,2,13,25,5.183548,0.004455
87,matlab,-,-,-,-,2,13,25,33.853231,3.864335
88,futhark,run_equilibrium,futhark01,C,3,2,17,25,126.820564,1.259650
89,futhark,run_equilibrium,futhark01,M,3,2,17,25,9.221466,0.076523
90,futhark,run_equilibrium,futhark01,U,3,2,17,25,6.878315,0.004409
109,matlab,-,-,-,-,2,17,25,118.626387,9.634622
110,futhark,run_equilibrium,futhark01,C,3,2,21,25,241.287080,1.816869
111,futhark,run_equilibrium,futhark01,M,3,2,21,25,13.855926,0.826463
112,futhark,run_equilibrium,futhark01,U,3,2,21,25,10.065132,0.002027
131,matlab,-,-,-,-,2,21,25,407.037305,36.981903

,source,run_equi,val_name,backend,runs,n,c,abar,mean,stdev
14,futhark,run_equilibrium_man,futhark01,C,3,2,1,25,0.024319,0.000030
15,futhark,run_equilibrium_man,futhark01,M,3,2,1,25,0.058998,0.000799
16,futhark,run_equilibrium_man,futhark01,U,3,2,1,25,0.292506,0.000426
21,matlab,-,-,-,-,2,1,25,0.105785,0.027910
36,futhark,run_equilibrium_man,futhark01,C,3,2,5,25,0.781393,0.191018
37,futhark,run_equilibrium_man,futhark01,M,3,2,5,25,0.403040,0.016153
38,futhark,run_equilibrium_man,futhark01,U,3,2,5,25,2.378817,0.514461
43,matlab,-,-,-,-,2,5,25,1.754218,0.030317
58,futhark,run_equilibrium_man,futhark01,C,3,2,9,25,3.224055,0.008248
59,futhark,run_equilibrium_man,futhark01,M,3,2,9,25,1.272435,0.010355
60,futhark,run_equilibrium_man,futhark01,U,3,2,9,25,4.836228,0.023913
65,matlab,-,-,-,-,2,9,25,10.211754,0.054219
80,futhark,run_equilibrium_man,futhark01,C,3,2,13,25,9.978703,0.004948
81,futhark,run_equilibrium_man,futhark01,M,3,2,13,25,2.589353,0.053451
82,futhark,run_equilibrium_man,futhark01,U,3,2,13,25,9.241270,0.330094
87,matlab,-,-,-,-,2,13,25,33.853231,3.864335
102,futhark,run_equilibrium_man,futhark01,C,3,2,17,25,21.492664,0.134910
103,futhark,run_equilibrium_man,futhark01,M,3,2,17,25,4.572540,0.360613
104,futhark,run_equilibrium_man,futhark01,U,3,2,17,25,11.841203,0.363658
109,matlab,-,-,-,-,2,17,25,118.626387,9.634622
124,futhark,run_equilibrium_man,futhark01,C,3,2,21,25,44.341214,0.037179
125,futhark,run_equilibrium_man,futhark01,M,3,2,21,25,10.746129,0.170451
126,futhark,run_equilibrium_man,futhark01,U,3,2,21,25,17.243547,0.262607
131,matlab,-,-,-,-,2,21,25,407.037305,36.981903

##### LaTeX Table

In [99]:
def local_bench_table(variant, val_name='local'):
      """Wide table for `variant`: rows = varying parameter (c / n / abar),
      columns = (MATLAB / Futhark-C / Futhark-M) × (mean, stdev).
      Only Futhark rows whose val_name matches `val_name` are kept."""
      df = bench_time_table(variant)

      mask = (df['source'] == 'matlab') | (
          (df['source'] == 'futhark') & (df['val_name'] == val_name)
      )
      df = df[mask].copy()
      df['label'] = df.apply(
          lambda r: 'MATLAB' if r['source'] == 'matlab' else f"Futhark-{r['backend']}",
          axis=1,
      )

      var_col = {'cars': 'c', 'households': 'n', 'age': 'abar', 'cars_long': 'c'}[variant]
      pivot = df.pivot_table(index=var_col, columns='label',
                             values=['mean', 'stdev'], aggfunc='first')
      pivot = pivot.swaplevel(0, 1, axis=1)

      label_order = ['MATLAB', 'Futhark-C', 'Futhark-M']
      present = [l for l in label_order if l in pivot.columns.get_level_values(0).unique()]
      cols = [(lbl, stat) for lbl in present for stat in ['mean', 'stdev']]
      return pivot.reindex(columns=cols)

In [100]:
for v in ['cars', 'households', 'age', 'cars_long']:
      print(f"\n=== {v}: bench times (local) ===")
      tbl = local_bench_table(v)
      display(tbl)
      print(tbl.to_latex(float_format='%.4f',
                         caption=f'Equilibrium benchmark times ({v})',
                         label=f'tab:bench-{v}'))

=== cars: bench times (local) ===

label     MATLAB            Futhark-C           Futhark-M
            mean     stdev       mean     stdev      mean     stdev
c
1       0.068386  0.020576   0.015431  0.000122  0.047325  0.014614
3       0.485418  0.086544   0.330239  0.000843  0.132433  0.008728
5       1.939685  0.108326   1.270393  0.037300  0.308382  0.009547
7       7.587036  0.504120   3.311001  0.021470  0.987857  0.025682
9      11.064450  0.675593   5.712635  0.093886  1.842999  0.079794
11     19.586699  0.637146  10.658316  0.191747  3.224413  0.022561
13     30.973843  0.538623  18.838399  1.161052  5.590788  0.113585

\begin{table}
\caption{Equilibrium benchmark times (cars)}
\label{tab:bench-cars}
\begin{tabular}{lrrrrrr}
\toprule
label & \multicolumn{2}{r}{MATLAB} & \multicolumn{2}{r}{Futhark-C} & \multicolumn{2}{r}{Futhark-M} \\
 & mean & stdev & mean & stdev & mean & stdev \\
c &  &  &  &  &  &  \\
\midrule
1 & 0.0684 & 0.0206 & 0.0154 & 0.0001 & 0.0473 & 0.0146 \\
3 & 0.4854 & 0.0865 & 0.3302 & 0.0008 & 0.1324 & 0.0087 \\
5 & 1.9397 & 0.1083 & 1.2704 & 0.0373 & 0.3084 & 0.0095 \\
7 & 7.5870 & 0.5041 & 3.3110 & 0.0215 & 0.9879 & 0.0257 \\
9 & 11.0645 & 0.6756 & 5.7126 & 0.0939 & 1.8430 & 0.0798 \\
11 & 19.5867 & 0.6371 & 10.6583 & 0.1917 & 3.2244 & 0.0226 \\
13 & 30.9738 & 0.5386 & 18.8384 & 1.1611 & 5.5908 & 0.1136 \\
\bottomrule
\end{tabular}
\end{table}


=== households: bench times (local) ===

label     MATLAB           Futhark-C           Futhark-M
            mean     stdev      mean     stdev      mean     stdev
n
2       7.020355  0.190719  3.311001  0.021470  0.987857  0.025682
3       6.707738  0.021294  4.233363  0.126168  1.175821  0.058068
4       8.168758  0.021005  5.326726  0.074081  1.498123  0.075818
5      11.204162  0.043375  6.525457  0.033199  1.755546  0.090920
6      11.174867  0.044354  7.827898  0.052284  2.442221  0.205999

\begin{table}
\caption{Equilibrium benchmark times (households)}
\label{tab:bench-households}
\begin{tabular}{lrrrrrr}
\toprule
label & \multicolumn{2}{r}{MATLAB} & \multicolumn{2}{r}{Futhark-C} & \multicolumn{2}{r}{Futhark-M} \\
 & mean & stdev & mean & stdev & mean & stdev \\
n &  &  &  &  &  &  \\
\midrule
2 & 7.0204 & 0.1907 & 3.3110 & 0.0215 & 0.9879 & 0.0257 \\
3 & 6.7077 & 0.0213 & 4.2334 & 0.1262 & 1.1758 & 0.0581 \\
4 & 8.1688 & 0.0210 & 5.3267 & 0.0741 & 1.4981 & 0.0758 \\
5 & 11.2042 & 0.0434 & 6.5255 & 0.0332 & 1.7555 & 0.0909 \\
6 & 11.1749 & 0.0444 & 7.8279 & 0.0523 & 2.4422 & 0.2060 \\
\bottomrule
\end{tabular}
\end{table}


=== age: bench times (local) ===

label     MATLAB           Futhark-C           Futhark-M
            mean     stdev      mean     stdev      mean     stdev
abar
10      0.681014  0.037932  0.275749  0.007175  0.105716  0.014869
15      1.110800  0.038380  0.668816  0.003574  0.327886  0.078854
20      2.574031  0.156272  1.439351  0.025735  0.397220  0.011858
25      7.087320  0.248254  3.311001  0.021470  0.987857  0.025682
30     11.409867  0.942833  5.562934  0.027941  1.846307  0.113170
35     19.765368  0.748713  8.920049  0.068249  2.925500  0.087916

\begin{table}
\caption{Equilibrium benchmark times (age)}
\label{tab:bench-age}
\begin{tabular}{lrrrrrr}
\toprule
label & \multicolumn{2}{r}{MATLAB} & \multicolumn{2}{r}{Futhark-C} & \multicolumn{2}{r}{Futhark-M} \\
 & mean & stdev & mean & stdev & mean & stdev \\
abar &  &  &  &  &  &  \\
\midrule
10 & 0.6810 & 0.0379 & 0.2757 & 0.0072 & 0.1057 & 0.0149 \\
15 & 1.1108 & 0.0384 & 0.6688 & 0.0036 & 0.3279 & 0.0789 \\
20 & 2.5740 & 0.1563 & 1.4394 & 0.0257 & 0.3972 & 0.0119 \\
25 & 7.0873 & 0.2483 & 3.3110 & 0.0215 & 0.9879 & 0.0257 \\
30 & 11.4099 & 0.9428 & 5.5629 & 0.0279 & 1.8463 & 0.1132 \\
35 & 19.7654 & 0.7487 & 8.9200 & 0.0682 & 2.9255 & 0.0879 \\
\bottomrule
\end{tabular}
\end{table}


=== cars_long: bench times (local) ===

label      MATLAB             Futhark-C            Futhark-M
             mean      stdev       mean     stdev       mean     stdev
c
1        0.105785   0.027910   0.015431  0.000122   0.047325  0.014614
5        1.754218   0.030317   1.270393  0.037300   0.308382  0.009547
9       10.211754   0.054219   5.712635  0.093886   1.842999  0.079794
13      33.853231   3.864335  18.838399  1.161052   5.590788  0.113585
17     118.626387   9.634622  42.287842  0.384940  13.801242  0.162382
21     407.037305  36.981903  79.799575  0.705347  27.488477  1.779575

\begin{table}
\caption{Equilibrium benchmark times (cars_long)}
\label{tab:bench-cars_long}
\begin{tabular}{lrrrrrr}
\toprule
label & \multicolumn{2}{r}{MATLAB} & \multicolumn{2}{r}{Futhark-C} & \multicolumn{2}{r}{Futhark-M} \\
 & mean & stdev & mean & stdev & mean & stdev \\
c &  &  &  &  &  &  \\
\midrule
1 & 0.1058 & 0.0279 & 0.0154 & 0.0001 & 0.0473 & 0.0146 \\
5 & 1.7542 & 0.0303 & 1.2704 & 0.0373 & 0.3084 & 0.0095 \\
9 & 10.2118 & 0.0542 & 5.7126 & 0.0939 & 1.8430 & 0.0798 \\
13 & 33.8532 & 3.8643 & 18.8384 & 1.1611 & 5.5908 & 0.1136 \\
17 & 118.6264 & 9.6346 & 42.2878 & 0.3849 & 13.8012 & 0.1624 \\
21 & 407.0373 & 36.9819 & 79.7996 & 0.7053 & 27.4885 & 1.7796 \\
\bottomrule
\end{tabular}
\end{table}

##### Validation Tables

In [101]:
def _pivot_validation(variant, rename, val_name='local'):
      """Pivot validation rows for `variant`, keeping only the metrics in `rename`."""
      rows = comparison_table(variant)
      rows = rows[rows['val_name'] == val_name].copy()
      if rows.empty:
          return pd.DataFrame()

      metrics = list(rename)

      # Compact list-valued counters: [30, 30] -> '30';  [30, 33] -> '30,33'
      def compact(lst):
          return str(lst[0]) if len(set(lst)) == 1 else ','.join(map(str, lst))
      for col in {'sa_iters_tot', 'nk_iters_tot', 'rtrips_tot'} & set(metrics):
          rows[col] = rows[col].apply(compact)

      var_col = {'cars': 'c', 'households': 'n', 'age': 'abar'}[variant]
      rows['label'] = rows['run_equi'] + '-' + rows['backend']

      indexed = rows.set_index([var_col, 'label'])[metrics]
      pivot = indexed.unstack('label').rename(columns=rename, level=0)
      pivot = pivot.swaplevel(0, 1, axis=1)

      label_order = sorted(rows['label'].unique())
      cols = [(lbl, rename[m]) for lbl in label_order for m in metrics]
      return pivot.reindex(columns=cols)


def local_validation_summary(variant, val_name='local'):
    """Newton / Conv / Match per (run_equi, backend)."""
    return _pivot_validation(variant,
        {'iter': 'Newton', 'conv': 'Conv', 'within_tol': 'Match'}, val_name)


def local_validation_iters(variant, val_name='local'):
    """SA / NK / RT per (run_equi, backend)."""
    return _pivot_validation(variant,
        {'sa_iters_tot': 'SA', 'nk_iters_tot': 'NK', 'rtrips_tot': 'RT'}, val_name)

In [102]:
for v in ['cars', 'households', 'age']:
      print(f"\n=== {v}: convergence summary (local) ===")
      tbl = local_validation_summary(v)
      display(tbl)
      print(tbl.to_latex(caption=f'Convergence summary ({v})',
                         label=f'tab:val-summary-{v}'))

      print(f"\n=== {v}: iteration counts (local) ===")
      tbl = local_validation_iters(v)
      display(tbl)
      print(tbl.to_latex(caption=f'Iteration counts ({v})',
                         label=f'tab:val-iters-{v}'))

=== cars: convergence summary (local) ===

label run_equilibrium-C             run_equilibrium-M              \
                 Newton  Conv Match            Newton  Conv Match
c
1                   7.0  True  True               7.0  True  True
3                   7.0  True  True               7.0  True  True
5                   6.0  True  True               6.0  True  True
7                   6.0  True  True               6.0  True  True
9                   5.0  True  True               5.0  True  True
11                  5.0  True  True               5.0  True  True
13                  5.0  True  True               5.0  True  True
17                  5.0  True  True               5.0  True  True
21                  5.0  True  True               5.0  True  True

label run_equilibrium_almost_full_ad-C              \
                                Newton  Conv Match
c
1                                  7.0  True  True
3                                  NaN   NaN   NaN
5                                  6.0  True  True
7                                  NaN   NaN   NaN
9                                  5.0  True  True
11                                 NaN   NaN   NaN
13                                 5.0  True  True
17                                 5.0  True  True
21                                 5.0  True  True

label run_equilibrium_almost_full_ad-M             run_equilibrium_dp_solve-C  \
                                Newton  Conv Match                     Newton
c
1                                  7.0  True  True                        7.0
3                                  NaN   NaN   NaN                        7.0
5                                  6.0  True  True                        6.0
7                                  NaN   NaN   NaN                        6.0
9                                  5.0  True  True                        6.0
11                                 NaN   NaN   NaN                        5.0
13                                 5.0  True  True                        5.0
17                                 5.0  True  True                        NaN
21                                 5.0  True  True                        NaN

label             run_equilibrium_dp_solve-M              \
       Conv Match                     Newton  Conv Match
c
1      True  True                        7.0  True  True
3      True  True                        7.0  True  True
5      True  True                        6.0  True  True
7      True  True                        6.0  True  True
9      True  True                        6.0  True  True
11     True  True                        5.0  True  True
13     True  True                        5.0  True  True
17      NaN   NaN                        NaN   NaN   NaN
21      NaN   NaN                        NaN   NaN   NaN

label run_equilibrium_full_ad-C             run_equilibrium_full_ad-M        \
                         Newton  Conv Match                    Newton  Conv
c
1                           7.0  True  True                       7.0  True
3                           8.0  True  True                       8.0  True
5                           7.0  True  True                       7.0  True
7                           7.0  True  True                       7.0  True
9                           6.0  True  True                       6.0  True
11                          6.0  True  True                       6.0  True
13                          6.0  True  True                       6.0  True
17                          5.0  True  True                       5.0  True
21                          5.0  True  True                       5.0  True

label       run_equilibrium_full_ad_alt-C              \
      Match                        Newton  Conv Match
c
1      True                           7.0  True  True
3      True                           NaN   NaN   NaN
5      True                           6.0  True  True
7      True                           NaN   NaN   NaN
9      True                           5.0  True  True
11     True                           NaN   NaN   NaN
13     True                           5.0  True  True
17     True                           5.0  True  True
21     True                           5.0  True  True

label run_equilibrium_full_ad_alt-M             run_equilibrium_man-C        \
                             Newton  Conv Match                Newton  Conv
c
1                               7.0  True  True                   7.0  True
3                               NaN   NaN   NaN                   7.0  True
5                               6.0  True  True                   6.0  True
7                               NaN   NaN   NaN                   6.0  True
9                               5.0  True  True                   5.0  True
11                              NaN   NaN   NaN                   5.0  True
13                              5.0  True  True                   5.0  True
17                              5.0  True  True                   5.0  True
21                              5.0  True  True                   5.0  True

label       run_equilibrium_man-M             run_equilibrium_man_sa-C         \
      Match                Newton  Conv Match                   Newton   Conv
c
1      True                   7.0  True  True                     14.0   True
3      True                   7.0  True  True                     20.0  False
5      True                   6.0  True  True                     20.0  False
7      True                   6.0  True  True                     20.0  False
9      True                   5.0  True  True                     20.0  False
11     True                   5.0  True  True                     20.0  False
13     True                   5.0  True  True                     20.0  False
17     True                   5.0  True  True                     20.0  False
21     True                   5.0  True  True                     20.0  False

label        run_equilibrium_man_sa-M               run_equilibrium_sa-C  \
       Match                   Newton   Conv  Match               Newton
c
1      False                     14.0   True  False                  7.0
3      False                     20.0  False  False                  8.0
5      False                     20.0  False  False                  7.0
7      False                     20.0  False  False                  7.0
9      False                     20.0  False  False                  6.0
11     False                     20.0  False  False                  6.0
13     False                     20.0  False  False                  6.0
17     False                     20.0  False  False                  NaN
21     False                     20.0  False  False                  NaN

label             run_equilibrium_sa-M
       Conv Match               Newton  Conv Match
c
1      True  True                  7.0  True  True
3      True  True                  8.0  True  True
5      True  True                  7.0  True  True
7      True  True                  7.0  True  True
9      True  True                  6.0  True  True
11     True  True                  6.0  True  True
13     True  True                  6.0  True  True
17      NaN   NaN                  NaN   NaN   NaN
21      NaN   NaN                  NaN   NaN   NaN

\begin{table}
\caption{Convergence summary (cars)}
\label{tab:val-summary-cars}
\begin{tabular}{lrllrllrllrllrllrllrllrllrllrllrllrllrllrllrllrll}
\toprule
label & \multicolumn{3}{r}{run_equilibrium-C} & \multicolumn{3}{r}{run_equilibrium-M} & \multicolumn{3}{r}{run_equilibrium_almost_full_ad-C} & \multicolumn{3}{r}{run_equilibrium_almost_full_ad-M} & \multicolumn{3}{r}{run_equilibrium_dp_solve-C} & \multicolumn{3}{r}{run_equilibrium_dp_solve-M} & \multicolumn{3}{r}{run_equilibrium_full_ad-C} & \multicolumn{3}{r}{run_equilibrium_full_ad-M} & \multicolumn{3}{r}{run_equilibrium_full_ad_alt-C} & \multicolumn{3}{r}{run_equilibrium_full_ad_alt-M} & \multicolumn{3}{r}{run_equilibrium_man-C} & \multicolumn{3}{r}{run_equilibrium_man-M} & \multicolumn{3}{r}{run_equilibrium_man_sa-C} & \multicolumn{3}{r}{run_equilibrium_man_sa-M} & \multicolumn{3}{r}{run_equilibrium_sa-C} & \multicolumn{3}{r}{run_equilibrium_sa-M} \\
 & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match \\
c &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
\midrule
1 & 7.000000 & True & True & 7.000000 & True & True & 7.000000 & True & True & 7.000000 & True & True & 7.000000 & True & True & 7.000000 & True & True & 7.000000 & True & True & 7.000000 & True & True & 7.000000 & True & True & 7.000000 & True & True & 7.000000 & True & True & 7.000000 & True & True & 14.000000 & True & False & 14.000000 & True & False & 7.000000 & True & True & 7.000000 & True & True \\
3 & 7.000000 & True & True & 7.000000 & True & True & NaN & NaN & NaN & NaN & NaN & NaN & 7.000000 & True & True & 7.000000 & True & True & 8.000000 & True & True & 8.000000 & True & True & NaN & NaN & NaN & NaN & NaN & NaN & 7.000000 & True & True & 7.000000 & True & True & 20.000000 & False & False & 20.000000 & False & False & 8.000000 & True & True & 8.000000 & True & True \\
5 & 6.000000 & True & True & 6.000000 & True & True & 6.000000 & True & True & 6.000000 & True & True & 6.000000 & True & True & 6.000000 & True & True & 7.000000 & True & True & 7.000000 & True & True & 6.000000 & True & True & 6.000000 & True & True & 6.000000 & True & True & 6.000000 & True & True & 20.000000 & False & False & 20.000000 & False & False & 7.000000 & True & True & 7.000000 & True & True \\
7 & 6.000000 & True & True & 6.000000 & True & True & NaN & NaN & NaN & NaN & NaN & NaN & 6.000000 & True & True & 6.000000 & True & True & 7.000000 & True & True & 7.000000 & True & True & NaN & NaN & NaN & NaN & NaN & NaN & 6.000000 & True & True & 6.000000 & True & True & 20.000000 & False & False & 20.000000 & False & False & 7.000000 & True & True & 7.000000 & True & True \\
9 & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 6.000000 & True & True & 6.000000 & True & True & 6.000000 & True & True & 6.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 20.000000 & False & False & 20.000000 & False & False & 6.000000 & True & True & 6.000000 & True & True \\
11 & 5.000000 & True & True & 5.000000 & True & True & NaN & NaN & NaN & NaN & NaN & NaN & 5.000000 & True & True & 5.000000 & True & True & 6.000000 & True & True & 6.000000 & True & True & NaN & NaN & NaN & NaN & NaN & NaN & 5.000000 & True & True & 5.000000 & True & True & 20.000000 & False & False & 20.000000 & False & False & 6.000000 & True & True & 6.000000 & True & True \\
13 & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 6.000000 & True & True & 6.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 20.000000 & False & False & 20.000000 & False & False & 6.000000 & True & True & 6.000000 & True & True \\
17 & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & NaN & NaN & NaN & NaN & NaN & NaN & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 20.000000 & False & False & 20.000000 & False & False & NaN & NaN & NaN & NaN & NaN & NaN \\
21 & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & NaN & NaN & NaN & NaN & NaN & NaN & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 5.000000 & True & True & 20.000000 & False & False & 20.000000 & False & False & NaN & NaN & NaN & NaN & NaN & NaN \\
\bottomrule
\end{tabular}
\end{table}


=== cars: iteration counts (local) ===

label run_equilibrium-C          run_equilibrium-M           \
                     SA    NK RT                SA    NK RT
c
1                 30,33  12,7  7             30,33  12,7  7
3                    28     7  7                28     7  7
5                    24     6  6                24     6  6
7                    24     6  6                24     6  6
9                    20     5  5                20     5  5
11                   20     5  5                20     5  5
13                   20     5  5                20     5  5
17                   20     5  5                20     5  5
21                   20     5  5                20     5  5

label run_equilibrium_almost_full_ad-C             \
                                    SA    NK   RT
c
1                                30,33  12,7    7
3                                  NaN   NaN  NaN
5                                   24     6    6
7                                  NaN   NaN  NaN
9                                   20     5    5
11                                 NaN   NaN  NaN
13                                  20     5    5
17                                  20     5    5
21                                  20     5    5

label run_equilibrium_almost_full_ad-M            run_equilibrium_dp_solve-C  \
                                    SA    NK   RT                         SA
c
1                                30,33  12,7    7                         -1
3                                  NaN   NaN  NaN                         -1
5                                   24     6    6                         -1
7                                  NaN   NaN  NaN                         -1
9                                   20     5    5                         -1
11                                 NaN   NaN  NaN                         -1
13                                  20     5    5                         -1
17                                  20     5    5                        NaN
21                                  20     5    5                        NaN

label           run_equilibrium_dp_solve-M            \
        NK   RT                         SA   NK   RT
c
1       -1   -1                         -1   -1   -1
3       -1   -1                         -1   -1   -1
5       -1   -1                         -1   -1   -1
7       -1   -1                         -1   -1   -1
9       -1   -1                         -1   -1   -1
11      -1   -1                         -1   -1   -1
13      -1   -1                         -1   -1   -1
17     NaN  NaN                        NaN  NaN  NaN
21     NaN  NaN                        NaN  NaN  NaN

label run_equilibrium_full_ad-C          run_equilibrium_full_ad-M           \
                             SA    NK RT                        SA    NK RT
c
1                         30,33  12,7  7                     30,33  12,7  7
3                            32     8  8                        32     8  8
5                            28     7  7                        28     7  7
7                            28     7  7                        28     7  7
9                            24     6  6                        24     6  6
11                           24     6  6                        24     6  6
13                           24     6  6                        24     6  6
17                           20     5  5                        20     5  5
21                           20     5  5                        20     5  5

label run_equilibrium_full_ad_alt-C            run_equilibrium_full_ad_alt-M  \
                                 SA    NK   RT                            SA
c
1                             30,33  12,7    7                         30,33
3                               NaN   NaN  NaN                           NaN
5                                24     6    6                            24
7                               NaN   NaN  NaN                           NaN
9                                20     5    5                            20
11                              NaN   NaN  NaN                           NaN
13                               20     5    5                            20
17                               20     5    5                            20
21                               20     5    5                            20

label            run_equilibrium_man-C          run_equilibrium_man-M        \
         NK   RT                    SA    NK RT                    SA    NK
c
1      12,7    7                 30,33  12,7  7                 30,33  12,7
3       NaN  NaN                    28     7  7                    28     7
5         6    6                    24     6  6                    24     6
7       NaN  NaN                    24     6  6                    24     6
9         5    5                    20     5  5                    20     5
11      NaN  NaN                    20     5  5                    20     5
13        5    5                    20     5  5                    20     5
17        5    5                    20     5  5                    20     5
21        5    5                    20     5  5                    20     5

label    run_equilibrium_man_sa-C       run_equilibrium_man_sa-M        \
      RT                       SA NK RT                       SA NK RT
c
1      7                      280  0  0                      280  0  0
3      7                      400  0  0                      400  0  0
5      6                      400  0  0                      400  0  0
7      6                      400  0  0                      400  0  0
9      5                      400  0  0                      400  0  0
11     5                      400  0  0                      400  0  0
13     5                      400  0  0                      400  0  0
17     5                      400  0  0                      400  0  0
21     5                      400  0  0                      400  0  0

label run_equilibrium_sa-C           run_equilibrium_sa-M
                        SA   NK   RT                   SA   NK   RT
c
1                3349,3219    0    0            3349,3219    0    0
3                3866,3729    0    0            3866,3729    0    0
5                3396,3282    0    0            3396,3282    0    0
7                3403,3295    0    0            3403,3295    0    0
9                2923,2834    0    0            2923,2834    0    0
11               2924,2840    0    0            2924,2840    0    0
13               2929,2842    0    0            2929,2842    0    0
17                     NaN  NaN  NaN                  NaN  NaN  NaN
21                     NaN  NaN  NaN                  NaN  NaN  NaN

\begin{table}
\caption{Iteration counts (cars)}
\label{tab:val-iters-cars}
\begin{tabular}{lllllllllllllllllllllllllllllllllllllllllllllllll}
\toprule
label & \multicolumn{3}{r}{run_equilibrium-C} & \multicolumn{3}{r}{run_equilibrium-M} & \multicolumn{3}{r}{run_equilibrium_almost_full_ad-C} & \multicolumn{3}{r}{run_equilibrium_almost_full_ad-M} & \multicolumn{3}{r}{run_equilibrium_dp_solve-C} & \multicolumn{3}{r}{run_equilibrium_dp_solve-M} & \multicolumn{3}{r}{run_equilibrium_full_ad-C} & \multicolumn{3}{r}{run_equilibrium_full_ad-M} & \multicolumn{3}{r}{run_equilibrium_full_ad_alt-C} & \multicolumn{3}{r}{run_equilibrium_full_ad_alt-M} & \multicolumn{3}{r}{run_equilibrium_man-C} & \multicolumn{3}{r}{run_equilibrium_man-M} & \multicolumn{3}{r}{run_equilibrium_man_sa-C} & \multicolumn{3}{r}{run_equilibrium_man_sa-M} & \multicolumn{3}{r}{run_equilibrium_sa-C} & \multicolumn{3}{r}{run_equilibrium_sa-M} \\
 & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT \\
c &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
\midrule
1 & 30,33 & 12,7 & 7 & 30,33 & 12,7 & 7 & 30,33 & 12,7 & 7 & 30,33 & 12,7 & 7 & -1 & -1 & -1 & -1 & -1 & -1 & 30,33 & 12,7 & 7 & 30,33 & 12,7 & 7 & 30,33 & 12,7 & 7 & 30,33 & 12,7 & 7 & 30,33 & 12,7 & 7 & 30,33 & 12,7 & 7 & 280 & 0 & 0 & 280 & 0 & 0 & 3349,3219 & 0 & 0 & 3349,3219 & 0 & 0 \\
3 & 28 & 7 & 7 & 28 & 7 & 7 & NaN & NaN & NaN & NaN & NaN & NaN & -1 & -1 & -1 & -1 & -1 & -1 & 32 & 8 & 8 & 32 & 8 & 8 & NaN & NaN & NaN & NaN & NaN & NaN & 28 & 7 & 7 & 28 & 7 & 7 & 400 & 0 & 0 & 400 & 0 & 0 & 3866,3729 & 0 & 0 & 3866,3729 & 0 & 0 \\
5 & 24 & 6 & 6 & 24 & 6 & 6 & 24 & 6 & 6 & 24 & 6 & 6 & -1 & -1 & -1 & -1 & -1 & -1 & 28 & 7 & 7 & 28 & 7 & 7 & 24 & 6 & 6 & 24 & 6 & 6 & 24 & 6 & 6 & 24 & 6 & 6 & 400 & 0 & 0 & 400 & 0 & 0 & 3396,3282 & 0 & 0 & 3396,3282 & 0 & 0 \\
7 & 24 & 6 & 6 & 24 & 6 & 6 & NaN & NaN & NaN & NaN & NaN & NaN & -1 & -1 & -1 & -1 & -1 & -1 & 28 & 7 & 7 & 28 & 7 & 7 & NaN & NaN & NaN & NaN & NaN & NaN & 24 & 6 & 6 & 24 & 6 & 6 & 400 & 0 & 0 & 400 & 0 & 0 & 3403,3295 & 0 & 0 & 3403,3295 & 0 & 0 \\
9 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & -1 & -1 & -1 & -1 & -1 & -1 & 24 & 6 & 6 & 24 & 6 & 6 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & 400 & 0 & 0 & 400 & 0 & 0 & 2923,2834 & 0 & 0 & 2923,2834 & 0 & 0 \\
11 & 20 & 5 & 5 & 20 & 5 & 5 & NaN & NaN & NaN & NaN & NaN & NaN & -1 & -1 & -1 & -1 & -1 & -1 & 24 & 6 & 6 & 24 & 6 & 6 & NaN & NaN & NaN & NaN & NaN & NaN & 20 & 5 & 5 & 20 & 5 & 5 & 400 & 0 & 0 & 400 & 0 & 0 & 2924,2840 & 0 & 0 & 2924,2840 & 0 & 0 \\
13 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & -1 & -1 & -1 & -1 & -1 & -1 & 24 & 6 & 6 & 24 & 6 & 6 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & 400 & 0 & 0 & 400 & 0 & 0 & 2929,2842 & 0 & 0 & 2929,2842 & 0 & 0 \\
17 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & NaN & NaN & NaN & NaN & NaN & NaN & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & 400 & 0 & 0 & 400 & 0 & 0 & NaN & NaN & NaN & NaN & NaN & NaN \\
21 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & NaN & NaN & NaN & NaN & NaN & NaN & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & 400 & 0 & 0 & 400 & 0 & 0 & NaN & NaN & NaN & NaN & NaN & NaN \\
\bottomrule
\end{tabular}
\end{table}


=== households: convergence summary (local) ===

label run_equilibrium-C             run_equilibrium-M              \
                 Newton  Conv Match            Newton  Conv Match
n
2                     6  True  True                 6  True  True
3                     5  True  True                 5  True  True
4                     5  True  True                 5  True  True
5                     5  True  True                 5  True  True
6                     5  True  True                 5  True  True

label run_equilibrium_dp_solve-C             run_equilibrium_dp_solve-M        \
                          Newton  Conv Match                     Newton  Conv
n
2                              6  True  True                          6  True
3                              5  True  True                          5  True
4                              5  True  True                          5  True
5                              5  True  True                          5  True
6                              5  True  True                          5  True

label       run_equilibrium_full_ad-C             run_equilibrium_full_ad-M  \
      Match                    Newton  Conv Match                    Newton
n
2      True                         7  True  True                         7
3      True                         6  True  True                         6
4      True                         6  True  True                         6
5      True                         5  True  True                         5
6      True                         5  True  True                         5

label             run_equilibrium_man-C             run_equilibrium_man-M  \
       Conv Match                Newton  Conv Match                Newton
n
2      True  True                     6  True  True                     6
3      True  True                     5  True  True                     5
4      True  True                     5  True  True                     5
5      True  True                     5  True  True                     5
6      True  True                     5  True  True                     5

label             run_equilibrium_man_sa-C                \
       Conv Match                   Newton   Conv  Match
n
2      True  True                       20  False  False
3      True  True                       20  False  False
4      True  True                       20  False  False
5      True  True                       20  False  False
6      True  True                       20  False  False

label run_equilibrium_man_sa-M               run_equilibrium_sa-C              \
                        Newton   Conv  Match               Newton  Conv Match
n
2                           20  False  False                    7  True  True
3                           20  False  False                    6  True  True
4                           20  False  False                    6  True  True
5                           20  False  False                    5  True  True
6                           20  False  False                    5  True  True

label run_equilibrium_sa-M
                    Newton  Conv Match
n
2                        7  True  True
3                        6  True  True
4                        6  True  True
5                        5  True  True
6                        5  True  True

\begin{table}
\caption{Convergence summary (households)}
\label{tab:val-summary-households}
\begin{tabular}{lrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr}
\toprule
label & \multicolumn{3}{r}{run_equilibrium-C} & \multicolumn{3}{r}{run_equilibrium-M} & \multicolumn{3}{r}{run_equilibrium_dp_solve-C} & \multicolumn{3}{r}{run_equilibrium_dp_solve-M} & \multicolumn{3}{r}{run_equilibrium_full_ad-C} & \multicolumn{3}{r}{run_equilibrium_full_ad-M} & \multicolumn{3}{r}{run_equilibrium_man-C} & \multicolumn{3}{r}{run_equilibrium_man-M} & \multicolumn{3}{r}{run_equilibrium_man_sa-C} & \multicolumn{3}{r}{run_equilibrium_man_sa-M} & \multicolumn{3}{r}{run_equilibrium_sa-C} & \multicolumn{3}{r}{run_equilibrium_sa-M} \\
 & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match \\
n &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
\midrule
2 & 6 & True & True & 6 & True & True & 6 & True & True & 6 & True & True & 7 & True & True & 7 & True & True & 6 & True & True & 6 & True & True & 20 & False & False & 20 & False & False & 7 & True & True & 7 & True & True \\
3 & 5 & True & True & 5 & True & True & 5 & True & True & 5 & True & True & 6 & True & True & 6 & True & True & 5 & True & True & 5 & True & True & 20 & False & False & 20 & False & False & 6 & True & True & 6 & True & True \\
4 & 5 & True & True & 5 & True & True & 5 & True & True & 5 & True & True & 6 & True & True & 6 & True & True & 5 & True & True & 5 & True & True & 20 & False & False & 20 & False & False & 6 & True & True & 6 & True & True \\
5 & 5 & True & True & 5 & True & True & 5 & True & True & 5 & True & True & 5 & True & True & 5 & True & True & 5 & True & True & 5 & True & True & 20 & False & False & 20 & False & False & 5 & True & True & 5 & True & True \\
6 & 5 & True & True & 5 & True & True & 5 & True & True & 5 & True & True & 5 & True & True & 5 & True & True & 5 & True & True & 5 & True & True & 20 & False & False & 20 & False & False & 5 & True & True & 5 & True & True \\
\bottomrule
\end{tabular}
\end{table}


=== households: iteration counts (local) ===

label run_equilibrium-C       run_equilibrium-M        \
                     SA NK RT                SA NK RT
n
2                    24  6  6                24  6  6
3                    20  5  5                20  5  5
4                    20  5  5                20  5  5
5                    20  5  5                20  5  5
6                    20  5  5                20  5  5

label run_equilibrium_dp_solve-C         run_equilibrium_dp_solve-M          \
                              SA  NK  RT                         SA  NK  RT
n
2                             -1  -1  -1                         -1  -1  -1
3                             -1  -1  -1                         -1  -1  -1
4                             -1  -1  -1                         -1  -1  -1
5                             -1  -1  -1                         -1  -1  -1
6                             -1  -1  -1                         -1  -1  -1

label run_equilibrium_full_ad-C       run_equilibrium_full_ad-M        \
                             SA NK RT                        SA NK RT
n
2                            28  7  7                        28  7  7
3                            24  6  6                        24  6  6
4                            24  6  6                        24  6  6
5                            20  5  5                        20  5  5
6                            20  5  5                        20  5  5

label run_equilibrium_man-C       run_equilibrium_man-M        \
                         SA NK RT                    SA NK RT
n
2                        24  6  6                    24  6  6
3                        20  5  5                    20  5  5
4                        20  5  5                    20  5  5
5                        20  5  5                    20  5  5
6                        20  5  5                    20  5  5

label run_equilibrium_man_sa-C       run_equilibrium_man_sa-M        \
                            SA NK RT                       SA NK RT
n
2                          400  0  0                      400  0  0
3                          400  0  0                      400  0  0
4                          400  0  0                      400  0  0
5                          400  0  0                      400  0  0
6                          400  0  0                      400  0  0

label           run_equilibrium_sa-C                 run_equilibrium_sa-M     \
                                  SA NK RT                             SA NK
n
2                          3403,3295  0  0                      3403,3295  0
3                     2918,2806,2806  0  0                 2918,2806,2806  0
4                2922,2798,2798,2798  0  0            2922,2798,2798,2798  0
5           2435,2327,2327,2327,2327  0  0       2435,2327,2327,2327,2327  0
6      2435,2324,2324,2324,2324,2324  0  0  2435,2324,2324,2324,2324,2324  0

label
      RT
n
2      0
3      0
4      0
5      0
6      0

\begin{table}
\caption{Iteration counts (households)}
\label{tab:val-iters-households}
\begin{tabular}{lllllllllllllllllllllllllllllllllllll}
\toprule
label & \multicolumn{3}{r}{run_equilibrium-C} & \multicolumn{3}{r}{run_equilibrium-M} & \multicolumn{3}{r}{run_equilibrium_dp_solve-C} & \multicolumn{3}{r}{run_equilibrium_dp_solve-M} & \multicolumn{3}{r}{run_equilibrium_full_ad-C} & \multicolumn{3}{r}{run_equilibrium_full_ad-M} & \multicolumn{3}{r}{run_equilibrium_man-C} & \multicolumn{3}{r}{run_equilibrium_man-M} & \multicolumn{3}{r}{run_equilibrium_man_sa-C} & \multicolumn{3}{r}{run_equilibrium_man_sa-M} & \multicolumn{3}{r}{run_equilibrium_sa-C} & \multicolumn{3}{r}{run_equilibrium_sa-M} \\
 & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT \\
n &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
\midrule
2 & 24 & 6 & 6 & 24 & 6 & 6 & -1 & -1 & -1 & -1 & -1 & -1 & 28 & 7 & 7 & 28 & 7 & 7 & 24 & 6 & 6 & 24 & 6 & 6 & 400 & 0 & 0 & 400 & 0 & 0 & 3403,3295 & 0 & 0 & 3403,3295 & 0 & 0 \\
3 & 20 & 5 & 5 & 20 & 5 & 5 & -1 & -1 & -1 & -1 & -1 & -1 & 24 & 6 & 6 & 24 & 6 & 6 & 20 & 5 & 5 & 20 & 5 & 5 & 400 & 0 & 0 & 400 & 0 & 0 & 2918,2806,2806 & 0 & 0 & 2918,2806,2806 & 0 & 0 \\
4 & 20 & 5 & 5 & 20 & 5 & 5 & -1 & -1 & -1 & -1 & -1 & -1 & 24 & 6 & 6 & 24 & 6 & 6 & 20 & 5 & 5 & 20 & 5 & 5 & 400 & 0 & 0 & 400 & 0 & 0 & 2922,2798,2798,2798 & 0 & 0 & 2922,2798,2798,2798 & 0 & 0 \\
5 & 20 & 5 & 5 & 20 & 5 & 5 & -1 & -1 & -1 & -1 & -1 & -1 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & 400 & 0 & 0 & 400 & 0 & 0 & 2435,2327,2327,2327,2327 & 0 & 0 & 2435,2327,2327,2327,2327 & 0 & 0 \\
6 & 20 & 5 & 5 & 20 & 5 & 5 & -1 & -1 & -1 & -1 & -1 & -1 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & 20 & 5 & 5 & 400 & 0 & 0 & 400 & 0 & 0 & 2435,2324,2324,2324,2324,2324 & 0 & 0 & 2435,2324,2324,2324,2324,2324 & 0 & 0 \\
\bottomrule
\end{tabular}
\end{table}


=== age: convergence summary (local) ===

label run_equilibrium-C             run_equilibrium-M              \
                 Newton  Conv Match            Newton  Conv Match
abar
10                    5  True  True                 5  True  True
15                    5  True  True                 5  True  True
20                    5  True  True                 5  True  True
25                    6  True  True                 6  True  True
30                    6  True  True                 6  True  True
35                    6  True  True                 6  True  True

label run_equilibrium_dp_solve-C             run_equilibrium_dp_solve-M        \
                          Newton  Conv Match                     Newton  Conv
abar
10                             5  True  True                          5  True
15                             5  True  True                          5  True
20                             5  True  True                          5  True
25                             6  True  True                          6  True
30                             6  True  True                          6  True
35                             6  True  True                          6  True

label       run_equilibrium_full_ad-C             run_equilibrium_full_ad-M  \
      Match                    Newton  Conv Match                    Newton
abar
10     True                         6  True  True                         6
15     True                         6  True  True                         6
20     True                         6  True  True                         6
25     True                         7  True  True                         7
30     True                         7  True  True                         7
35     True                         7  True  True                         7

label             run_equilibrium_man-C             run_equilibrium_man-M  \
       Conv Match                Newton  Conv Match                Newton
abar
10     True  True                     5  True  True                     5
15     True  True                     5  True  True                     5
20     True  True                     5  True  True                     5
25     True  True                     6  True  True                     6
30     True  True                     6  True  True                     6
35     True  True                     6  True  True                     6

label             run_equilibrium_man_sa-C                \
       Conv Match                   Newton   Conv  Match
abar
10     True  True                       20  False  False
15     True  True                       20  False  False
20     True  True                       20  False  False
25     True  True                       20  False  False
30     True  True                       16   True  False
35     True  True                       13   True  False

label run_equilibrium_man_sa-M               run_equilibrium_sa-C              \
                        Newton   Conv  Match               Newton  Conv Match
abar
10                          20  False  False                    6  True  True
15                          20  False  False                    6  True  True
20                          20  False  False                    6  True  True
25                          20  False  False                    7  True  True
30                          16   True  False                    7  True  True
35                          13   True  False                    7  True  True

label run_equilibrium_sa-M
                    Newton  Conv Match
abar
10                       6  True  True
15                       6  True  True
20                       6  True  True
25                       7  True  True
30                       7  True  True
35                       7  True  True

\begin{table}
\caption{Convergence summary (age)}
\label{tab:val-summary-age}
\begin{tabular}{lrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr}
\toprule
label & \multicolumn{3}{r}{run_equilibrium-C} & \multicolumn{3}{r}{run_equilibrium-M} & \multicolumn{3}{r}{run_equilibrium_dp_solve-C} & \multicolumn{3}{r}{run_equilibrium_dp_solve-M} & \multicolumn{3}{r}{run_equilibrium_full_ad-C} & \multicolumn{3}{r}{run_equilibrium_full_ad-M} & \multicolumn{3}{r}{run_equilibrium_man-C} & \multicolumn{3}{r}{run_equilibrium_man-M} & \multicolumn{3}{r}{run_equilibrium_man_sa-C} & \multicolumn{3}{r}{run_equilibrium_man_sa-M} & \multicolumn{3}{r}{run_equilibrium_sa-C} & \multicolumn{3}{r}{run_equilibrium_sa-M} \\
 & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match & Newton & Conv & Match \\
abar &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
\midrule
10 & 5 & True & True & 5 & True & True & 5 & True & True & 5 & True & True & 6 & True & True & 6 & True & True & 5 & True & True & 5 & True & True & 20 & False & False & 20 & False & False & 6 & True & True & 6 & True & True \\
15 & 5 & True & True & 5 & True & True & 5 & True & True & 5 & True & True & 6 & True & True & 6 & True & True & 5 & True & True & 5 & True & True & 20 & False & False & 20 & False & False & 6 & True & True & 6 & True & True \\
20 & 5 & True & True & 5 & True & True & 5 & True & True & 5 & True & True & 6 & True & True & 6 & True & True & 5 & True & True & 5 & True & True & 20 & False & False & 20 & False & False & 6 & True & True & 6 & True & True \\
25 & 6 & True & True & 6 & True & True & 6 & True & True & 6 & True & True & 7 & True & True & 7 & True & True & 6 & True & True & 6 & True & True & 20 & False & False & 20 & False & False & 7 & True & True & 7 & True & True \\
30 & 6 & True & True & 6 & True & True & 6 & True & True & 6 & True & True & 7 & True & True & 7 & True & True & 6 & True & True & 6 & True & True & 16 & True & False & 16 & True & False & 7 & True & True & 7 & True & True \\
35 & 6 & True & True & 6 & True & True & 6 & True & True & 6 & True & True & 7 & True & True & 7 & True & True & 6 & True & True & 6 & True & True & 13 & True & False & 13 & True & False & 7 & True & True & 7 & True & True \\
\bottomrule
\end{tabular}
\end{table}


=== age: iteration counts (local) ===

label run_equilibrium-C       run_equilibrium-M        \
                     SA NK RT                SA NK RT
abar
10                   20  5  5                20  5  5
15                   20  5  5                20  5  5
20                   20  5  5                20  5  5
25                   24  6  6                24  6  6
30                   24  6  6                24  6  6
35                   24  6  6                24  6  6

label run_equilibrium_dp_solve-C         run_equilibrium_dp_solve-M          \
                              SA  NK  RT                         SA  NK  RT
abar
10                            -1  -1  -1                         -1  -1  -1
15                            -1  -1  -1                         -1  -1  -1
20                            -1  -1  -1                         -1  -1  -1
25                            -1  -1  -1                         -1  -1  -1
30                            -1  -1  -1                         -1  -1  -1
35                            -1  -1  -1                         -1  -1  -1

label run_equilibrium_full_ad-C       run_equilibrium_full_ad-M        \
                             SA NK RT                        SA NK RT
abar
10                           24  6  6                        24  6  6
15                           24  6  6                        24  6  6
20                           24  6  6                        24  6  6
25                           28  7  7                        28  7  7
30                           28  7  7                        28  7  7
35                           28  7  7                        28  7  7

label run_equilibrium_man-C       run_equilibrium_man-M        \
                         SA NK RT                    SA NK RT
abar
10                       20  5  5                    20  5  5
15                       20  5  5                    20  5  5
20                       20  5  5                    20  5  5
25                       24  6  6                    24  6  6
30                       24  6  6                    24  6  6
35                       24  6  6                    24  6  6

label run_equilibrium_man_sa-C       run_equilibrium_man_sa-M        \
                            SA NK RT                       SA NK RT
abar
10                         400  0  0                      400  0  0
15                         400  0  0                      400  0  0
20                         400  0  0                      400  0  0
25                         400  0  0                      400  0  0
30                         320  0  0                      320  0  0
35                         260  0  0                      260  0  0

label run_equilibrium_sa-C       run_equilibrium_sa-M
                        SA NK RT                   SA NK RT
abar
10               2909,2666  0  0            2909,2666  0  0
15               2917,2785  0  0            2917,2785  0  0
20               2917,2821  0  0            2917,2821  0  0
25               3403,3295  0  0            3403,3295  0  0
30               3403,3295  0  0            3403,3295  0  0
35               3403,3295  0  0            3403,3295  0  0

\begin{table}
\caption{Iteration counts (age)}
\label{tab:val-iters-age}
\begin{tabular}{lllllllllllllllllllllllllllllllllllll}
\toprule
label & \multicolumn{3}{r}{run_equilibrium-C} & \multicolumn{3}{r}{run_equilibrium-M} & \multicolumn{3}{r}{run_equilibrium_dp_solve-C} & \multicolumn{3}{r}{run_equilibrium_dp_solve-M} & \multicolumn{3}{r}{run_equilibrium_full_ad-C} & \multicolumn{3}{r}{run_equilibrium_full_ad-M} & \multicolumn{3}{r}{run_equilibrium_man-C} & \multicolumn{3}{r}{run_equilibrium_man-M} & \multicolumn{3}{r}{run_equilibrium_man_sa-C} & \multicolumn{3}{r}{run_equilibrium_man_sa-M} & \multicolumn{3}{r}{run_equilibrium_sa-C} & \multicolumn{3}{r}{run_equilibrium_sa-M} \\
 & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT & SA & NK & RT \\
abar &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  &  \\
\midrule
10 & 20 & 5 & 5 & 20 & 5 & 5 & -1 & -1 & -1 & -1 & -1 & -1 & 24 & 6 & 6 & 24 & 6 & 6 & 20 & 5 & 5 & 20 & 5 & 5 & 400 & 0 & 0 & 400 & 0 & 0 & 2909,2666 & 0 & 0 & 2909,2666 & 0 & 0 \\
15 & 20 & 5 & 5 & 20 & 5 & 5 & -1 & -1 & -1 & -1 & -1 & -1 & 24 & 6 & 6 & 24 & 6 & 6 & 20 & 5 & 5 & 20 & 5 & 5 & 400 & 0 & 0 & 400 & 0 & 0 & 2917,2785 & 0 & 0 & 2917,2785 & 0 & 0 \\
20 & 20 & 5 & 5 & 20 & 5 & 5 & -1 & -1 & -1 & -1 & -1 & -1 & 24 & 6 & 6 & 24 & 6 & 6 & 20 & 5 & 5 & 20 & 5 & 5 & 400 & 0 & 0 & 400 & 0 & 0 & 2917,2821 & 0 & 0 & 2917,2821 & 0 & 0 \\
25 & 24 & 6 & 6 & 24 & 6 & 6 & -1 & -1 & -1 & -1 & -1 & -1 & 28 & 7 & 7 & 28 & 7 & 7 & 24 & 6 & 6 & 24 & 6 & 6 & 400 & 0 & 0 & 400 & 0 & 0 & 3403,3295 & 0 & 0 & 3403,3295 & 0 & 0 \\
30 & 24 & 6 & 6 & 24 & 6 & 6 & -1 & -1 & -1 & -1 & -1 & -1 & 28 & 7 & 7 & 28 & 7 & 7 & 24 & 6 & 6 & 24 & 6 & 6 & 320 & 0 & 0 & 320 & 0 & 0 & 3403,3295 & 0 & 0 & 3403,3295 & 0 & 0 \\
35 & 24 & 6 & 6 & 24 & 6 & 6 & -1 & -1 & -1 & -1 & -1 & -1 & 28 & 7 & 7 & 28 & 7 & 7 & 24 & 6 & 6 & 24 & 6 & 6 & 260 & 0 & 0 & 260 & 0 & 0 & 3403,3295 & 0 & 0 & 3403,3295 & 0 & 0 \\
\bottomrule
\end{tabular}
\end{table}

In [103]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

display(comparison_table("cars"))

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

,run_equi,val_name,n,c,abar,acc0,trans,backend,filename,max_abs_ed,stat_res,norm_err,min_q,iter,conv,sa_iters_tot,nk_iters_tot,rtrips_tot,within_tol,max_abs_diff,max_rel_diff
0,run_equilibrium,3_local_new,2,1,25,5,0,C,run_equilibrium-3_local_new-validate_solve-2-1...,1.776060e-10,3.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041376e-07
1,run_equilibrium,3_local_new,2,3,25,5,0,C,run_equilibrium-3_local_new-validate_solve-2-3...,1.500000e-14,5.300000e-14,0.000000e+00,2.429617e-04,8,True,"[32, 32]","[8, 8]","[8, 8]",True,0.000004,1.298640e-07
2,run_equilibrium,3_local_new,2,5,25,5,0,C,run_equilibrium-3_local_new-validate_solve-2-5...,1.199000e-12,3.700000e-14,1.000000e-15,1.645633e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,2.444766e-07
3,run_equilibrium,3_local_new,2,7,25,5,0,C,run_equilibrium-3_local_new-validate_solve-2-7...,9.000000e-14,2.500000e-13,0.000000e+00,1.245906e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635894e-07
4,run_equilibrium,3_local_new,2,9,25,5,0,C,run_equilibrium-3_local_new-validate_solve-2-9...,1.601310e-10,1.190000e-13,1.000000e-15,1.002891e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.857835e-07
5,run_equilibrium,3_local_new,2,11,25,5,0,C,run_equilibrium-3_local_new-validate_solve-2-1...,1.488700e-11,3.640000e-13,1.000000e-15,8.393742e-05,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.817334e-07
6,run_equilibrium,3_local_new,2,13,25,5,0,C,run_equilibrium-3_local_new-validate_solve-2-1...,3.034000e-12,2.380000e-13,1.000000e-15,7.217770e-05,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.614682e-07
7,run_equilibrium,3_local_new,2,1,25,5,0,M,run_equilibrium-3_local_new-validate_solve-2-1...,1.776060e-10,6.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041376e-07
8,run_equilibrium,3_local_new,2,3,25,5,0,M,run_equilibrium-3_local_new-validate_solve-2-3...,1.500000e-14,5.300000e-14,0.000000e+00,2.429617e-04,8,True,"[32, 32]","[8, 8]","[8, 8]",True,0.000004,1.298640e-07
9,run_equilibrium,3_local_new,2,5,25,5,0,M,run_equilibrium-3_local_new-validate_solve-2-5...,1.199000e-12,3.700000e-14,1.000000e-15,1.645633e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,2.444766e-07
10,run_equilibrium,3_local_new,2,7,25,5,0,M,run_equilibrium-3_local_new-validate_solve-2-7...,9.000000e-14,2.500000e-13,0.000000e+00,1.245906e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635894e-07
11,run_equilibrium,3_local_new,2,9,25,5,0,M,run_equilibrium-3_local_new-validate_solve-2-9...,1.601310e-10,1.190000e-13,1.000000e-15,1.002891e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.857835e-07
12,run_equilibrium,3_local_new,2,11,25,5,0,M,run_equilibrium-3_local_new-validate_solve-2-1...,1.488700e-11,3.640000e-13,1.000000e-15,8.393742e-05,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.817334e-07
13,run_equilibrium,3_local_new,2,13,25,5,0,M,run_equilibrium-3_local_new-validate_solve-2-1...,3.034000e-12,2.380000e-13,1.000000e-15,7.217770e-05,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.614682e-07
14,run_equilibrium,futhark01,2,1,25,5,0,C,run_equilibrium-futhark01-validate_solve-2-1-2...,1.776050e-10,6.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041376e-07
15,run_equilibrium,futhark01,2,3,25,5,0,C,run_equilibrium-futhark01-validate_solve-2-3-2...,2.800000e-14,6.400000e-14,1.000000e-15,2.429617e-04,8,True,"[32, 32]","[8, 8]","[8, 8]",True,0.000004,1.298642e-07
16,run_equilibrium,futhark01,2,5,25,5,0,C,run_equilibrium-futhark01-validate_solve-2-5-2...,8.164651e-08,4.400000e-14,1.000000e-15,1.645633e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,2.442028e-07
17,run_equilibrium,futhark01,2,7,25,5,0,C,run_equilibrium-futhark01-validate_solve-2-7-2...,1.170000e-13,9.000000e-14,0.000000e+00,1.245906e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635888e-07
18,run_equilibrium,futhark01,2,9,25,5,0,C,run_equilibrium-futhark01-validate_solve-2-9-2...,7.078428e-07,1.310000e-13,0.000000e+00,1.002891e-04,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.696208e-07
19,run_equilibrium,futhark01,2,11,25,5,0,C,run_equilibrium-futhark01-validate_solve-2-11-...,1.488600e-11,2.320000e-13,0.000000e+00,8.393742e-05,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.817315e-07
20,run_equilibrium,futhark01,2,13,25,5,0,C,run_equilibrium-futhark01-validate_solve-2-13-...,9.993377e-08,3.360000e-13,1.000000e-15,7.217770e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.608359e-07
21,run_equilibrium,futhark01,2,17,25,5,0,C,run_equilibrium-futhark01-validate_solve-2-17-...,1.153871e-07,9.900000e-14,0.000000e+00,5.638751e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,3.015387e-07
22,run_equilibrium,futhark01,2,21,25,5,0,C,run_equilibrium-futhark01-validate_solve-2-21-...,1.140144e-07,9.070000e-13,0.000000e+00,4.626974e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,2.334436e-07
23,run_equilibrium,futhark01,2,1,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-1-2...,1.776050e-10,6.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041376e-07
24,run_equilibrium,futhark01,2,3,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-3-2...,2.800000e-14,6.400000e-14,1.000000e-15,2.429617e-04,8,True,"[32, 32]","[8, 8]","[8, 8]",True,0.000004,1.298642e-07
25,run_equilibrium,futhark01,2,5,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-5-2...,8.164651e-08,4.400000e-14,1.000000e-15,1.645633e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,2.442028e-07
26,run_equilibrium,futhark01,2,7,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-7-2...,1.760000e-13,4.900000e-14,0.000000e+00,1.245906e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635900e-07
27,run_equilibrium,futhark01,2,9,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-9-2...,7.078428e-07,1.940000e-13,0.000000e+00,1.002891e-04,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.696205e-07
28,run_equilibrium,futhark01,2,11,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-11-...,1.488700e-11,2.800000e-13,0.000000e+00,8.393742e-05,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.817310e-07
29,run_equilibrium,futhark01,2,13,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-13-...,9.993377e-08,3.620000e-13,0.000000e+00,7.217770e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.608369e-07
30,run_equilibrium,futhark01,2,17,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-17-...,1.153871e-07,1.010000e-13,0.000000e+00,5.638751e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,3.015367e-07
31,run_equilibrium,futhark01,2,21,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-21-...,1.140144e-07,4.150000e-13,0.000000e+00,4.626974e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,2.334428e-07
32,run_equilibrium,futhark01,2,25,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-25-...,1.075137e-07,2.140000e-13,0.000000e+00,3.923198e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
33,run_equilibrium,futhark01,2,29,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-29-...,9.986430e-08,7.860000e-13,1.000000e-15,3.405317e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
34,run_equilibrium,futhark01,2,33,25,5,0,M,run_equilibrium-futhark01-validate_solve-2-33-...,9.241465e-08,3.590000e-13,0.000000e+00,3.008252e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
35,run_equilibrium,futhark01,2,1,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-1-2...,1.776050e-10,3.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041376e-07
36,run_equilibrium,futhark01,2,3,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-3-2...,2.500000e-14,1.900000e-14,0.000000e+00,2.429617e-04,8,True,"[32, 32]","[8, 8]","[8, 8]",True,0.000004,1.298642e-07
37,run_equilibrium,futhark01,2,5,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-5-2...,8.164651e-08,8.000000e-15,0.000000e+00,1.645633e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,2.442024e-07
38,run_equilibrium,futhark01,2,7,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-7-2...,2.500000e-14,9.800000e-14,0.000000e+00,1.245906e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.635889e-07
39,run_equilibrium,futhark01,2,9,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-9-2...,7.078428e-07,4.600000e-14,0.000000e+00,1.002891e-04,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.696213e-07
40,run_equilibrium,futhark01,2,11,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-11-...,3.838900e-11,9.200000e-14,0.000000e+00,8.393742e-05,9,True,"[36, 36]","[9, 9]","[9, 9]",True,0.000004,1.815439e-07
41,run_equilibrium,futhark01,2,13,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-13-...,1.640648e-07,1.320000e-13,0.000000e+00,7.217768e-05,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000041,4.329165e-06
42,run_equilibrium,futhark01,2,17,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-17-...,5.149398e-07,4.180000e-13,1.000000e-15,5.638832e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000787,6.281871e-05
43,run_equilibrium,futhark01,2,21,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-21-...,6.759107e-07,2.630000e-13,0.000000e+00,4.627704e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",False,0.005926,3.140754e-04
44,run_equilibrium,futhark01,2,25,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-25-...,3.956094e-07,4.020000e-13,0.000000e+00,3.923579e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
45,run_equilibrium,futhark01,2,29,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-29-...,2.498612e-07,1.004000e-12,1.000000e-15,3.405534e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
46,run_equilibrium,futhark01,2,33,25,5,0,U,run_equilibrium-futhark01-validate_solve-2-33-...,4.838467e-08,5.420000e-13,0.000000e+00,3.008261e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
47,run_equilibrium,local,2,1,25,5,0,C,run_equilibrium-local-validate_solve-2-1-25-5-...,1.776060e-10,3.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041376e-07
48,run_equilibrium,local,2,3,25,5,0,C,run_equilibrium-local-validate_solve-2-3-25-5-...,6.159482e-09,2.800000e-14,0.000000e+00,2.429617e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.298638e-07
49,run_equilibrium,local,2,5,25,5,0,C,run_equilibrium-local-validate_solve-2-5-25-5-...,8.164651e-08,1.700000e-14,0.000000e+00,1.645633e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,2.442022e-07
50,run_equilibrium,local,2,7,25,5,0,C,run_equilibrium-local-validate_solve-2-7-25-5-...,2.134065e-09,1.610000e-13,1.000000e-15,1.245906e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.635885e-07
51,run_equilibrium,local,2,9,25,5,0,C,run_equilibrium-local-validate_solve-2-9-25-5-...,7.078428e-07,2.040000e-13,1.000000e-15,1.002891e-04,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.696210e-07
52,run_equilibrium,local,2,11,25,5,0,C,run_equilibrium-local-validate_solve-2-11-25-5...,1.947470e-07,1.460000e-13,0.000000e+00,8.393742e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.777388e-07
53,run_equilibrium,local,2,13,25,5,0,C,run_equilibrium-local-validate_solve-2-13-25-5...,9.993377e-08,2.350000e-13,0.000000e+00,7.217770e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.608386e-07
54,run_equilibrium,local,2,17,25,5,0,C,run_equilibrium-local-validate_solve-2-17-25-5...,1.153871e-07,3.220000e-13,0.000000e+00,5.638751e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,3.015375e-07
55,run_equilibrium,local,2,21,25,5,0,C,run_equilibrium-local-validate_solve-2-21-25-5...,1.140144e-07,4.010000e-13,1.000000e-15,4.626974e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,2.334411e-07
56,run_equilibrium,local,2,1,25,5,0,M,run_equilibrium-local-validate_solve-2-1-25-5-...,1.776060e-10,8.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041376e-07
57,run_equilibrium,local,2,3,25,5,0,M,run_equilibrium-local-validate_solve-2-3-25-5-...,6.159482e-09,2.800000e-14,0.000000e+00,2.429617e-04,7,True,"[28, 28]","[7, 7]","[7, 7]",True,0.000004,1.298638e-07
58,run_equilibrium,local,2,5,25,5,0,M,run_equilibrium-local-validate_solve-2-5-25-5-...,8.164651e-08,1.700000e-14,0.000000e+00,1.645633e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,2.442022e-07
59,run_equilibrium,local,2,7,25,5,0,M,run_equilibrium-local-validate_solve-2-7-25-5-...,2.134065e-09,1.610000e-13,1.000000e-15,1.245906e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,1.635885e-07
60,run_equilibrium,local,2,9,25,5,0,M,run_equilibrium-local-validate_solve-2-9-25-5-...,7.078428e-07,2.040000e-13,1.000000e-15,1.002891e-04,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.696210e-07
61,run_equilibrium,local,2,11,25,5,0,M,run_equilibrium-local-validate_solve-2-11-25-5...,1.947470e-07,1.460000e-13,0.000000e+00,8.393742e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.777388e-07
62,run_equilibrium,local,2,13,25,5,0,M,run_equilibrium-local-validate_solve-2-13-25-5...,9.993377e-08,2.350000e-13,0.000000e+00,7.217770e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.608386e-07
63,run_equilibrium,local,2,17,25,5,0,M,run_equilibrium-local-validate_solve-2-17-25-5...,1.153871e-07,3.220000e-13,0.000000e+00,5.638751e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,3.015375e-07
64,run_equilibrium,local,2,21,25,5,0,M,run_equilibrium-local-validate_solve-2-21-25-5...,1.140144e-07,4.010000e-13,0.000000e+00,4.626974e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,2.334411e-07
65,run_equilibrium_almost_full_ad,futhark01,2,1,25,5,0,C,run_equilibrium_almost_full_ad-futhark01-valid...,1.776060e-10,7.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041376e-07
66,run_equilibrium_almost_full_ad,futhark01,2,5,25,5,0,C,run_equilibrium_almost_full_ad-futhark01-valid...,8.164651e-08,7.100000e-14,0.000000e+00,1.645633e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,2.442025e-07
67,run_equilibrium_almost_full_ad,futhark01,2,9,25,5,0,C,run_equilibrium_almost_full_ad-futhark01-valid...,7.078428e-07,7.800000e-14,0.000000e+00,1.002891e-04,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.696217e-07
68,run_equilibrium_almost_full_ad,futhark01,2,13,25,5,0,C,run_equilibrium_almost_full_ad-futhark01-valid...,9.993377e-08,1.850000e-13,0.000000e+00,7.217770e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.608380e-07
69,run_equilibrium_almost_full_ad,futhark01,2,17,25,5,0,C,run_equilibrium_almost_full_ad-futhark01-valid...,1.153871e-07,3.050000e-13,0.000000e+00,5.638751e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,3.015356e-07
70,run_equilibrium_almost_full_ad,futhark01,2,21,25,5,0,C,run_equilibrium_almost_full_ad-futhark01-valid...,1.140144e-07,2.740000e-13,0.000000e+00,4.626974e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,2.334410e-07
71,run_equilibrium_almost_full_ad,futhark01,2,1,25,5,0,M,run_equilibrium_almost_full_ad-futhark01-valid...,1.776060e-10,7.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041376e-07
72,run_equilibrium_almost_full_ad,futhark01,2,5,25,5,0,M,run_equilibrium_almost_full_ad-futhark01-valid...,8.164651e-08,7.100000e-14,1.000000e-15,1.645633e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,2.442025e-07
73,run_equilibrium_almost_full_ad,futhark01,2,9,25,5,0,M,run_equilibrium_almost_full_ad-futhark01-valid...,7.078428e-07,7.800000e-14,0.000000e+00,1.002891e-04,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.696217e-07
74,run_equilibrium_almost_full_ad,futhark01,2,13,25,5,0,M,run_equilibrium_almost_full_ad-futhark01-valid...,9.993377e-08,3.080000e-13,0.000000e+00,7.217770e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.608393e-07
75,run_equilibrium_almost_full_ad,futhark01,2,17,25,5,0,M,run_equilibrium_almost_full_ad-futhark01-valid...,1.153871e-07,2.210000e-13,0.000000e+00,5.638751e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,3.015375e-07
76,run_equilibrium_almost_full_ad,futhark01,2,21,25,5,0,M,run_equilibrium_almost_full_ad-futhark01-valid...,1.140144e-07,7.950000e-13,1.000000e-15,4.626974e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,2.334419e-07
77,run_equilibrium_almost_full_ad,futhark01,2,25,25,5,0,M,run_equilibrium_almost_full_ad-futhark01-valid...,1.075137e-07,8.580000e-13,1.000000e-15,3.923198e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
78,run_equilibrium_almost_full_ad,futhark01,2,29,25,5,0,M,run_equilibrium_almost_full_ad-futhark01-valid...,9.986430e-08,1.075000e-12,0.000000e+00,3.405317e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
79,run_equilibrium_almost_full_ad,futhark01,2,33,25,5,0,M,run_equilibrium_almost_full_ad-futhark01-valid...,9.241464e-08,2.100000e-13,1.000000e-15,3.008252e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
80,run_equilibrium_almost_full_ad,futhark01,2,1,25,5,0,U,run_equilibrium_almost_full_ad-futhark01-valid...,1.776060e-10,4.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041377e-07
81,run_equilibrium_almost_full_ad,futhark01,2,5,25,5,0,U,run_equilibrium_almost_full_ad-futhark01-valid...,8.164651e-08,3.300000e-14,0.000000e+00,1.645633e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,2.442028e-07
82,run_equilibrium_almost_full_ad,futhark01,2,9,25,5,0,U,run_equilibrium_almost_full_ad-futhark01-valid...,7.078428e-07,1.190000e-13,0.000000e+00,1.002891e-04,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.696213e-07
83,run_equilibrium_almost_full_ad,futhark01,2,13,25,5,0,U,run_equilibrium_almost_full_ad-futhark01-valid...,1.640648e-07,1.940000e-13,0.000000e+00,7.217768e-05,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000041,4.329165e-06
84,run_equilibrium_almost_full_ad,futhark01,2,17,25,5,0,U,run_equilibrium_almost_full_ad-futhark01-valid...,5.149398e-07,1.390000e-13,0.000000e+00,5.638832e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000787,6.281871e-05
85,run_equilibrium_almost_full_ad,futhark01,2,21,25,5,0,U,run_equilibrium_almost_full_ad-futhark01-valid...,6.759107e-07,6.440000e-13,0.000000e+00,4.627704e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",False,0.005926,3.140754e-04
86,run_equilibrium_almost_full_ad,futhark01,2,25,25,5,0,U,run_equilibrium_almost_full_ad-futhark01-valid...,3.956094e-07,2.340000e-13,0.000000e+00,3.923579e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
87,run_equilibrium_almost_full_ad,futhark01,2,29,25,5,0,U,run_equilibrium_almost_full_ad-futhark01-valid...,2.498612e-07,1.329000e-12,1.000000e-15,3.405534e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
88,run_equilibrium_almost_full_ad,futhark01,2,33,25,5,0,U,run_equilibrium_almost_full_ad-futhark01-valid...,4.838467e-08,9.140000e-13,1.000000e-15,3.008261e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",None,NaN,NaN
89,run_equilibrium_almost_full_ad,local,2,1,25,5,0,C,run_equilibrium_almost_full_ad-local-validate_...,1.776060e-10,4.000000e-15,0.000000e+00,4.725005e-04,7,True,"[30, 33]","[12, 7]","[7, 7]",True,0.000002,1.041376e-07
90,run_equilibrium_almost_full_ad,local,2,5,25,5,0,C,run_equilibrium_almost_full_ad-local-validate_...,8.164651e-08,4.200000e-14,0.000000e+00,1.645633e-04,6,True,"[24, 24]","[6, 6]","[6, 6]",True,0.000004,2.442032e-07
91,run_equilibrium_almost_full_ad,local,2,9,25,5,0,C,run_equilibrium_almost_full_ad-local-validate_...,7.078428e-07,6.800000e-14,0.000000e+00,1.002891e-04,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.696219e-07
92,run_equilibrium_almost_full_ad,local,2,13,25,5,0,C,run_equilibrium_almost_full_ad-local-validate_...,9.993377e-08,3.090000e-13,0.000000e+00,7.217770e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000004,1.608364e-07
93,run_equilibrium_almost_full_ad,local,2,17,25,5,0,C,run_equilibrium_almost_full_ad-local-validate_...,1.153871e-07,2.240000e-13,0.000000e+00,5.638751e-05,5,True,"[20, 20]","[5, 5]","[5, 5]",True,0.000005,3.015358e-07

In [ ]:
SYSTEMS = ["local", "futhark01", "futhark03"]
RUN_EQUIS = ["run_equilibrium", "run_equilibrium_man", "run_equilibrium_full_ad"]
BACKEND_ORDER = {"C": 0, "M": 1, "U": 2, "O": 3}

def _iter_range(x):
    x = pd.Series(x).dropna().astype(int)
    if x.empty:
        return ""
    lo, hi = x.min(), x.max()
    return str(lo) if lo == hi else f"{lo}--{hi}"


def validation_summary_selected(variant="cars"):
    """
    Summarise validation results for local/futhark01/futhark03 and
    run_equilibrium / run_equilibrium_man / run_equilibrium_full_ad.

    For car scaling, use variant='cars'. This includes the extended c values
    such as 17 and 21, since cars_long is only separate for benchmark files.
    """
    df = comparison_table(variant)
    df = df[
        df["val_name"].isin(SYSTEMS)
        & df["run_equi"].isin(RUN_EQUIS)
    ].copy()

    out = (
        df.groupby(["val_name", "run_equi", "backend"], as_index=False)
          .agg(
              configs=("filename", "count"),
              all_converged=("conv", "all"),
              max_abs_diff=("max_abs_diff", "max"),
              max_abs_ed=("max_abs_ed", "max"),
              max_stat_res=("stat_res", "max"),
              max_norm_err=("norm_err", "max"),
              min_q=("min_q", "min"),
              newton_iters=("iter", _iter_range),
          )
    )

    out["val_name"] = pd.Categorical(out["val_name"], SYSTEMS, ordered=True)
    out["run_equi"] = pd.Categorical(out["run_equi"], RUN_EQUIS, ordered=True)
    out["backend_order"] = out["backend"].map(BACKEND_ORDER).fillna(99)

    return (
        out.sort_values(["val_name", "run_equi", "backend_order"])
           .drop(columns=["backend_order"])
           .reset_index(drop=True)
    )


def validation_details_selected(variant="cars"):
    """
    Detailed validation rows for local/futhark01/futhark03 and
    run_equilibrium / run_equilibrium_man / run_equilibrium_full_ad.
    """
    df = comparison_table(variant)
    df = df[
        df["val_name"].isin(SYSTEMS)
        & df["run_equi"].isin(RUN_EQUIS)
    ].copy()

    sort_col = {"cars": "c", "households": "n", "age": "abar"}[variant]
    df["val_name"] = pd.Categorical(df["val_name"], SYSTEMS, ordered=True)
    df["run_equi"] = pd.Categorical(df["run_equi"], RUN_EQUIS, ordered=True)
    df["backend_order"] = df["backend"].map(BACKEND_ORDER).fillna(99)

    cols = [
        "val_name", "run_equi", "backend",
        "n", "c", "abar", "acc0", "trans",
        "conv", "iter",
        "max_abs_diff", "max_abs_ed", "stat_res", "norm_err", "min_q",
        "sa_iters_tot", "nk_iters_tot", "rtrips_tot",
        "filename",
    ]

    return (
        df.sort_values(["val_name", "run_equi", "backend_order", sort_col])
          .drop(columns=["backend_order"])
          [cols]
          .reset_index(drop=True)
    )


def benchmark_selected(variant="cars_long"):
    """
    Benchmark rows for local/futhark01/futhark03 and
    run_equilibrium / run_equilibrium_man / run_equilibrium_full_ad.

    Use variant='cars_long', 'cars_longer', or 'cars_longest'
    for the car-scaling benchmarks.
    """
    df = bench_time_table(variant)

    mask = (
        (df["source"] == "matlab")
        | (
            (df["source"] == "futhark")
            & df["val_name"].isin(SYSTEMS)
            & df["run_equi"].isin(RUN_EQUIS)
        )
    )

    df = df[mask].copy()

    sort_col = {
        "cars": "c",
        "cars_long": "c",
        "cars_longer": "c",
        "cars_longest": "c",
        "households": "n",
        "age": "abar",
    }[variant]

    df["val_name"] = pd.Categorical(df["val_name"], ["-", *SYSTEMS], ordered=True)
    df["run_equi"] = pd.Categorical(df["run_equi"], ["-", *RUN_EQUIS], ordered=True)
    df["backend_order"] = df["backend"].map(BACKEND_ORDER).fillna(99)

    return (
        df.sort_values([sort_col, "source", "val_name", "run_equi", "backend_order"])
          .drop(columns=["backend_order"])
          .reset_index(drop=True)
    )


pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

print("=== Validation summary: selected systems and solvers ===")
display(validation_summary_selected("cars"))

print("=== Validation details: selected systems and solvers ===")
display(validation_details_selected("cars"))

for variant in ["cars_long", "cars_longer", "cars_longest"]:
    print(f"=== Benchmark results: selected systems and solvers ({variant}) ===")
    display(benchmark_selected(variant))

In [105]:
CAR_VARIANT_PRIORITY = {
    "cars_long": 0,
    "cars_longer": 1,
    "cars_longest": 2,
}

def combined_car_benchmarks_prefer_latest():
    dfs = []
    for variant in ["cars_long", "cars_longer", "cars_longest"]:
        df = bench_time_table(variant).copy()
        if not df.empty:
            df["variant"] = variant
            df["variant_priority"] = CAR_VARIANT_PRIORITY[variant]
            dfs.append(df)

    if not dfs:
        return pd.DataFrame()

    df = pd.concat(dfs, ignore_index=True)

    # For the same configuration, keep the result from the latest / most precise variant.
    key_cols = ["source", "run_equi", "val_name", "backend", "n", "c", "abar"]
    df = (
        df.sort_values("variant_priority")
          .drop_duplicates(subset=key_cols, keep="last")
          .drop(columns=["variant_priority"])
          .reset_index(drop=True)
    )

    return df


def benchcell_tex(runtime, speedup=None):
    if pd.isna(runtime):
        return ""
    if speedup is None or pd.isna(speedup):
        return f"{runtime:.3f}"
    return rf"\benchcell{{{runtime:.3f}}}{{{speedup:.1f}}}"


def make_futhark01_common_table():
    df = combined_car_benchmarks_prefer_latest()
    df = df[df["c"].isin([1, 5, 9, 13, 17, 21])].copy()

    df = df[
        (df["source"].eq("matlab"))
        |
        (
            df["source"].eq("futhark")
            & df["val_name"].eq("futhark01")
            & df["run_equi"].isin(["run_equilibrium", "run_equilibrium_man"])
            & df["backend"].isin(["C", "M", "U"])
        )
    ].copy()

    matlab = df[df["source"].eq("matlab")].set_index("c")["mean"].rename("MATLAB")

    futhark = df[df["source"].eq("futhark")].copy()
    futhark["label"] = futhark.apply(
        lambda r:
            "Base-C" if r["run_equi"] == "run_equilibrium" and r["backend"] == "C" else
            "Base-M" if r["run_equi"] == "run_equilibrium" and r["backend"] == "M" else
            "Base-CUDA" if r["run_equi"] == "run_equilibrium" and r["backend"] == "U" else
            "Manual-C" if r["run_equi"] == "run_equilibrium_man" and r["backend"] == "C" else
            "Manual-M" if r["run_equi"] == "run_equilibrium_man" and r["backend"] == "M" else
            "Manual-CUDA" if r["run_equi"] == "run_equilibrium_man" and r["backend"] == "U" else
            None,
        axis=1,
    )

    wide = futhark.pivot_table(index="c", columns="label", values="mean", aggfunc="first")
    wide = wide.join(matlab, how="outer")
    wide = wide.reindex(columns=["MATLAB", "Base-C", "Base-M", "Base-CUDA", "Manual-C", "Manual-M", "Manual-CUDA"])
    wide = wide.sort_index()

    lines = [
        r"\begin{table}[H]",
        r"\caption{\texttt{futhark01} car-type benchmark}",
        r"\label{tab:bench-cars-long-futhark01}",
        r"\centering",
        r"\scriptsize",
        r"\renewcommand{\arraystretch}{1.15}",
        r"\begin{tabular}{rccccccc}",
        r"\hline",
        r"Car types & MATLAB & Base-C & Base-M & Base-CUDA & Manual-C & Manual-M & Manual-CUDA \\",
        r"\hline",
    ]

    for c, row in wide.iterrows():
        matlab_time = row["MATLAB"]
        cells = [str(int(c)), f"{matlab_time:.3f}" if pd.notna(matlab_time) else ""]
        for col in ["Base-C", "Base-M", "Base-CUDA", "Manual-C", "Manual-M", "Manual-CUDA"]:
            runtime = row[col]
            speedup = matlab_time / runtime if pd.notna(matlab_time) and pd.notna(runtime) else None
            cells.append(benchcell_tex(runtime, speedup))
        lines.append(" & ".join(cells) + r" \\")

    lines += [
        r"\hline",
        r"\end{tabular}",
        "",
        r"\begin{flushleft}",
        r"\footnotesize",
        r"\textit{Note:} Mean equilibrium-solver runtimes in seconds for \texttt{futhark01}. Speedup relative to MATLAB on \texttt{futhark01} for the same number of car types is shown below each runtime in parentheses. MATLAB runtimes are averaged over 10 benchmark runs. Futhark C-backend runtimes are averaged over 3 runs, while Futhark multicore and CUDA runtimes are averaged over 6 runs where available. The benchmark uses two household types and maximal age 25. Base denotes the AD-based implementation, while Manual denotes the implementation using manually derived derivatives.",
        r"\end{flushleft}",
        r"\end{table}",
    ]

    return "\n".join(lines)


def make_futhark01_extended_table():
    df = combined_car_benchmarks_prefer_latest()
    df = df[df["c"] > 21].copy()

    df = df[
        df["source"].eq("futhark")
        & df["val_name"].eq("futhark01")
        & df["run_equi"].isin(["run_equilibrium", "run_equilibrium_man"])
        & df["backend"].isin(["M", "U"])
    ].copy()

    futhark = df.copy()
    futhark["label"] = futhark.apply(
        lambda r:
            "Base-M" if r["run_equi"] == "run_equilibrium" and r["backend"] == "M" else
            "Base-CUDA" if r["run_equi"] == "run_equilibrium" and r["backend"] == "U" else
            "Manual-M" if r["run_equi"] == "run_equilibrium_man" and r["backend"] == "M" else
            "Manual-CUDA" if r["run_equi"] == "run_equilibrium_man" and r["backend"] == "U" else
            None,
        axis=1,
    )

    wide = futhark.pivot_table(index="c", columns="label", values="mean", aggfunc="first")
    wide = wide.reindex(columns=["Base-M", "Base-CUDA", "Manual-M", "Manual-CUDA"])
    wide = wide.sort_index()

    lines = [
        r"\begin{table}[H]",
        r"\caption{Extended \texttt{futhark01} car-type benchmark}",
        r"\label{tab:bench-cars-extended-futhark01}",
        r"\centering",
        r"\small",
        r"\renewcommand{\arraystretch}{1.15}",
        r"\begin{tabular}{rcccc}",
        r"\hline",
        r"Car types & Base-M & Base-CUDA & Manual-M & Manual-CUDA \\",
        r"\hline",
    ]

    for c, row in wide.iterrows():
        cells = [str(int(c))]
        for col in ["Base-M", "Base-CUDA", "Manual-M", "Manual-CUDA"]:
            cells.append(f"{row[col]:.3f}" if pd.notna(row[col]) else "")
        lines.append(" & ".join(cells) + r" \\")

    lines += [
        r"\hline",
        r"\end{tabular}",
        "",
        r"\begin{flushleft}",
        r"\footnotesize",
        r"\textit{Note:} Mean equilibrium-solver runtimes in seconds for the extended \texttt{futhark01} benchmark. These runs include only the multicore and CUDA backends for car-type configurations larger than those included in Table~\ref{tab:bench-cars-long-futhark01}. Each reported runtime is averaged over 6 benchmark runs. The benchmark uses two household types and maximal age 25. Base denotes the AD-based implementation, while Manual denotes the implementation using manually derived derivatives.",
        r"\end{flushleft}",
        r"\end{table}",
    ]

    return "\n".join(lines)


print(make_futhark01_common_table())
print("\n\n")
print(make_futhark01_extended_table())

\begin{table}[H]
\caption{\texttt{futhark01} car-type benchmark}
\label{tab:bench-cars-long-futhark01}
\centering
\scriptsize
\renewcommand{\arraystretch}{1.15}
\begin{tabular}{rccccccc}
\hline
Car types & MATLAB & Base-C & Base-M & Base-CUDA & Manual-C & Manual-M & Manual-CUDA \\
\hline
1 & 0.106 & \benchcell{0.077}{1.4} & \benchcell{0.058}{1.8} & \benchcell{0.283}{0.4} & \benchcell{0.024}{4.3} & \benchcell{0.066}{1.6} & \benchcell{0.286}{0.4} \\
5 & 1.754 & \benchcell{3.935}{0.4} & \benchcell{0.483}{3.6} & \benchcell{1.326}{1.3} & \benchcell{0.781}{2.2} & \benchcell{0.377}{4.7} & \benchcell{1.300}{1.3} \\
9 & 10.212 & \benchcell{17.634}{0.6} & \benchcell{1.453}{7.0} & \benchcell{3.127}{3.3} & \benchcell{3.224}{3.2} & \benchcell{1.172}{8.7} & \benchcell{2.403}{4.2} \\
13 & 33.853 & \benchcell{54.497}{0.6} & \benchcell{3.178}{10.7} & \benchcell{5.814}{5.8} & \benchcell{9.979}{3.4} & \benchcell{3.313}{10.2} & \benchcell{4.976}{6.8} \\
17 & 118.626 & \benchcell{126.821}{0.9} & \benchcell{6.945}{17.1} & \benchcell{8.093}{14.7} & \benchcell{21.493}{5.5} & \benchcell{6.807}{17.4} & \benchcell{6.416}{18.5} \\
21 & 407.037 & \benchcell{241.287}{1.7} & \benchcell{18.313}{22.2} & \benchcell{11.749}{34.6} & \benchcell{44.341}{9.2} & \benchcell{13.805}{29.5} & \benchcell{9.117}{44.6} \\
\hline
\end{tabular}

\begin{flushleft}
\footnotesize
\textit{Note:} Mean equilibrium-solver runtimes in seconds for \texttt{futhark01}. Speedup relative to MATLAB on \texttt{futhark01} for the same number of car types is shown below each runtime in parentheses. MATLAB runtimes are averaged over 10 benchmark runs. Futhark C-backend runtimes are averaged over 3 runs, while Futhark multicore and CUDA runtimes are averaged over 6 runs where available. The benchmark uses two household types and maximal age 25. Base denotes the AD-based implementation, while Manual denotes the implementation using manually derived derivatives.
\end{flushleft}
\end{table}



\begin{table}[H]
\caption{Extended \texttt{futhark01} car-type benchmark}
\label{tab:bench-cars-extended-futhark01}
\centering
\small
\renewcommand{\arraystretch}{1.15}
\begin{tabular}{rcccc}
\hline
Car types & Base-M & Base-CUDA & Manual-M & Manual-CUDA \\
\hline
25 & 25.844 & 16.696 & 17.953 & 12.500 \\
29 & 29.557 & 228.438 & 26.229 & 15.808 \\
33 & 50.156 & 602.064 & 25.198 & 20.202 \\
40 &  &  & 47.708 & 290.520 \\
45 &  &  & 65.478 & 749.936 \\
50 &  &  & 66.718 & 1219.442 \\
\hline
\end{tabular}

\begin{flushleft}
\footnotesize
\textit{Note:} Mean equilibrium-solver runtimes in seconds for the extended \texttt{futhark01} benchmark. These runs include only the multicore and CUDA backends for car-type configurations larger than those included in Table~\ref{tab:bench-cars-long-futhark01}. Each reported runtime is averaged over 6 benchmark runs. The benchmark uses two household types and maximal age 25. Base denotes the AD-based implementation, while Manual denotes the implementation using manually derived derivatives.
\end{flushleft}
\end{table}

##### CUDA vs non-CUDA prices (configs without a MATLAB reference)

In [106]:
def cuda_vs_noncuda_diffs(val_dir='validation_files',
                          mat_dir='matlab_results_for_validation'):
    """Per-config max |U_prices - other_backend_prices| where both a CUDA ('U')
    .val file and at least one non-CUDA .val file exist, and there is no
    matching MATLAB reference file.

    Returns a DataFrame with one row per (config, non-CUDA backend).
    """
    val_dir = Path(val_dir)
    mat_dir = Path(mat_dir)

    groups = {}
    for path in sorted(val_dir.glob('*.val')):
        m = _FUT_FILE_RE.match(path.name)
        if m is None:
            continue
        key = (m['run_equi'], m['val_name'],
               int(m['n']), int(m['c']), int(m['abar']),
               int(m['acc0']), int(m['trans']))
        groups.setdefault(key, {})[m['backend']] = path

    results = []
    for key, backends in groups.items():
        run_equi, val_name, n, c, abar, acc0, trans = key

        mat_path = mat_dir / f"matlab-validate_solve-{n}-{c}-{abar}-{acc0}-{trans}.dat"
        if mat_path.exists():
            continue
        if 'U' not in backends or len(backends) < 2:
            continue

        u_prices = parse_futhark_prices(backends['U'])
        for b, p in backends.items():
            if b == 'U':
                continue
            other = parse_futhark_prices(p)
            diff = np.abs(u_prices - other)
            results.append({
                'run_equi': run_equi, 'val_name': val_name,
                'n': n, 'c': c, 'abar': abar, 'acc0': acc0, 'trans': trans,
                'other_backend': b,
                'max_abs_diff': float(np.max(diff)),
                'max_rel_diff': float(np.max(diff / np.maximum(np.abs(other), 1e-12))),
            })

    df = pd.DataFrame(results)
    if not df.empty:
        df = df.sort_values(['run_equi', 'val_name', 'n', 'c', 'abar',
                             'acc0', 'trans', 'other_backend']
                           ).reset_index(drop=True)
    return df


display(cuda_vs_noncuda_diffs())

,run_equi,val_name,n,c,abar,acc0,trans,other_backend,max_abs_diff,max_rel_diff
0,run_equilibrium,futhark01,2,25,25,5,0,M,0.003621,0.000193
1,run_equilibrium,futhark01,2,29,25,5,0,M,0.002368,0.000127
2,run_equilibrium,futhark01,2,33,25,5,0,M,0.000134,0.000009
3,run_equilibrium_almost_full_ad,futhark01,2,25,25,5,0,M,0.003621,0.000193
4,run_equilibrium_almost_full_ad,futhark01,2,29,25,5,0,M,0.002368,0.000127
5,run_equilibrium_almost_full_ad,futhark01,2,33,25,5,0,M,0.000134,0.000009
6,run_equilibrium_man,futhark01,2,25,25,5,0,M,0.003621,0.000193
7,run_equilibrium_man,futhark01,2,29,25,5,0,M,0.002368,0.000127
8,run_equilibrium_man,futhark01,2,33,25,5,0,M,0.000134,0.000009
9,run_equilibrium_man,futhark01,2,40,25,5,0,M,0.000079,0.000005
10,run_equilibrium_man,futhark01,2,45,25,5,0,M,0.000172,0.000009
11,run_equilibrium_man,futhark01,2,50,25,5,0,M,0.000128,0.000007